// Anatomy curriculum seed data: subject, modules, topics, NMC competencies
export const anatomySubject = {
  name: "Anatomy",
  code: "AN",
  phase: "PHASE_1" as const,
  totalHours: 700,
  description: "Study of human body structure - gross anatomy, histology, embryology, neuroanatomy",
  iconUrl: null,
  sortOrder: 1,
};

export const anatomyModules = [
  { code: "AN-MOD-01", name: "Upper Limb", description: "Shoulder, arm, forearm, hand anatomy", estimatedHours: 60, sortOrder: 1 },
  { code: "AN-MOD-02", name: "Lower Limb", description: "Hip, thigh, leg, foot anatomy", estimatedHours: 55, sortOrder: 2 },
  { code: "AN-MOD-03", name: "Thorax", description: "Heart, lungs, mediastinum, thoracic wall", estimatedHours: 50, sortOrder: 3 },
  { code: "AN-MOD-04", name: "Abdomen", description: "GI tract, liver, spleen, kidneys, peritoneum", estimatedHours: 55, sortOrder: 4 },
  { code: "AN-MOD-05", name: "Pelvis & Perineum", description: "Pelvic organs, perineal muscles, reproductive anatomy", estimatedHours: 40, sortOrder: 5 },
  { code: "AN-MOD-06", name: "Head & Neck", description: "Skull, face, pharynx, larynx, cranial nerves", estimatedHours: 70, sortOrder: 6 },
  { code: "AN-MOD-07", name: "Neuroanatomy", description: "Brain, spinal cord, meninges, CSF, tracts", estimatedHours: 60, sortOrder: 7 },
  { code: "AN-MOD-08", name: "General Anatomy", description: "Bones, joints, muscles, connective tissues", estimatedHours: 30, sortOrder: 8 },
  { code: "AN-MOD-09", name: "Histology", description: "Epithelium, connective tissue, muscle, nervous tissue", estimatedHours: 40, sortOrder: 9 },
  { code: "AN-MOD-10", name: "Embryology", description: "Gametogenesis, fertilization, organ development", estimatedHours: 35, sortOrder: 10 },
];

export const anatomyTopics: Record<string, Array<{ code: string; name: string; sortOrder: number; competencyCode: string; competencyDesc: string }>> = {
  "AN-MOD-01": [
    { code: "AN-MOD-01-TOP-01", name: "Pectoral Region & Breast", sortOrder: 1, competencyCode: "AN2.1", competencyDesc: "Describe the anatomy of pectoral region and breast" },
    { code: "AN-MOD-01-TOP-02", name: "Axilla", sortOrder: 2, competencyCode: "AN3.1", competencyDesc: "Describe the boundaries, contents, and applied anatomy of axilla" },
    { code: "AN-MOD-01-TOP-03", name: "Shoulder Joint & Scapular Region", sortOrder: 3, competencyCode: "AN4.1", competencyDesc: "Describe the anatomy of shoulder joint and scapular region" },
    { code: "AN-MOD-01-TOP-04", name: "Arm: Muscles & Nerves", sortOrder: 4, competencyCode: "AN5.1", competencyDesc: "Describe the muscles, nerves, and vessels of the arm" },
    { code: "AN-MOD-01-TOP-05", name: "Brachial Plexus", sortOrder: 5, competencyCode: "AN6.1", competencyDesc: "Describe the formation, branches, and applied anatomy of brachial plexus" },
    { code: "AN-MOD-01-TOP-06", name: "Forearm: Anterior & Posterior Compartments", sortOrder: 6, competencyCode: "AN7.1", competencyDesc: "Describe the muscles, nerves, and vessels of the forearm" },
    { code: "AN-MOD-01-TOP-07", name: "Hand: Muscles & Spaces", sortOrder: 7, competencyCode: "AN8.1", competencyDesc: "Describe the muscles, spaces, and applied anatomy of the hand" },
    { code: "AN-MOD-01-TOP-08", name: "Joints of Upper Limb", sortOrder: 8, competencyCode: "AN9.1", competencyDesc: "Describe the joints of upper limb with clinical correlations" },
  ],
  "AN-MOD-02": [
    { code: "AN-MOD-02-TOP-01", name: "Front of Thigh", sortOrder: 1, competencyCode: "AN14.1", competencyDesc: "Describe the muscles, vessels, and nerves of the front of thigh" },
    { code: "AN-MOD-02-TOP-02", name: "Medial Side of Thigh", sortOrder: 2, competencyCode: "AN14.3", competencyDesc: "Describe the adductor compartment of thigh" },
    { code: "AN-MOD-02-TOP-03", name: "Gluteal Region", sortOrder: 3, competencyCode: "AN15.1", competencyDesc: "Describe the gluteal muscles and structures" },
    { code: "AN-MOD-02-TOP-04", name: "Back of Thigh & Popliteal Fossa", sortOrder: 4, competencyCode: "AN15.3", competencyDesc: "Describe the posterior compartment of thigh and popliteal fossa" },
    { code: "AN-MOD-02-TOP-05", name: "Leg: Anterior & Lateral Compartments", sortOrder: 5, competencyCode: "AN16.1", competencyDesc: "Describe the muscles and nerves of the leg" },
    { code: "AN-MOD-02-TOP-06", name: "Leg: Posterior Compartment", sortOrder: 6, competencyCode: "AN16.3", competencyDesc: "Describe the posterior compartment of leg" },
    { code: "AN-MOD-02-TOP-07", name: "Foot & Joints of Lower Limb", sortOrder: 7, competencyCode: "AN17.1", competencyDesc: "Describe the anatomy of foot and joints of lower limb" },
  ],
  "AN-MOD-03": [
    { code: "AN-MOD-03-TOP-01", name: "Thoracic Wall & Diaphragm", sortOrder: 1, competencyCode: "AN21.1", competencyDesc: "Describe the thoracic wall, intercostal spaces, and diaphragm" },
    { code: "AN-MOD-03-TOP-02", name: "Pleura & Lungs", sortOrder: 2, competencyCode: "AN22.1", competencyDesc: "Describe the anatomy of pleura and lungs" },
    { code: "AN-MOD-03-TOP-03", name: "Mediastinum", sortOrder: 3, competencyCode: "AN23.1", competencyDesc: "Describe the divisions and contents of mediastinum" },
    { code: "AN-MOD-03-TOP-04", name: "Heart: External Features", sortOrder: 4, competencyCode: "AN24.1", competencyDesc: "Describe the external features and relations of heart" },
    { code: "AN-MOD-03-TOP-05", name: "Heart: Internal Features & Conducting System", sortOrder: 5, competencyCode: "AN24.5", competencyDesc: "Describe the internal features and conducting system of heart" },
    { code: "AN-MOD-03-TOP-06", name: "Great Vessels & Pericardium", sortOrder: 6, competencyCode: "AN25.1", competencyDesc: "Describe the great vessels and pericardium" },
  ],
  "AN-MOD-04": [
    { code: "AN-MOD-04-TOP-01", name: "Anterior Abdominal Wall", sortOrder: 1, competencyCode: "AN44.1", competencyDesc: "Describe the layers and muscles of anterior abdominal wall" },
    { code: "AN-MOD-04-TOP-02", name: "Inguinal Region & Hernias", sortOrder: 2, competencyCode: "AN44.5", competencyDesc: "Describe the inguinal canal and types of hernia" },
    { code: "AN-MOD-04-TOP-03", name: "Peritoneum & Peritoneal Cavity", sortOrder: 3, competencyCode: "AN45.1", competencyDesc: "Describe the peritoneum and peritoneal relations" },
    { code: "AN-MOD-04-TOP-04", name: "Stomach, Duodenum & Pancreas", sortOrder: 4, competencyCode: "AN46.1", competencyDesc: "Describe the anatomy of stomach, duodenum, and pancreas" },
    { code: "AN-MOD-04-TOP-05", name: "Small & Large Intestine", sortOrder: 5, competencyCode: "AN47.1", competencyDesc: "Describe the jejunum, ileum, colon, and rectum" },
    { code: "AN-MOD-04-TOP-06", name: "Liver, Gallbladder & Spleen", sortOrder: 6, competencyCode: "AN48.1", competencyDesc: "Describe the liver, gallbladder, biliary apparatus, and spleen" },
    { code: "AN-MOD-04-TOP-07", name: "Kidneys, Ureters & Suprarenal Glands", sortOrder: 7, competencyCode: "AN49.1", competencyDesc: "Describe the kidneys, ureters, and suprarenal glands" },
  ],
  "AN-MOD-05": [
    { code: "AN-MOD-05-TOP-01", name: "Bony Pelvis & Pelvic Floor", sortOrder: 1, competencyCode: "AN50.1", competencyDesc: "Describe the bony pelvis and pelvic floor muscles" },
    { code: "AN-MOD-05-TOP-02", name: "Male Reproductive Organs", sortOrder: 2, competencyCode: "AN51.1", competencyDesc: "Describe the male reproductive organs" },
    { code: "AN-MOD-05-TOP-03", name: "Female Reproductive Organs", sortOrder: 3, competencyCode: "AN52.1", competencyDesc: "Describe the uterus, ovaries, and fallopian tubes" },
    { code: "AN-MOD-05-TOP-04", name: "Urinary Bladder & Urethra", sortOrder: 4, competencyCode: "AN53.1", competencyDesc: "Describe the urinary bladder and urethra" },
    { code: "AN-MOD-05-TOP-05", name: "Perineum", sortOrder: 5, competencyCode: "AN54.1", competencyDesc: "Describe the anatomy of perineum" },
  ],
  "AN-MOD-06": [
    { code: "AN-MOD-06-TOP-01", name: "Scalp, Temple & Face", sortOrder: 1, competencyCode: "AN26.1", competencyDesc: "Describe the layers of scalp and muscles of face" },
    { code: "AN-MOD-06-TOP-02", name: "Parotid Region & Facial Nerve", sortOrder: 2, competencyCode: "AN27.1", competencyDesc: "Describe the parotid gland and facial nerve" },
    { code: "AN-MOD-06-TOP-03", name: "Oral Cavity, Tongue & Palate", sortOrder: 3, competencyCode: "AN35.1", competencyDesc: "Describe the anatomy of oral cavity and tongue" },
    { code: "AN-MOD-06-TOP-04", name: "Pharynx & Larynx", sortOrder: 4, competencyCode: "AN36.1", competencyDesc: "Describe the anatomy of pharynx and larynx" },
    { code: "AN-MOD-06-TOP-05", name: "Neck: Triangles & Root", sortOrder: 5, competencyCode: "AN32.1", competencyDesc: "Describe the triangles of neck and root of neck" },
    { code: "AN-MOD-06-TOP-06", name: "Thyroid & Parathyroid Glands", sortOrder: 6, competencyCode: "AN33.1", competencyDesc: "Describe the thyroid and parathyroid glands" },
    { code: "AN-MOD-06-TOP-07", name: "Cranial Nerves", sortOrder: 7, competencyCode: "AN29.1", competencyDesc: "Describe the origin, course, and distribution of cranial nerves" },
    { code: "AN-MOD-06-TOP-08", name: "Orbit & Eye", sortOrder: 8, competencyCode: "AN31.1", competencyDesc: "Describe the anatomy of orbit and eyeball" },
  ],
  "AN-MOD-07": [
    { code: "AN-MOD-07-TOP-01", name: "Meninges, Ventricles & CSF", sortOrder: 1, competencyCode: "AN55.1", competencyDesc: "Describe the meninges, ventricular system, and CSF circulation" },
    { code: "AN-MOD-07-TOP-02", name: "Cerebrum: Lobes & Functional Areas", sortOrder: 2, competencyCode: "AN56.1", competencyDesc: "Describe the cerebral hemispheres and functional areas" },
    { code: "AN-MOD-07-TOP-03", name: "Brainstem", sortOrder: 3, competencyCode: "AN57.1", competencyDesc: "Describe the anatomy of midbrain, pons, and medulla" },
    { code: "AN-MOD-07-TOP-04", name: "Cerebellum & Basal Ganglia", sortOrder: 4, competencyCode: "AN58.1", competencyDesc: "Describe the cerebellum and basal ganglia" },
    { code: "AN-MOD-07-TOP-05", name: "Spinal Cord & Tracts", sortOrder: 5, competencyCode: "AN59.1", competencyDesc: "Describe the spinal cord segments and ascending/descending tracts" },
    { code: "AN-MOD-07-TOP-06", name: "Blood Supply of Brain", sortOrder: 6, competencyCode: "AN60.1", competencyDesc: "Describe the arterial supply and venous drainage of brain" },
  ],
  "AN-MOD-08": [
    { code: "AN-MOD-08-TOP-01", name: "Bones: Classification & Ossification", sortOrder: 1, competencyCode: "AN1.1", competencyDesc: "Describe classification and general features of bones" },
    { code: "AN-MOD-08-TOP-02", name: "Joints: Classification & Movements", sortOrder: 2, competencyCode: "AN1.2", competencyDesc: "Describe types of joints and their movements" },
    { code: "AN-MOD-08-TOP-03", name: "Muscles: Types & Actions", sortOrder: 3, competencyCode: "AN1.3", competencyDesc: "Describe the types and actions of muscles" },
    { code: "AN-MOD-08-TOP-04", name: "Blood Vessels, Lymphatics & Nerves", sortOrder: 4, competencyCode: "AN1.4", competencyDesc: "Describe general features of blood vessels, lymphatics, and nerves" },
  ],
  "AN-MOD-09": [
    { code: "AN-MOD-09-TOP-01", name: "Epithelial Tissue", sortOrder: 1, competencyCode: "AN65.1", competencyDesc: "Classify and identify epithelial tissues" },
    { code: "AN-MOD-09-TOP-02", name: "Connective Tissue", sortOrder: 2, competencyCode: "AN65.2", competencyDesc: "Describe types of connective tissue" },
    { code: "AN-MOD-09-TOP-03", name: "Muscle Tissue", sortOrder: 3, competencyCode: "AN66.1", competencyDesc: "Describe types of muscle tissue" },
    { code: "AN-MOD-09-TOP-04", name: "Nervous Tissue", sortOrder: 4, competencyCode: "AN67.1", competencyDesc: "Describe the structure of neurons and neuroglia" },
    { code: "AN-MOD-09-TOP-05", name: "Special Histology (Organs)", sortOrder: 5, competencyCode: "AN68.1", competencyDesc: "Identify histological features of organs" },
  ],
  "AN-MOD-10": [
    { code: "AN-MOD-10-TOP-01", name: "Gametogenesis & Fertilization", sortOrder: 1, competencyCode: "AN73.1", competencyDesc: "Describe gametogenesis and fertilization" },
    { code: "AN-MOD-10-TOP-02", name: "Implantation & Placenta", sortOrder: 2, competencyCode: "AN74.1", competencyDesc: "Describe implantation and placental development" },
    { code: "AN-MOD-10-TOP-03", name: "Embryonic Period & Folding", sortOrder: 3, competencyCode: "AN75.1", competencyDesc: "Describe the embryonic period and body folding" },
    { code: "AN-MOD-10-TOP-04", name: "Developmental Anomalies", sortOrder: 4, competencyCode: "AN76.1", competencyDesc: "Describe common congenital anomalies and their embryological basis" },
  ],
};
