export const obgMcqs2 = [
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old primigravida at 35 weeks presents with severe headache, visual disturbances, and BP 165/110 mmHg. Which pathophysiologic mechanism is responsible for her symptoms?",
    clinicalVignette: "A 28-year-old G2P1 at 35 weeks presents with severe persistent headache, blurred vision, right upper quadrant pain, and edema. BP is 165/110 mmHg, urinalysis shows 3+ proteinuria. Laboratory: platelet count 95,000/µL, AST 88 U/L. She has evidence of preeclampsia with severe features.",
    options: [
      { id: "a", text: "Vasospasm from endothelial dysfunction causing inadequate cerebral perfusion", isCorrect: true, explanation: "Preeclampsia is characterized by placental dysfunction leading to release of placental factors (sFlt1, sEng) that cause systemic endothelial dysfunction. This leads to: (1) Increased vascular permeability → edema and hypovolemia, (2) Vasospasm → hypertension and reduced organ perfusion, (3) Placental ischemia from vasospasm. Vasospasm in the cerebral circulation causes symptoms: severe headache, visual disturbances, hyperreflexia, and seizures in eclampsia. Endothelial dysfunction also causes platelet activation/consumption (thrombocytopenia), hepatic injury (elevated transaminases), and renal endothelial damage (proteinuria, azotemia). This patient has preeclampsia with severe features (BP ≥160/110, visual symptoms, RUQ pain, low platelets, elevated liver enzymes)" },
      { id: "b", text: "Acute volume overload from excessive sodium retention", isCorrect: false, explanation: "While sodium retention occurs, preeclampsia involves vasoconstriction with relative hypovolemia" },
      { id: "c", text: "Eclamptic seizure from cerebral edema", isCorrect: false, explanation: "While cerebral edema occurs in eclampsia, vasospasm is the primary mechanism" },
      { id: "d", text: "Placental abruption from massive hemorrhage", isCorrect: false, explanation: "Abruption is a complication, not the underlying mechanism" },
    ],
    explanation: "Preeclampsia management depends on gestational age: <34 weeks → corticosteroids for fetal lung maturity + delivery at 34 weeks (if stable) or immediately (if unstable). ≥34 weeks → delivery is indicated. Management includes magnesium sulfate (seizure prophylaxis), antihypertensive agents for BP >160/110, and supportive care. HELLP syndrome (hemolysis, elevated liver enzymes, low platelets) is a severe variant with poor prognosis.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-01-TOP-01",
    textbookRefs: [{ book: "Williams Obstetrics", chapter: "Ch 34", edition: "25th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 32-year-old G3P2 at 32 weeks with sudden severe abdominal pain, vaginal bleeding, and a firm, tender uterus is suspected of having placental abruption. Which mechanism explains the severe maternal complication?",
    clinicalVignette: "A 32-year-old G3P2 with poorly controlled hypertension presents suddenly with severe abdominal pain and vaginal bleeding. Vital signs show tachycardia (HR 125), hypotension (BP 90/55), and cool extremities. The uterus is firm and tender throughout. Fetal heart rate is absent. CBC shows Hb 7.5 g/dL and platelet count 85,000/µL.",
    options: [
      { id: "a", text: "Direct fetal blood loss from placental separation", isCorrect: false, explanation: "Most bleeding in abruption is maternal, not fetal" },
      { id: "b", text: "Massive maternal hemorrhage with coagulopathy from thromboplastin release", isCorrect: true, explanation: "Placental abruption (premature separation) causes: (1) Massive maternal hemorrhage from torn placental bed vessels, (2) Release of thromboplastin and tissue factor from separated placenta → activation of coagulation cascade and DIC, (3) Consumption of platelets and clotting factors → coagulopathy, (4) Shock from hemorrhage and loss of uterine contractility. This patient has Class III hemorrhage (>30-40% blood volume loss): hypotension, tachycardia, cool extremities, and oliguria. Fetal death occurs from placental insufficiency. Complications include maternal death (1-5%), renal failure from shock, and DIC with severe bleeding" },
      { id: "c", text: "Umbilical cord compression from uterine irritability", isCorrect: false, explanation: "Cord compression occurs but fetal death is from placental separation" },
      { id: "d", text: "Amniotic fluid embolism from ruptured membranes", isCorrect: false, explanation: "AFE is a separate complication" },
    ],
    explanation: "Management of placental abruption: (1) Immediate stabilization (IV access ×2, aggressive fluid resuscitation, blood products), (2) Emergency cesarean delivery, (3) Management of DIC with FFP, platelets, and cryoprecipitate, (4) ICU monitoring for complications (acute renal failure, eclampsia, pulmonary edema). Maternal mortality in abruption is 1-5%; fetal mortality is 10-50% depending on severity.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-02-TOP-01",
    textbookRefs: [{ book: "Williams Obstetrics", chapter: "Ch 36", edition: "25th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 24-year-old G1P0 with positive pregnancy test, severe lower abdominal pain, and vaginal bleeding is found to have a ruptured ectopic pregnancy. Which anatomic location predisposes to rupture?",
    clinicalVignette: "A 24-year-old G1P0 at 7 weeks gestation (by LMP) presents to the ED with acute-onset severe left lower abdominal pain and vaginal bleeding. Vital signs show tachycardia (HR 130), hypotension (BP 85/50), and pallor. Serum β-hCG is 35,000 mIU/mL. Transvaginal ultrasound confirms gestational sac in the left fallopian tube with free fluid in pelvis.",
    options: [
      { id: "a", text: "Interstitial/cornual pregnancy (highest rupture risk and maternal mortality)", isCorrect: true, explanation: "Ectopic pregnancy occurs when the fertilized ovum implants outside the uterine cavity. Common sites (order of frequency): ampulla of fallopian tube (70%), isthmus (12%), interstitium (2-3%), ovary (0.5%), abdomen (0.1%). However, interstitial pregnancy carries the highest rupture risk and maternal mortality (2.5%) because: (1) The interstitial portion of the tube has rich vascularization (branches from uterine artery), (2) The myometrium expands more than the fallopian tube, allowing larger gestational sac before rupture (typically ruptures at 12-16 weeks vs 8-12 weeks for tubal), (3) Rupture causes massive hemorrhage. This patient's isthmic location still carries significant rupture risk (ruptures around 8-12 weeks)" },
      { id: "b", text: "Ampullary pregnancy (slowest growth due to wider lumen)", isCorrect: false, explanation: "While ampullary pregnancies may grow slightly longer, they still rupture" },
      { id: "c", text: "Ovarian pregnancy (contained within ovarian parenchyma)", isCorrect: false, explanation: "Ovarian pregnancies are rare but do rupture" },
      { id: "d", text: "Abdominal pregnancy (free within peritoneal cavity)", isCorrect: false, explanation: "Abdominal pregnancies can continue longer but carry fetal demise risk" },
    ],
    explanation: "This patient presents with hemodynamically unstable ruptured ectopic pregnancy (class III hemorrhage). Management: emergency surgery (salpingostomy or salpingectomy depending on contralateral tube and future fertility desires), massive transfusion protocol, and ICU monitoring. Risk factors for ectopic: previous ectopic, PID, endometriosis, IUD use, tubal surgery. Prevention with barrier contraception to reduce PID/STI risk.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-02-TOP-02",
    textbookRefs: [{ book: "Williams Obstetrics", chapter: "Ch 18", edition: "25th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old G2P1 at 38 weeks with severe headache, scotomata (visual flashes), and a hyperreflexic exam develops a seizure. Which syndrome is this?",
    clinicalVignette: "A 28-year-old G2P1 at 38 weeks of gestation with prior preeclampsia develops severe headache, photopsia (visual flashes), and right upper quadrant pain. On examination, she is hyperreflexic (3+) with ankle clonus. Suddenly, she develops a generalized tonic-clonic seizure lasting 90 seconds. BP is 175/115 mmHg, urinalysis shows 2+ proteinuria.",
    options: [
      { id: "a", text: "Preeclampsia with severe features", isCorrect: false, explanation: "While she has preeclampsia, seizure defines eclampsia" },
      { id: "b", text: "Eclampsia (preeclampsia + seizures)", isCorrect: true, explanation: "Eclampsia is the development of seizures in a patient with preeclampsia/gestational hypertension. Seizures can occur antepartum (50%), intrapartum (25%), or postpartum (25%). Mechanism: cerebral vasospasm and endothelial dysfunction leading to cerebral edema and seizures. Symptoms preceding seizure (as in this patient): severe headache, visual disturbances (scotomata, photopsia, cortical blindness), hyperreflexia, and clonus. Eclampsia is a medical emergency with maternal mortality 5-14% if untreated. Magnesium sulfate is the anticonvulsant of choice (reduces seizure recurrence by 50% vs diazepam)" },
      { id: "c", text: "Amniotic fluid embolism", isCorrect: false, explanation: "AFE presents with acute cardiopulmonary collapse, not seizure from hypertension" },
      { id: "d", text: "Intracranial hemorrhage from chronic hypertension", isCorrect: false, explanation: "While hypertensive hemorrhage can occur, the clinical picture fits eclampsia" },
    ],
    explanation: "Management of eclampsia: (1) Magnesium sulfate (4-6 g IV load, then 1-2 g/hour maintenance), (2) Seizure precautions (quiet dark room, side rails), (3) BP control (labetalol or hydralazine for BP >160/110), (4) Delivery within 12-24 hours postpartum (or as soon as seizures controlled in antepartum eclampsia). Aspiration precautions (suction available) are essential as aspiration is a leading preventable cause of eclamptic death.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-01-TOP-02",
    textbookRefs: [{ book: "Williams Obstetrics", chapter: "Ch 34", edition: "25th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 32-year-old G3P2 with PCOS and obesity (BMI 35) is evaluated for infertility. Which hormonal abnormality explains the irregular menstrual cycles and anovulation?",
    clinicalVignette: "A 32-year-old G3P2 with PCOS (irregular cycles every 2-3 months, hirsutism, acne) has been trying to conceive for 2 years. Laboratory findings: LH 25 mIU/mL (elevated), FSH 7 mIU/mL (normal), LH:FSH ratio 3.5:1, testosterone 85 ng/dL (elevated), DHEA-S normal. She has multiple ovarian cysts on ultrasound.",
    options: [
      { id: "a", text: "Absolute FSH deficiency from pituitary tumors", isCorrect: false, explanation: "FSH is normal; the issue is relative elevation of LH" },
      { id: "b", text: "Excessive LH secretion causing abnormal follicular development and anovulation", isCorrect: true, explanation: "PCOS is characterized by: (1) Hyperandrogenism (elevated testosterone, DHEA-S, androstenediol), (2) Anovulation/oligomenorrhea from abnormal gonadotropin secretion (elevated LH, low-normal FSH, elevated LH:FSH ratio >2:1 or 3:1), (3) Polycystic ovaries (ultrasound criteria: ≥12 follicles per ovary, or ovarian volume ≥10 mL). The elevated LH stimulates excessive androgen production by theca cells. The resulting hyperandrogenism inhibits FSH-dependent aromatase, preventing normal follicle maturation and estrogen production. Without the LH surge (from normal estrogen feedback), ovulation doesn't occur, causing anovulation and infertility" },
      { id: "c", text: "Insulin resistance causing impaired gluconeogenesis", isCorrect: false, explanation: "Insulin resistance is a feature but hormonal imbalance drives anovulation" },
      { id: "d", text: "Prolactin excess from hypothyroidism", isCorrect: false, explanation: "While PCOS can coexist with hypothyroidism, elevated LH is the key finding" },
    ],
    explanation: "Management of PCOS-related infertility: (1) Weight loss (even 5-10% reduces LH, improves ovulation), (2) Ovulation induction with clomiphene citrate (first-line) or letrozole (second-line), (3) Metformin (improves insulin sensitivity, aids weight loss), (4) Assisted reproductive technology if clomiphene/letrozole fail. PCOS increases risk of gestational diabetes, preeclampsia, and metabolic syndrome.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-03-TOP-01",
    textbookRefs: [{ book: "Williams Gynecology", chapter: "Ch 40", edition: "4th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old G2P1 presents with infertility and dysmenorrhea. Laparoscopy shows powder-burn lesions and adhesions. Which tissue defect explains the dyspareunia?",
    clinicalVignette: "A 35-year-old G2P1 with 10-year history of dysmenorrhea and dyspareunia undergoes diagnostic laparoscopy for suspected endometriosis. Findings confirm endometriosis (powder-burn lesions on peritoneum, chocolate cysts in bilateral ovaries, dense adhesions). She has not conceived despite normal semen analysis and regular ovulation.",
    options: [
      { id: "a", text: "Ectopic endometrial tissue with inflammatory response causing pain", isCorrect: true, explanation: "Endometriosis is the presence of endometrial glands and stroma outside the uterus (most commonly peritoneum, ovaries, fallopian tubes, rectosigmoid). Ectopic endometrium undergoes cyclic bleeding with menses, causing: (1) Dysmenorrhea and dyspareunia from inflammatory response (elevated prostaglandins, inflammatory cytokines), (2) Pelvic adhesions from repeated bleeding and inflammation, (3) Infertility from ovulatory dysfunction, tubal obstruction, and impaired embryo implantation. Pain is due to local inflammation and prostaglandin production, not mechanical obstruction alone. Lesions appear as powder-burn (black/brown), red (active), or white (fibrotic) endometrial implants" },
      { id: "b", text: "Mechanical obstruction of fallopian tubes from scar tissue", isCorrect: false, explanation: "While mechanical obstruction occurs, dyspareunia results from inflammatory response" },
      { id: "c", text: "Adenomyosis with myometrial invasion", isCorrect: false, explanation: "Adenomyosis is endometrial invasion of myometrium; peritoneal lesions are endometriosis" },
      { id: "d", text: "Fibroids with distorted uterine cavity", isCorrect: false, explanation: "Fibroids are leiomyomas (smooth muscle), not endometriosis" },
    ],
    explanation: "Management of endometriosis: (1) NSAIDs for pain (target prostaglandins), (2) Hormonal suppression: OCPs (continuous dosing preferred), progestins, GnRH agonists with add-back therapy, (3) Surgical resection/ablation via laparoscopy (improves fertility and pain), (4) Assisted reproductive technology for severe endometriosis with infertility. Pregnancy temporarily improves symptoms (due to decidualization of ectopic endometrium), but endometriosis often recurs postpartum.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-03-TOP-02",
    textbookRefs: [{ book: "Williams Gynecology", chapter: "Ch 19", edition: "4th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old G1P0 at 10 weeks gestation presents with vaginal bleeding and lower abdominal pain. Ultrasound shows no fetal pole despite appropriate gestational sac size. Which diagnosis is most likely?",
    clinicalVignette: "A 28-year-old G1P0 at 10 weeks gestation (by LMP) presents with vaginal bleeding and mild cramping. Transvaginal ultrasound shows a gestational sac measuring 35 mm (appropriate for 9-10 weeks) but no yolk sac or fetal pole. Repeat ultrasound in 1 week shows no interval growth of gestational sac.",
    options: [
      { id: "a", text: "Blighted ovum (anembryonic pregnancy)", isCorrect: true, explanation: "A blighted ovum is a pregnancy in which a gestational sac develops but no embryo forms (anembryonic pregnancy). Ultrasound criteria for diagnosis: (1) Gestational sac >25 mm without yolk sac (if transabdominal ultrasound or >20 mm if transvaginal), (2) Gestational sac >16 mm without fetal pole (transvaginal). This patient meets criteria (35 mm sac, no fetal pole). Absence of interval growth on repeat ultrasound confirms the diagnosis. Blighted ovum accounts for ~50% of first-trimester losses. β-hCG levels may still be appropriate for gestational age, but no embryonic development occurs" },
      { id: "b", text: "Threatened abortion with viable intrauterine pregnancy", isCorrect: false, explanation: "A viable pregnancy would show fetal pole with cardiac activity" },
      { id: "c", text: "Complete molar pregnancy with trophoblastic proliferation", isCorrect: false, explanation: "Molar pregnancy shows no fetal pole but has abnormal chorionic tissue (would see hydropic/edematous appearance and high β-hCG)" },
      { id: "d", text: "Ectopic pregnancy with concurrent intrauterine sac", isCorrect: false, explanation: "While rare, the sac characteristics suggest intrauterine blighted ovum" },
    ],
    explanation: "Management of blighted ovum: (1) Expectant management (spontaneous passage in 50-80% within 4-8 weeks), (2) Medical management (misoprostol), (3) Surgical evacuation (curettage). RhoGAM (anti-D immunoglobulin) is given to Rh-negative women to prevent isoimmunization. After pregnancy loss, β-hCG should be followed to undetectable levels to ensure complete evacuation and rule out persistent gestational trophoblastic disease.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-04-TOP-01",
    textbookRefs: [{ book: "Williams Obstetrics", chapter: "Ch 17", edition: "25th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old woman with a history of normal Pap smears presents with postcoital bleeding and a cervical lesion. Which cellular abnormality most likely explains her presentation?",
    clinicalVignette: "A 35-year-old woman with 15 years of smoking history and multiple sexual partners presents with postcoital bleeding and vulvovaginal discomfort. Speculum exam reveals a 3 cm exophytic lesion on the cervix with irregular borders and friable surface. Cervical biopsy shows keratinizing squamous cell carcinoma.",
    options: [
      { id: "a", text: "Abnormal keratinization from HPV-induced transcription of viral oncogenes E6 and E7", isCorrect: true, explanation: "Cervical cancer develops through a well-characterized progression: normal squamous epithelium → CIN1 (low-grade) → CIN2 (high-grade) → CIN3 (high-grade) → invasive cancer. This is driven primarily by persistent infection with high-risk HPV (types 16, 18, 31, 33, etc.). HPV E6 and E7 oncoproteins inactivate tumor suppressors p53 and Rb, disrupting normal cell cycle control and apoptosis. This allows accumulation of additional mutations leading to dysplasia and eventual malignant transformation. Keratinizing squamous cell carcinoma is the most common type (~70%) and is strongly associated with HPV16" },
      { id: "b", text: "Chronic inflammation from sexually transmitted infections", isCorrect: false, explanation: "While chronic inflammation contributes, HPV oncogenic transformation is primary" },
      { id: "c", text: "Metaplasia of columnar epithelium in the transformation zone", isCorrect: false, explanation: "Metaplasia is normal; dysplasia from HPV causes the lesion" },
      { id: "d", text: "Endocervical adenocarcinoma from PID scarring", isCorrect: false, explanation: "While PID increases cancer risk, HPV-driven squamous malignancy is present here" },
    ],
    explanation: "Cervical cancer prevention: (1) HPV vaccination (Gardasil, Cervarix) for ages 11-45 (protects against high-risk types), (2) Cervical cancer screening via Pap smear or HPV testing, (3) Smoking cessation, (4) Safe sex practices (barrier contraception). Treatment of invasive cervical cancer depends on stage: stage IB1 (≤4 cm, confined to cervix) → radical hysterectomy or combined chemoradiation. Advanced disease (IB2-IIB) → concurrent chemoradiation with cisplatin.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-05-TOP-01",
    textbookRefs: [{ book: "Williams Gynecology", chapter: "Ch 29", edition: "4th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 42-year-old woman with amenorrhea for 6 months, hot flashes, and mood changes is confirmed to have menopause. Which hormonal change is responsible for her vasomotor symptoms?",
    clinicalVignette: "A 42-year-old multiparous woman with 6 months of amenorrhea, frequent hot flashes (10+ per day), night sweats causing sleep disruption, and mood lability is evaluated. FSH is 68 mIU/mL (elevated), LH is 45 mIU/mL (elevated), and estradiol is <15 pg/mL (low). She has normal TSH and normal bone density on DEXA.",
    options: [
      { id: "a", text: "Elevated FSH directly stimulating skin vasomotor responses", isCorrect: false, explanation: "FSH doesn't directly cause vasomotor symptoms" },
      { id: "b", text: "Rapid decline in estrogen causing thermoregulatory dysfunction and increased norepinephrine sensitivity", isCorrect: true, explanation: "Vasomotor symptoms (hot flashes, night sweats) result from estrogen deficiency during menopause. Mechanism: (1) Loss of estrogen leads to reduced inhibition of GnRH neurons in the hypothalamus (GnRH-estrogen feedback), (2) Increased GnRH secretion drives FSH and LH surges, (3) These peptide hormone surges activate kisspeptin neurons that regulate thermoregulation, (4) Altered set-point of the hypothalamic thermoregulatory center causes inappropriate vasodilation and increased sweating (trying to cool core temperature from inappropriately high set-point). Additionally, estrogen deficiency increases sympathetic nerve activity and norepinephrine sensitivity, contributing to symptoms" },
      { id: "c", text: "Elevated testosterone from ovarian androgen synthesis", isCorrect: false, explanation: "Testosterone actually decreases at menopause" },
      { id: "d", text: "Thyroid dysfunction from loss of estrogen-mediated TBG clearance", isCorrect: false, explanation: "While TBG increases with estrogen, normal TSH rules out thyroid dysfunction" },
    ],
    explanation: "Management of menopausal symptoms: (1) Hormone replacement therapy (HRT) with estrogen ± progestin is most effective for vasomotor symptoms (reduces hot flashes by 75%), (2) Non-hormonal options: SSRIs (citalopram, paroxetine), SNRIs (venlafaxine), gabapentin, (3) Lifestyle modifications (cool environment, cotton clothing, avoid triggers). HRT is contraindicated in women with history of breast cancer, active thromboembolism, or acute liver disease. Benefits vs risks of HRT should be individualized.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-06-TOP-01",
    textbookRefs: [{ book: "Williams Gynecology", chapter: "Ch 41", edition: "4th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old G3P2 requesting permanent sterilization chooses an intrauterine copper device (IUD). Which mechanism provides contraceptive efficacy?",
    clinicalVignette: "A 28-year-old G3P2 with completed childbearing chooses a copper IUD (Paragard) for permanent contraception. She is counseled that the device is >99% effective. She is concerned about infections and ectopic pregnancy given the IUD mechanism.",
    options: [
      { id: "a", text: "Cervical mucus thickening from progestin-releasing mechanism", isCorrect: false, explanation: "Copper IUDs don't release progestin; LNG-IUDs do" },
      { id: "b", text: "Inflammatory response and spermicidal effects from copper and prostanoid production", isCorrect: true, explanation: "Copper IUDs (non-hormonal) work through: (1) Inflammatory response in the endometrium to the foreign body, (2) Copper ions that are directly spermicidal, inhibiting sperm motility and function, (3) Increased local prostaglandin production that creates a hostile uterine environment (impairs sperm function and embryo implantation). The failure rate is extremely low (0.8 per 100 woman-years), with most failures occurring in the first year. Importantly, copper IUDs do NOT prevent ovulation, so if pregnancy does occur, it's at higher risk of being ectopic (though absolute ectopic risk remains low because IUDs are so effective at preventing pregnancy)" },
      { id: "c", text: "Suppression of ovulation via GnRH antagonism", isCorrect: false, explanation: "GnRH antagonism doesn't occur with copper IUDs" },
      { id: "d", text: "Mechanical blockade of sperm transport through the fallopian tubes", isCorrect: false, explanation: "While some blockade occurs, spermicidal effects are primary" },
    ],
    explanation: "Copper IUDs are highly effective, safe contraceptives with no systemic side effects. Benefits: >99% effective, long-acting (10-12 years), immediately reversible, no blood clots/stroke/cancer risk. Side effects: heavier/longer periods, dysmenorrhea (in some users). Contraindications: current PID, cervicitis, STI, uterine distortion, heavy/prolonged menstrual bleeding. IUD placement can be done at any time; if placed after week 3 of cycle, backup contraception not needed.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "OG",
    topicCode: "OG-MOD-07-TOP-01",
    textbookRefs: [{ book: "Williams Gynecology", chapter: "Ch 13", edition: "4th" }],
  },
];
