export const pediatricsMcqs2 = [
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 2-day-old neonate with respiratory distress, pink frothy sputum, and cyanosis is found to have hyaline membrane disease. Which pathophysiologic mechanism is responsible?",
    clinicalVignette: "A 2-day-old male born at 32 weeks gestation to a mother with inadequate prenatal care presents with progressive respiratory distress (tachypnea 70/min, grunting, nasal flaring). CXR shows diffuse ground-glass opacities. He has low Apgar scores and delayed cord clamping. FiO2 requirements escalate rapidly.",
    options: [
      { id: "a", text: "Aspiration of meconium causing airway obstruction", isCorrect: false, explanation: "Meconium aspiration causes different CXR findings" },
      { id: "b", text: "Pulmonary surfactant deficiency causing alveolar collapse", isCorrect: true, explanation: "Respiratory distress syndrome (RDS) or hyaline membrane disease occurs primarily in preterm infants due to surfactant deficiency. Surfactant is produced by type II pneumocytes and contains lipoproteins that reduce surface tension, preventing alveolar collapse during expiration. Deficiency causes: (1) Progressive alveolar collapse (atelectasis), (2) Uneven ventilation and hypoxemia, (3) Increased work of breathing, (4) Pulmonary edema from damaged capillaries → hyaline membrane formation. Risk is highest <32 weeks; antenatal corticosteroids (betamethasone) accelerate fetal lung maturity and reduce RDS risk by 40-60%. Treatment includes exogenous surfactant replacement (highly effective) and mechanical ventilation with lung-protective strategies" },
      { id: "c", text: "Pulmonary edema from immature lymphatic drainage", isCorrect: false, explanation: "While lymphatic immaturity contributes, surfactant deficiency is primary" },
      { id: "d", text: "Intracranial hemorrhage causing bradypnea", isCorrect: false, explanation: "This patient has tachypnea, not bradypnea" },
    ],
    explanation: "RDS is the most common cause of respiratory distress in preterm infants. Exogenous surfactant (natural or synthetic) has revolutionized neonatal care, reducing mortality from ~85% (pre-surfactant era) to ~5-10% in developed countries. Complications include air leaks (pneumothorax, pneumomediastinum), chronic lung disease (bronchopulmonary dysplasia), and intraventricular hemorrhage from fluctuating cerebral blood flow.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-01-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 102", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 6-month-old girl with failure to thrive, developmental delay, and hepatosplenomegaly is found to have elevated plasma amino acids (methionine, tyrosine). Which metabolic disease is suspected?",
    clinicalVignette: "A 6-month-old girl, product of consanguineous marriage, presents with poor growth, developmental delay, and hepatomegaly. Laboratory findings: elevated methionine (310 µmol/L, normal <40), elevated tyrosine (350 µmol/L, normal <100), elevated transaminases (ALT 180, AST 240), and indirect hyperbilirubinemia. Urine shows a musty odor.",
    options: [
      { id: "a", text: "Phenylketonuria", isCorrect: false, explanation: "PKU causes elevated phenylalanine, not methionine or tyrosine" },
      { id: "b", text: "Maple syrup urine disease", isCorrect: false, explanation: "MSUD elevates branched-chain amino acids (leucine, isoleucine, valine)" },
      { id: "c", text: "Tyrosinemia type I (hepatorenal tyrosinemia)", isCorrect: true, explanation: "Tyrosinemia type I results from fumarylacetoacetase (FAA) deficiency in the final step of tyrosine degradation. Accumulation of fumarylacetone and succinylacetone (toxic metabolites) causes acute hepatic necrosis, renal tubular dysfunction, and neurological crises. Clinical presentation includes failure to thrive, vomiting, diarrhea, hepatomegaly, cholestasis, coagulopathy, acute liver failure (in severe cases), and renal tubular acidosis. Laboratory findings include elevated tyrosine, methionine (from hepatic synthesis), and succinylacetone (pathognomonic). Urine shows cabbage-like or musty odor" },
      { id: "d", text: "Galactosemia", isCorrect: false, explanation: "Galactosemia elevates galactose and galactose-1-phosphate, not these amino acids" },
    ],
    explanation: "Tyrosinemia type I is managed with nitisinone (NTBC), a potent inhibitor of 4-hydroxyphenylpyruvate dioxygenase, which blocks the pathway upstream of the FAA deficiency. Nitisinone dramatically improves survival (from ~20% to >80% in treated patients). Early diagnosis via newborn screening for succinylacetone allows presymptomatic treatment. Dietary protein and tyrosine restriction are adjunctive measures. Liver transplantation reverses hepatic disease but doesn't address renal or neurological complications.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-02-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 89", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 2-year-old boy with nephrotic syndrome and edema is found to have hypoalbuminemia and selective proteinuria. Which glomerular lesion is responsible?",
    clinicalVignette: "A 2-year-old boy presents with periorbital edema, pale appearance, and generalized edema. Urinalysis shows 4+ proteinuria (9.2 g/24h), with selective proteinuria (primarily albumin). Serum albumin is 2.1 g/dL (low), total protein 5.8 g/dL. Kidney function is normal. Kidney biopsy shows normal light microscopy but fusion of podocyte foot processes on electron microscopy.",
    options: [
      { id: "a", text: "Diffuse proliferative glomerulonephritis", isCorrect: false, explanation: "Proliferative GN has cellular proliferation on light microscopy" },
      { id: "b", text: "Minimal change disease (MCD)", isCorrect: true, explanation: "Minimal change disease is the most common cause of nephrotic syndrome in children (80-90% of cases <6 years). Light microscopy appears normal (hence 'minimal change'), but electron microscopy reveals fusion of podocyte foot processes. This suggests a functional defect in the slit diaphragm rather than structural damage. MCD presents with selective proteinuria (albumin loss), edema, hypoalbuminemia, and hyperlipidemia. Renal function is typically normal. The disease is exquisitely steroid-responsive: 90% of children achieve remission with 8 weeks of prednisone" },
      { id: "c", text: "Membranoproliferative glomerulonephritis", isCorrect: false, explanation: "MPGN has membrane thickening on light microscopy" },
      { id: "d", text: "Focal segmental glomerulosclerosis (FSGS)", isCorrect: false, explanation: "FSGS shows sclerotic lesions on light microscopy" },
    ],
    explanation: "Treatment of MCD in children includes: (1) Corticosteroids (prednisone 2 mg/kg/day for 8 weeks, then taper), (2) Supportive care (salt restriction, diuretics for edema), (3) Albumin infusion if severe hypoalbuminemia causes symptomatic hypotension. Steroid-dependent MCD (frequent relapses with steroid taper) occurs in 20-30% and may require alternative agents (cyclophosphamide, mycophenolate mofetil). Complete remission of proteinuria (with normal renal function) is the goal.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-03-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 533", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 4-month-old infant presents with seizures, poor feeding, and failure to thrive. CSF analysis shows hypoglycorrhachia (CSF glucose 18 mg/dL with plasma 120 mg/dL). Which organism is most likely?",
    clinicalVignette: "A 4-month-old boy (born via vaginal delivery from a mother who tested negative for GBS at 35 weeks) presents with fever, irritability, high-pitched cry, and seizures. CSF analysis shows: WBC 450 (70% neutrophils), protein 280 mg/dL, glucose 18 mg/dL (plasma 120 mg/dL). Gram stain shows gram-negative rod. Culture grows a motile gram-negative rod at 4°C.",
    options: [
      { id: "a", text: "Streptococcus pneumoniae", isCorrect: false, explanation: "Pneumococcus is gram-positive diplococci" },
      { id: "b", text: "Group B Streptococcus", isCorrect: false, explanation: "GBS is gram-positive cocci in chains" },
      { id: "c", text: "Listeria monocytogenes", isCorrect: false, explanation: "Listeria is gram-positive rod but often acid-fast positive" },
      { id: "d", text: "Gram-negative bacilli (E. coli with K1 antigen, Haemophilus influenzae)", isCorrect: true, explanation: "In infants 2-23 months (late-onset neonatal meningitis), gram-negative organisms (primarily E. coli K1 and Haemophilus influenzae type b) are common. E. coli K1 is motile at room temperature and commonly causes meningitis in infants. Features: gram-negative rod, motile (especially at 4°C), and ferments lactose (distinguishes from Salmonella/Shigella). Haemophilus influenzae type b risk has decreased dramatically with Hib vaccination. Empiric therapy for late-onset meningitis includes ceftriaxone ± gentamicin + ampicillin (for Listeria coverage if risk factors)" },
      { id: "e", text: "Neisseria meningitidis", isCorrect: false, explanation: "Meningococcus is gram-negative diplococcus but not motile" },
    ],
    explanation: "Bacterial meningitis in infants has extremely high morbidity and mortality. CSF glucose <40 mg/dL with CSF/plasma ratio <0.4 indicates bacterial meningitis. Diagnosis of organism guides antibiotic selection: E. coli K1 requires ampicillin + gentamicin + cephalosporin (ceftriaxone). Dexamethasone reduces neurological complications by 30-40%. Long-term sequelae include hearing loss (30-40%), developmental delay, and seizure disorder.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-04-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 182", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 6-year-old boy with progressive dyspnea, chest pain, and cyanosis is found to have a large VSD with left-to-right shunt. Which complication develops if repair is delayed?",
    clinicalVignette: "A 6-year-old boy with large VSD (diagnosed at birth) was never repaired due to parental refusal of surgery. He now presents with progressive dyspnea, exertional chest pain, and mild cyanosis. Echocardiography shows right-to-left shunt (reversed from original left-to-right). He has clubbing of fingers. Chest X-ray shows pulmonary plethora with Eisenmenger changes.",
    options: [
      { id: "a", text: "Increased left ventricular compliance", isCorrect: false, explanation: "LV compliance decreases with chronic overload" },
      { id: "b", text: "Pulmonary vascular disease with irreversible pulmonary hypertension (Eisenmenger syndrome)", isCorrect: true, explanation: "Large uncorrected left-to-right shunts (VSD, ASD, PDA) cause chronic pulmonary overcirculation, leading to pulmonary vascular remodeling: intimal thickening, smooth muscle proliferation, and fibrosis. This progressive pulmonary vascular disease increases pulmonary vascular resistance (PVR), eventually exceeding systemic vascular resistance. When PVR > SVR, the shunt reverses from left-to-right to right-to-left, causing cyanosis (Eisenmenger syndrome). This is an irreversible complication requiring urgent heart-lung or lung transplantation, as corrective surgery is no longer possible. Patients with Eisenmenger have poor prognosis without transplant (median survival ~20-40 years)" },
      { id: "c", text: "Infective endocarditis from bacterial seeding", isCorrect: false, explanation: "While endocarditis risk increases, it's not the primary mechanism of cyanosis" },
      { id: "d", text: "Right atrial failure from chronic volume overload", isCorrect: false, explanation: "Right-sided involvement occurs late; pulmonary vascular disease drives Eisenmenger development" },
    ],
    explanation: "Eisenmenger syndrome is the feared complication of large uncorrected left-to-right shunts. Early surgical repair (before age 2-3 years) prevents pulmonary vascular disease development. Once Eisenmenger establishes, surgery is contraindicated due to perioperative mortality from acute right ventricular failure. Management is palliative with pulmonary vasodilators (sildenafil, bosentan) and lung transplantation for eligible candidates.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-05-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 437", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 12-year-old boy presenting with high fever, severe sore throat, and asymmetric tonsillar enlargement with posterior pharyngeal exudate. Which complication can occur without antibiotic treatment?",
    clinicalVignette: "A 12-year-old boy with acute pharyngitis (fever 39.2°C, severe throat pain, dysphagia, asymmetric exudative pharyngitis) is presumed to have strep throat. Rapid strep test is positive. His family cannot afford antibiotics immediately. By day 4, he develops neck swelling, difficulty swallowing saliva, and voice change to 'hot potato voice'. Neck CT shows fluid collection.",
    options: [
      { id: "a", text: "Acute rheumatic fever from untreated GAS pharyngitis", isCorrect: false, explanation: "ARF develops weeks after untreated acute phase, not acutely" },
      { id: "b", text: "Peritonsillar abscess with potential for airway obstruction", isCorrect: true, explanation: "Peritonsillar abscess is a suppurative complication of acute pharyngitis (usually GAS) occurring 4-10 days after onset. The infection spreads from the tonsil to the peritonsillar space, forming a loculated collection of pus. Features: severe, one-sided throat pain, dysphagia, 'hot potato voice' (voice muffling from posterior pharyngeal bulging), trismus (difficulty opening mouth), head tilt away from abscess. Unilateral swelling of soft palate with uvula deviated to contralateral side is characteristic. Complications include airway obstruction, mediastinitis (if rupture occurs), and sepsis. Treatment requires needle aspiration or surgical incision-and-drainage plus IV antibiotics" },
      { id: "c", text: "Post-streptococcal glomerulonephritis from immune complex deposition", isCorrect: false, explanation: "PSGN develops 10-14 days after acute phase, not acutely" },
      { id: "d", text: "Lemierre's syndrome from thrombophlebitis of internal jugular vein", isCorrect: false, explanation: "Lemierre's syndrome can occur but is rarer and typically with more severe sepsis findings" },
    ],
    explanation: "Peritonsillar abscess requires emergency evaluation to assess airway risk. Imaging (ultrasound or CT) confirms the diagnosis and guides intervention. Needle aspiration is therapeutic and diagnostic (allows culture). Definitive surgical drainage may be needed for large abscesses or if needle aspiration fails. IV antibiotics cover Group A Streptococcus and anaerobes. Early recognition and treatment prevent life-threatening airway obstruction.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-06-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 177", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 3-month-old infant with poor feeding, weak cry, and constipation is found to have paralysis of extraocular muscles and dilated pupils. Which anaerobic toxin is responsible?",
    clinicalVignette: "A 3-month-old boy born to a mother with poor prenatal care presents with constipation followed by weakness, poor feeding, weak cry, and ptosis. Examination shows descending paralysis with preserved mental status. He has dilated, unreactive pupils. Serum toxin-blocking antibody test is positive for botulinum toxin.",
    options: [
      { id: "a", text: "Tetanus toxin (tetanospasmin) blocking GABA and glycine release", isCorrect: false, explanation: "Tetanus causes rigidity (opposite of paralysis) and spasms" },
      { id: "b", text: "Botulinum toxin blocking acetylcholine release at the neuromuscular junction", isCorrect: true, explanation: "Infant botulism results from ingestion of Clostridium botulinum spores, which germinate in the intestinal tract and produce botulinum toxin. This toxin blocks acetylcholine release at the neuromuscular junction by cleaving SNARE proteins (preventing acetylcholine vesicle fusion with presynaptic membrane). This causes descending paralysis: starts with extraocular muscles (ptosis, dilated pupils), then facial weakness, bulbar weakness (weak cry, poor feeding), and progressive limb paralysis. Respiratory muscle paralysis can be life-threatening. The key distinguishing feature is paralysis (vs tetanus rigidity), dilated pupils (vs pinpoint in other conditions), and constipation (preceding weakness)" },
      { id: "c", text: "Toxin of Clostridium difficile causing pseudomembranous colitis", isCorrect: false, explanation: "C. difficile toxin causes diarrhea, not paralysis" },
      { id: "d", text: "Shiga toxin from Shigella dysenteriae", isCorrect: false, explanation: "Shiga toxin causes hemolytic uremic syndrome, not paralysis" },
    ],
    explanation: "Infant botulism typically occurs in infants <12 months (peak 2-4 months). Honey is a known source of C. botulinum spores, so honey is contraindicated in infants <12 months. Treatment includes supportive care with mechanical ventilation if needed and botulism immune globulin (BIG-IV), which neutralizes circulating toxin and improves outcomes. Antibiotics are generally avoided (may increase toxin release from dying organisms).",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-06-TOP-02",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 201", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 5-year-old girl with childhood nephrotic syndrome presents with fever and acute abdominal pain. Which infectious complication is she at highest risk for?",
    clinicalVignette: "A 5-year-old girl with minimal change disease (on remission with prednisone taper) develops fever (39.5°C), acute abdominal pain, and abdominal tenderness. Peritoneal fluid obtained by paracentesis shows WBC 1800 (95% neutrophils) with positive gram stain for gram-negative rods. She has not received varicella or pneumococcal vaccine.",
    options: [
      { id: "a", text: "Aseptic meningitis from viral infection", isCorrect: false, explanation: "While viral infections occur, bacterial peritonitis is the characteristic complication" },
      { id: "b", text: "Spontaneous bacterial peritonitis (SBP) from encapsulated organisms", isCorrect: true, explanation: "Nephrotic syndrome increases infection risk due to: (1) Loss of immunoglobulins (especially IgG and complement) in urine, (2) Hypoalbuminemia impairing opsonization and complement function, (3) Edema and malnutrition reducing immune function, (4) Corticosteroid immunosuppression. Spontaneous bacterial peritonitis (SBP) is the most feared infection, occurring in 1-5% of nephrotic children. Organisms: encapsulated bacteria (Streptococcus pneumoniae, Haemophilus influenzae type b, N. meningitidis). Presentation: fever, abdominal pain, ascites (though nephrotic edema differs from SBP ascites). Diagnosis: paracentesis showing elevated WBC (>250 neutrophils) and positive culture" },
      { id: "c", text: "Acute pyelonephritis from Escherichia coli", isCorrect: false, explanation: "While UTI risk increases, SBP is the primary concern" },
      { id: "d", text: "Staphylococcal septicemia from skin source", isCorrect: false, explanation: "While skin infections risk increases, SBP is the classic complication" },
    ],
    explanation: "Prevention of SBP in nephrotic syndrome includes: (1) Pneumococcal vaccination (though response may be suboptimal with heavy proteinuria), (2) Haemophilus influenzae type b vaccination, (3) Prophylactic antibiotics in very high-risk patients (though controversial). Treatment of SBP requires empiric broad-spectrum antibiotics covering encapsulated organisms pending culture. Penicillin allergy should be assessed carefully as beta-lactams are most effective. Immunoglobulin replacement may be considered in severe infections.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-03-TOP-02",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 533", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 6-month-old boy presents with sudden seizure, cyanosis, and loss of consciousness. EEG shows characteristic 3-Hz spike-and-wave discharges. Which seizure type is this?",
    clinicalVignette: "A 6-month-old boy with normal development until now presents with a sudden episode of complete unresponsiveness lasting 10 seconds, during which he stares with eyelid fluttering. No convulsive movements occur. The episode ends abruptly and he returns to normal consciousness. EEG recorded during an attack shows 3-Hz spike-and-wave pattern. Seizures occur multiple times daily.",
    options: [
      { id: "a", text: "Simple focal seizure with preserved consciousness", isCorrect: false, explanation: "Focal seizures have focal EEG changes, not generalized spike-and-wave" },
      { id: "b", text: "Absence seizure (petit mal)", isCorrect: true, explanation: "Absence seizures are generalized non-convulsive seizures characterized by: (1) Sudden brief episodes of unconsciousness (5-10 seconds typically), (2) Staring with behavioral arrest (stops what they're doing), (3) Eyelid fluttering or automatisms (picking at clothes), (4) Abrupt offset with no post-ictal confusion, (5) Frequent occurrence (multiple per day to hundreds per day). EEG shows pathognomonic 3-Hz spike-and-wave pattern (generalized, bilateral, synchronous). Absence seizures are the hallmark of childhood absence epilepsy (CAE), typically onset 4-12 years (though infant absence variants exist). Ethosuximide is the first-line treatment" },
      { id: "c", text: "Atonic seizure with drop attacks", isCorrect: false, explanation: "Atonic seizures involve sudden muscle tone loss with falls, not staring" },
      { id: "d", text: "Myoclonic seizure with brief jerking", isCorrect: false, explanation: "Myoclonic seizures have visible brief muscle jerks" },
    ],
    explanation: "Absence seizures differ from staring spells (which are usually brief behavioral pauses without EEG changes). The 3-Hz spike-and-wave EEG pattern is diagnostic. Ethosuximide is first-line (blocks T-type calcium channels in the thalamus). Valproate and lamotrigine are alternatives. Treatment goals are seizure-free status and prevention of cognitive effects. Untreated or inadequately treated absence seizures can impair school performance and cognition.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-07-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 602", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 2-year-old girl with acute-onset polyuria, polydipsia, and altered mental status is found to have plasma osmolality 340 mOsm/kg and urine osmolality 110 mOsm/kg. Which diagnosis is most likely?",
    clinicalVignette: "A 2-year-old girl with no prior medical history presents acutely with polyuria (wet diapers every 30 minutes), polydipsia (drinks excessively), and lethargy. Serum sodium is 155 mEq/L (elevated), osmolality 340 mOsm/kg, creatinine normal. Urine osmolality is only 110 mOsm/kg (inappropriately low for serum osmolality). Diabetes mellitus is ruled out (glucose 95 mg/dL).",
    options: [
      { id: "a", text: "Type 2 diabetes mellitus", isCorrect: false, explanation: "Glucose is normal, ruling out DM" },
      { id: "b", text: "Central diabetes insipidus from ADH deficiency", isCorrect: true, explanation: "Central diabetes insipidus (CDI) results from deficiency of antidiuretic hormone (ADH/vasopressin) from the hypothalamus or pituitary. Causes in children include: CNS tumors (craniopharyngioma most common), CNS infection (meningitis, encephalitis), head trauma, pituitary surgery, and idiopathic. Presentation: acute or insidious polyuria (can exceed 10 L/day), polydipsia, and hypernatremia if fluid intake is inadequate. Laboratory: high serum osmolality (>300), low urine osmolality (<300), normal plasma glucose. Water deprivation test + desmopressin response confirms CDI (urine osmolality increases with desmopressin in CDI, but not in nephrogenic DI)" },
      { id: "c", text: "Nephrogenic diabetes insipidus from ADH receptor dysfunction", isCorrect: false, explanation: "While NDI presents similarly, desmopressin wouldn't help; treatment differs" },
      { id: "d", text: "Psychogenic polydipsia from excessive water intake", isCorrect: false, explanation: "Psychogenic polydipsia causes low osmolality initially, not high" },
    ],
    explanation: "Treatment of CDI with desmopressin (intranasal spray or tablets) effectively replaces ADH and controls polyuria. Dosing is individualized based on patient response. Patients need education about salt intake (avoid excessive salt which worsens hypernatremia) and free water access (to prevent dehydration with polyuria). Underlying cause must be identified (imaging of pituitary/CNS to rule out tumors).",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-08-TOP-01",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 570", edition: "21st" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 3-month-old infant with failure to thrive, severe metabolic acidosis (pH 7.15), and elevated blood ammonia (250 µmol/L) is found to have elevated methylmalonic acid. Which enzymatic defect is most likely?",
    clinicalVignette: "A 3-month-old boy with poor feeding, vomiting, lethargy, and developmental regression presents in metabolic crisis: pH 7.15, HCO3 8 mEq/L, glucose 45 mg/dL, ammonia 250 µmol/L. Plasma methylmalonic acid is markedly elevated. He has macrocytic anemia (Hb 8.5 g/dL, MCV 108 fL). His parents are consanguineous (from North India).",
    options: [
      { id: "a", text: "Methylmalonyl-CoA mutase deficiency", isCorrect: true, explanation: "Methylmalonic acidemia (MMA) results from methylmalonyl-CoA mutase (MUT) deficiency or cobalamin (vitamin B12) metabolism defects. The enzyme catalyzes methylmalonic acid → succinyl-CoA (a TCA cycle intermediate). Deficiency causes accumulation of methylmalonic acid (excreted in urine, causing characteristic 'ether' odor). Clinical presentation: metabolic acidosis, hyperammonemia (from secondary mitochondrial dysfunction), hypoglycemia, failure to thrive, anemia (from B12 malabsorption in some forms), and neurological sequelae. Acute episodes triggered by illness, infection, or protein intake. Long-term complications include renal failure and neurological deterioration" },
      { id: "b", text: "Propionyl-CoA carboxylase deficiency", isCorrect: false, explanation: "PCC deficiency causes propionic acidemia (elevated propionic acid, not methylmalonic acid)" },
      { id: "c", text: "Isovaleryl-CoA dehydrogenase deficiency", isCorrect: false, explanation: "IVD causes isovaleric acidemia (elevated isovaleric acid)" },
      { id: "d", text: "3-Ketothiolase deficiency", isCorrect: false, explanation: "3-KT deficiency causes 2-methylacetoacetic acidemia" },
    ],
    explanation: "Management of acute methylmalonic acidemia includes: (1) IV fluids with dextrose to reduce catabolism and ammonia, (2) Ammonia scavenging agents (sodium benzoate, sodium phenylbutyrate), (3) Protein restriction, (4) Vitamin B12 supplementation (helpful in Cbl-C, Cbl-D forms; less effective in MUT deficiency), (5) Carnitine supplementation (improves acyl-CoA handling). Long-term management requires strict dietary protein restriction and careful monitoring for renal dysfunction and neurological decline.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1" as const, "NEET_PG" as const],
    subjectCode: "PE",
    topicCode: "PE-MOD-02-TOP-02",
    textbookRefs: [{ book: "Nelson Textbook of Pediatrics", chapter: "Ch 90", edition: "21st" }],
  },
];
