// Physiology MCQs - NEXT pattern (50 questions) - Phase 1
// Distribution: 25% EASY, 40% MEDIUM, 25% HARD, 10% EXPERT
// Pattern: 60% ProblemSolving, 30% Analysis, 10% Recall

export const physiologyFullMcqs = [
  // ============ EASY (12 questions) ============
  // Mostly Recall and some Analysis
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-01-TOP-01",
    stem: "The sodium-potassium pump (Na+/K+-ATPase) exchanges which ions?",
    options: [
      { id: "a", text: "2 Na+ out, 2 K+ in", isCorrect: false, explanation: "The ratio is 3:2" },
      { id: "b", text: "3 Na+ out, 2 K+ in", isCorrect: true, explanation: "Correct 3:2 ratio maintained by the pump" },
      { id: "c", text: "1 Na+ out, 1 K+ in", isCorrect: false, explanation: "The stoichiometry is 3:2" },
      { id: "d", text: "3 Na+ in, 2 K+ out", isCorrect: false, explanation: "Direction is opposite" },
    ],
    explanation: "The **Na+/K+-ATPase pump** extrudes **3 Na+ ions** and imports **2 K+ ions** per ATP molecule hydrolyzed. This creates electrochemical gradients essential for resting membrane potential and cell excitability.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Cell Membrane and Transport", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-01-TOP-02",
    stem: "The resting membrane potential of a typical neuron is approximately:",
    options: [
      { id: "a", text: "-30 mV", isCorrect: false, explanation: "Less negative than typical RMP" },
      { id: "b", text: "-70 mV", isCorrect: true, explanation: "Typical resting membrane potential" },
      { id: "c", text: "-100 mV", isCorrect: false, explanation: "More negative than typical" },
      { id: "d", text: "0 mV", isCorrect: false, explanation: "This is the equilibrium potential" },
    ],
    explanation: "The **resting membrane potential (RMP)** of neurons is approximately **-70 mV**, maintained by the **Na+/K+-ATPase pump** and differential membrane permeability to ions. This negative potential is essential for action potential generation.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Membrane Potentials", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-02-TOP-02",
    stem: "Which hemoglobin variant has the highest oxygen affinity?",
    options: [
      { id: "a", text: "HbA", isCorrect: false, explanation: "HbF has higher affinity" },
      { id: "b", text: "HbF (fetal hemoglobin)", isCorrect: true, explanation: "HbF has higher O2 affinity than HbA" },
      { id: "c", text: "HbS", isCorrect: false, explanation: "HbS has abnormal properties" },
      { id: "d", text: "HbC", isCorrect: false, explanation: "HbC has lower affinity" },
    ],
    explanation: "**Fetal hemoglobin (HbF)** has **higher oxygen affinity** than adult hemoglobin (HbA) because it **does not bind 2,3-BPG** effectively. This allows placental oxygen transfer from maternal to fetal blood.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Red Blood Cell Function", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-03-TOP-01",
    stem: "Which ion channel is responsible for the rapid depolarization phase of cardiac action potential?",
    options: [
      { id: "a", text: "K+ channel", isCorrect: false, explanation: "K+ causes repolarization" },
      { id: "b", text: "Ca2+ channel", isCorrect: false, explanation: "Ca2+ causes plateau phase" },
      { id: "c", text: "Na+ channel", isCorrect: true, explanation: "Fast Na+ influx causes rapid depolarization" },
      { id: "d", text: "Cl- channel", isCorrect: false, explanation: "Cl- hyperpolarizes" },
    ],
    explanation: "The **rapid depolarization phase** (Phase 0) of the cardiac action potential is caused by opening of **fast sodium channels**, allowing rapid **Na+ influx** into the myocyte. This is characteristic of atrial and ventricular myocytes.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Cardiac Electrophysiology", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-03-TOP-02",
    stem: "During the cardiac cycle, which event occurs during the P wave on ECG?",
    options: [
      { id: "a", text: "Ventricular depolarization", isCorrect: false, explanation: "That's QRS" },
      { id: "b", text: "Atrial depolarization", isCorrect: true, explanation: "P wave represents atrial electrical activity" },
      { id: "c", text: "Ventricular repolarization", isCorrect: false, explanation: "That's T wave" },
      { id: "d", text: "Atrial repolarization", isCorrect: false, explanation: "Hidden in QRS" },
    ],
    explanation: "The **P wave** represents **atrial depolarization**. It precedes the QRS complex and marks the beginning of atrial contraction (mechanical response follows).",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Cardiac Electrophysiology", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-04-TOP-02",
    stem: "The total lung capacity (TLC) in an average adult male is approximately:",
    options: [
      { id: "a", text: "3000 mL", isCorrect: false, explanation: "This is closer to vital capacity" },
      { id: "b", text: "6000 mL", isCorrect: true, explanation: "Approximately 6000 mL or 6 L in adult males" },
      { id: "c", text: "8000 mL", isCorrect: false, explanation: "Too high" },
      { id: "d", text: "1500 mL", isCorrect: false, explanation: "Too low" },
    ],
    explanation: "**Total lung capacity (TLC)** in adult males is approximately **6000 mL (6 L)**. It includes tidal volume, inspiratory reserve volume, expiratory reserve volume, and residual volume.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Pulmonary Ventilation", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-05-TOP-01",
    stem: "The glomerular filtration rate (GFR) in normal adults is approximately:",
    options: [
      { id: "a", text: "50 mL/min", isCorrect: false, explanation: "This is lower than normal" },
      { id: "b", text: "100-120 mL/min", isCorrect: true, explanation: "Normal GFR is ~100-120 mL/min" },
      { id: "c", text: "200 mL/min", isCorrect: false, explanation: "Too high" },
      { id: "d", text: "20 mL/min", isCorrect: false, explanation: "Too low" },
    ],
    explanation: "The **glomerular filtration rate (GFR)** in normal adults is approximately **100-120 mL/min** or **60-80 mL/min/1.73 m² BSA**. This reflects the volume of fluid filtered from blood into Bowman's capsule per unit time.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Glomerular Filtration", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-06-TOP-04",
    stem: "Which liver enzyme is released into blood following hepatic injury?",
    options: [
      { id: "a", text: "Aspartate aminotransferase (AST)", isCorrect: true, explanation: "AST is released in hepatic necrosis" },
      { id: "b", text: "Pepsin", isCorrect: false, explanation: "Pepsin is from stomach" },
      { id: "c", text: "Amylase from pancreas", isCorrect: false, explanation: "Pancreatic amylase" },
      { id: "d", text: "Albumin", isCorrect: false, explanation: "Albumin is synthesized, not released" },
    ],
    explanation: "**Aspartate aminotransferase (AST)** and **alanine aminotransferase (ALT)** are released into the blood following **hepatocyte injury** or necrosis. These are key markers of liver damage.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Liver Functions", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-07-TOP-01",
    stem: "Which pituitary hormone stimulates the release of cortisol from the adrenal cortex?",
    options: [
      { id: "a", text: "ACTH (adrenocorticotropic hormone)", isCorrect: true, explanation: "ACTH stimulates cortisol release" },
      { id: "b", text: "TSH (thyroid-stimulating hormone)", isCorrect: false, explanation: "TSH stimulates thyroid" },
      { id: "c", text: "FSH (follicle-stimulating hormone)", isCorrect: false, explanation: "FSH stimulates gamete production" },
      { id: "d", text: "GH (growth hormone)", isCorrect: false, explanation: "GH affects growth and metabolism" },
    ],
    explanation: "**ACTH (adrenocorticotropic hormone)** from the **anterior pituitary** stimulates the release of **cortisol** from the **zona fasciculata** of the adrenal cortex. This is part of the HPA (hypothalamic-pituitary-adrenal) axis.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Adrenal Cortex", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-08-TOP-01",
    stem: "Which protein is responsible for initiating muscle contraction at the neuromuscular junction?",
    options: [
      { id: "a", text: "Acetylcholine (ACh)", isCorrect: true, explanation: "ACh binds to nicotinic receptors on muscle" },
      { id: "b", text: "Myosin", isCorrect: false, explanation: "Myosin is a contractile protein" },
      { id: "c", text: "Tropomyosin", isCorrect: false, explanation: "Tropomyosin blocks myosin-binding sites" },
      { id: "d", text: "Calmodulin", isCorrect: false, explanation: "Calmodulin binds calcium in smooth muscle" },
    ],
    explanation: "**Acetylcholine (ACh)** released from the motor nerve terminal binds to **nicotinic acetylcholine receptors** on the muscle membrane, causing depolarization and initiating the process of muscle contraction.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Neuromuscular Junction", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-01-TOP-04",
    stem: "What is the normal pH range of blood?",
    options: [
      { id: "a", text: "6.8-7.0", isCorrect: false, explanation: "Too acidic" },
      { id: "b", text: "7.35-7.45", isCorrect: true, explanation: "Normal arterial blood pH" },
      { id: "c", text: "7.8-8.0", isCorrect: false, explanation: "Too alkaline" },
      { id: "d", text: "6.5-7.5", isCorrect: false, explanation: "Too wide" },
    ],
    explanation: "The normal **arterial blood pH** is **7.35-7.45**. This narrow range is maintained by buffer systems (bicarbonate, phosphate, hemoglobin) and respiratory-renal mechanisms.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Acid-Base Balance", edition: "13th" }],
  },

  // ============ MEDIUM (20 questions) ============
  // Mostly ProblemSolving and some Analysis
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-01-TOP-03",
    stem: "A patient with hyperkalemia shows characteristic ECG changes. Which is the earliest sign of elevated potassium?",
    clinicalVignette: "A 55-year-old male with chronic kidney disease presents with serum K+ of 6.5 mEq/L. ECG shows characteristic changes.",
    options: [
      { id: "a", text: "Prolonged PR interval", isCorrect: false, explanation: "Occurs later" },
      { id: "b", text: "Peaked T waves", isCorrect: true, explanation: "Earliest ECG sign of hyperkalemia" },
      { id: "c", text: "Widened QRS", isCorrect: false, explanation: "Occurs later as K+ increases" },
      { id: "d", text: "Atrial fibrillation", isCorrect: false, explanation: "Occurs in severe hyperkalemia" },
    ],
    explanation: "The earliest ECG sign of **hyperkalemia** is **peaked (tall, narrow) T waves**. As potassium continues to rise, the PR interval lengthens, QRS widens, and eventually cardiac arrhythmias occur.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Regulation of Extracellular Potassium", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-02-TOP-04",
    stem: "A patient with a bleeding disorder has a prolonged bleeding time. Which platelet function is defective?",
    clinicalVignette: "A 28-year-old female presents with prolonged bleeding time, but normal platelet count and normal prothrombin time. Bleeding time is significantly prolonged.",
    options: [
      { id: "a", text: "Platelet adhesion to von Willebrand factor", isCorrect: true, explanation: "Adhesion defects prolong bleeding time" },
      { id: "b", text: "Coagulation factor synthesis", isCorrect: false, explanation: "Would affect PT, not bleeding time" },
      { id: "c", text: "Fibrinogen conversion", isCorrect: false, explanation: "Would affect PT/PTT" },
      { id: "d", text: "Platelet morphology only", isCorrect: false, explanation: "Doesn't affect bleeding time" },
    ],
    explanation: "**Bleeding time** is a measure of **platelet function** and **von Willebrand factor (vWF)**. Prolonged bleeding time with normal platelet count suggests platelet dysfunction (adhesion defect) or von Willebrand disease.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Hemostasis and Coagulation", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-03-TOP-04",
    stem: "A patient with septic shock develops a decreased cardiac output despite increased heart rate. Which mechanism explains this?",
    clinicalVignette: "A 65-year-old male with sepsis has heart rate of 120/min but cardiac output is markedly reduced. Blood pressure is low despite fluid resuscitation.",
    options: [
      { id: "a", text: "Decreased contractility due to myocardial depression", isCorrect: true, explanation: "Septic shock causes myocardial dysfunction" },
      { id: "b", text: "Increased afterload", isCorrect: false, explanation: "Afterload is typically decreased" },
      { id: "c", text: "Increased preload alone", isCorrect: false, explanation: "Preload increases but contractility is depressed" },
      { id: "d", text: "Increased heart rate is compensatory", isCorrect: false, explanation: "Cannot compensate for depressed contractility" },
    ],
    explanation: "In **septic shock**, **myocardial depression** occurs due to release of inflammatory cytokines and myocardial depressant factors. Despite increased heart rate (compensatory), **cardiac output remains low** because **stroke volume is markedly reduced** from depressed contractility.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Cardiac Output and Shock", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-04-TOP-03",
    stem: "A patient with severe anemia presents with dyspnea at rest. What is the primary mechanism?",
    clinicalVignette: "A 50-year-old female with hemoglobin of 5 g/dL presents with severe dyspnea even at rest. Oxygen saturation is normal (98%).",
    options: [
      { id: "a", text: "Decreased oxygen saturation", isCorrect: false, explanation: "O2 sat is usually normal" },
      { id: "b", text: "Decreased oxygen-carrying capacity of blood", isCorrect: true, explanation: "Low hemoglobin reduces O2 carrying" },
      { id: "c", text: "Pulmonary edema", isCorrect: false, explanation: "Not primary in anemia" },
      { id: "d", text: "Increased airway resistance", isCorrect: false, explanation: "Not related to anemia" },
    ],
    explanation: "In **severe anemia**, **dyspnea** occurs despite **normal oxygen saturation** because **oxygen-carrying capacity** of blood is reduced due to low hemoglobin concentration. The lungs cannot extract more oxygen from each unit of blood.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Anemias", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-05-TOP-04",
    stem: "A patient with severe metabolic acidosis has Kussmaul respirations. What drives this respiratory pattern?",
    clinicalVignette: "A 35-year-old male in diabetic ketoacidosis presents with rapid, deep breathing (Kussmaul respirations). pH is 7.15. Respiratory rate is 28 breaths/min.",
    options: [
      { id: "a", text: "Decreased blood pH stimulates respiratory chemoreceptors", isCorrect: true, explanation: "Acidosis drives hyperventilation" },
      { id: "b", text: "Hypoxemia", isCorrect: false, explanation: "O2 saturation is normal" },
      { id: "c", text: "Increased PCO2", isCorrect: false, explanation: "PCO2 is decreased (from hyperventilation)" },
      { id: "d", text: "Pulmonary edema", isCorrect: false, explanation: "Not present" },
    ],
    explanation: "**Kussmaul respirations** (rapid, deep breathing) occur in **metabolic acidosis** because **decreased blood pH** stimulates **central chemoreceptors** in the medulla, driving compensatory **hyperventilation** to eliminate CO2 and reduce acidosis.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Acid-Base Disorders", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-06-TOP-02",
    stem: "A patient with gastric ulcer disease has achlorhydria (no gastric acid). What is the consequence on iron absorption?",
    clinicalVignette: "A 60-year-old male on long-term PPI therapy develops iron deficiency anemia despite adequate dietary iron intake.",
    options: [
      { id: "a", text: "Iron absorption is increased", isCorrect: false, explanation: "Opposite occurs" },
      { id: "b", text: "Iron absorption is decreased due to lack of gastric acid for iron solubilization", isCorrect: true, explanation: "Acid is needed to dissolve ferric iron" },
      { id: "c", text: "Iron absorption is unchanged", isCorrect: false, explanation: "Significant reduction occurs" },
      { id: "d", text: "Iron is completely malabsorbed", isCorrect: false, explanation: "Some absorption occurs in duodenum" },
    ],
    explanation: "**Gastric acid (HCl)** is essential for solubilizing **ferric iron** and converting it to absorbable **ferrous iron**. In **achlorhydria** (whether from H. pylori, pernicious anemia, or PPI use), iron absorption is significantly reduced, leading to iron deficiency anemia.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Digestion and Absorption", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-07-TOP-02",
    stem: "A patient presents with symptoms of hyperthyroidism: palpitations, tremor, and heat intolerance. Which mechanism explains increased oxygen consumption?",
    clinicalVignette: "A 35-year-old female with Graves' disease has markedly elevated T3 and T4 levels. Metabolic rate is increased by 50%. Oxygen consumption is elevated.",
    options: [
      { id: "a", text: "Decreased mitochondrial ATP production", isCorrect: false, explanation: "Opposite occurs" },
      { id: "b", text: "Thyroid hormones increase mitochondrial uncoupling and metabolic rate", isCorrect: true, explanation: "T3/T4 increase O2 consumption and heat production" },
      { id: "c", text: "Increased sympathetic innervation alone", isCorrect: false, explanation: "Thyroid hormones are the primary driver" },
      { id: "d", text: "Increased body temperature", isCorrect: false, explanation: "Increased metabolic rate causes temperature rise" },
    ],
    explanation: "**Thyroid hormones (T3, T4)** increase **metabolic rate** by increasing **mitochondrial uncoupling** and ATP hydrolysis, leading to increased **oxygen consumption** and **heat production**. This explains the thermogenic and hypermetabolic symptoms of hyperthyroidism.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Thyroid Gland", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-07-TOP-04",
    stem: "A patient with type 1 diabetes is found to have elevated blood glucose despite insulin therapy. What is the primary defect?",
    clinicalVignette: "A 20-year-old male with type 1 diabetes on insulin therapy has persistently elevated fasting glucose (200 mg/dL) and elevated HbA1c.",
    options: [
      { id: "a", text: "Loss of pancreatic beta-cell function", isCorrect: true, explanation: "Type 1 DM involves autoimmune destruction of beta cells" },
      { id: "b", text: "Insulin resistance alone", isCorrect: false, explanation: "Type 1 is autoimmune, not resistance" },
      { id: "c", text: "Impaired glucose sensing", isCorrect: false, explanation: "Primary issue is beta-cell loss" },
      { id: "d", text: "Increased insulin-like growth factor", isCorrect: false, explanation: "Not relevant" },
    ],
    explanation: "**Type 1 diabetes mellitus** is characterized by **autoimmune destruction of pancreatic beta cells**, leading to **absolute insulin deficiency**. Patients require insulin replacement therapy. The primary defect is loss of beta-cell function, not insulin resistance.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Pancreatic Hormones", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-08-TOP-02",
    stem: "A patient with myasthenia gravis has decreased muscle strength that worsens with activity. What is the pathophysiology?",
    clinicalVignette: "A 30-year-old female presents with ptosis and diplopia that worsens throughout the day. Muscle strength improves temporarily with edrophonium injection.",
    options: [
      { id: "a", text: "Autoimmune destruction of the motor neuron", isCorrect: false, explanation: "Neurons are intact" },
      { id: "b", text: "Autoimmune attack on acetylcholine receptors at NMJ", isCorrect: true, explanation: "Antibodies block ACh receptors" },
      { id: "c", text: "Deficient acetylcholine synthesis", isCorrect: false, explanation: "ACh production is normal" },
      { id: "d", text: "Myofibril degeneration", isCorrect: false, explanation: "Muscles are structurally normal" },
    ],
    explanation: "**Myasthenia gravis** is an **autoimmune disorder** where **antibodies** attack **acetylcholine receptors (AChR)** at the **neuromuscular junction**. This leads to **decreased muscle strength** that worsens with activity (due to receptor depletion). Edrophonium (acetylcholinesterase inhibitor) temporarily improves strength by increasing ACh availability.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Neuromuscular Junction Disorders", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-08-TOP-05",
    stem: "A patient with myopia (nearsightedness) has difficulty seeing distant objects. What is the refractive error?",
    clinicalVignette: "A 25-year-old college student cannot read the board in class but has clear near vision. Refractive error is confirmed with glasses prescription.",
    options: [
      { id: "a", text: "Excessive corneal curvature or axial elongation", isCorrect: true, explanation: "Myopia = convergence error" },
      { id: "b", text: "Insufficient corneal curvature", isCorrect: false, explanation: "This causes hyperopia" },
      { id: "c", text: "Loss of lens elasticity", isCorrect: false, explanation: "This causes presbyopia" },
      { id: "d", text: "Retinal detachment", isCorrect: false, explanation: "This is a different pathology" },
    ],
    explanation: "**Myopia (nearsightedness)** results from **excessive corneal curvature** or **axial elongation** of the eye, causing parallel light rays to focus anterior to the retina. Correction requires **diverging (minus) lenses** to move the focal point posteriorly onto the retina.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Vision and Visual Acuity", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-01-TOP-05",
    stem: "A patient on long-term glucocorticoid therapy develops osteoporosis. What is the primary mechanism of bone loss?",
    clinicalVignette: "A 60-year-old female on chronic prednisone for rheumatoid arthritis develops severe osteoporosis with multiple vertebral fractures.",
    options: [
      { id: "a", text: "Increased osteoclast activity directly", isCorrect: true, explanation: "Glucocorticoids increase bone resorption" },
      { id: "b", text: "Decreased vitamin D activation", isCorrect: false, explanation: "Related but not primary" },
      { id: "c", text: "Increased intestinal calcium absorption", isCorrect: false, explanation: "Calcium absorption is decreased" },
      { id: "d", text: "Increased parathyroid hormone", isCorrect: false, explanation: "Secondary to decreased calcium" },
    ],
    explanation: "**Glucocorticoids** cause **bone loss** through multiple mechanisms: **increased osteoclast recruitment**, **decreased osteoblast function**, **decreased calcium absorption**, and **increased renal calcium loss**. This leads to rapid bone loss, particularly in the spine.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Bone Metabolism", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-02-TOP-01",
    stem: "A patient with blood loss develops compensatory tachycardia. What is the mechanism behind this heart rate increase?",
    clinicalVignette: "A 40-year-old male with hemorrhage (1 liter blood loss) develops heart rate of 120/min. Blood pressure is maintained at 100/60 mmHg.",
    options: [
      { id: "a", text: "Direct myocardial stimulation by norepinephrine", isCorrect: true, explanation: "SNS activation increases heart rate" },
      { id: "b", text: "Decreased parasympathetic tone alone", isCorrect: false, explanation: "SNS activation is primary" },
      { id: "c", text: "Decreased blood viscosity", isCorrect: false, explanation: "Mechanical factor, not primary driver" },
      { id: "d", text: "Increased circulating potassium", isCorrect: false, explanation: "Not relevant to tachycardia" },
    ],
    explanation: "In **hemorrhage**, **decreased blood pressure** triggers **sympathetic nervous system activation** (via baroreceptor reflex), leading to **increased heart rate** and **increased contractility**. This maintains **cardiac output (CO = HR × SV)** despite reduced blood volume.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Regulation of Cardiac Output", edition: "13th" }],
  },

  // ============ HARD (12 questions) ============
  // Mostly ProblemSolving and Analysis
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-03-TOP-05",
    stem: "A patient with hypertension has elevated blood pressure despite multiple antihypertensive medications. Which autoregulatory mechanism is impaired?",
    clinicalVignette: "A 65-year-old male with long-standing hypertension develops end-organ damage (left ventricular hypertrophy, proteinuria). Despite intensive therapy, BP remains elevated.",
    options: [
      { id: "a", text: "Myogenic autoregulation is shifted to higher pressures", isCorrect: true, explanation: "Chronic HTN resets autoregulation" },
      { id: "b", text: "Complete loss of autoregulation", isCorrect: false, explanation: "Partial impairment, not complete loss" },
      { id: "c", text: "Increased parasympathetic tone", isCorrect: false, explanation: "Not the primary mechanism" },
      { id: "d", text: "Decreased renal perfusion pressure", isCorrect: false, explanation: "This is a consequence, not mechanism" },
    ],
    explanation: "In **chronic hypertension**, **myogenic autoregulation** (the ability to maintain constant organ perfusion across changing pressures) is **shifted to higher pressure levels**. The kidney becomes "hypertensive" and requires higher pressures to maintain filtration, perpetuating the hypertension.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Blood Pressure Regulation", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-04-TOP-04",
    stem: "A patient with severe COPD has chronic hypoxemia and hypercapnia. Which respiratory center adaptation is responsible for hypercapnic drive becoming the primary stimulus?",
    clinicalVignette: "A 70-year-old male with COPD has baseline PCO2 of 65 mmHg. When given high-flow oxygen, his respiratory drive decreases and he becomes drowsy.",
    options: [
      { id: "a", text: "Central chemoreceptors become insensitive to pH changes", isCorrect: true, explanation: "Central chemoreceptors adapt in chronic hypercapnia" },
      { id: "b", text: "Loss of peripheral chemoreceptor function", isCorrect: false, explanation: "Peripheral chemoreceptors remain intact" },
      { id: "c", text: "Increased tolerance to elevated PCO2", isCorrect: false, explanation: "Adaptation of central receptors" },
      { id: "d", text: "Complete respiratory depression", isCorrect: false, explanation: "Selective adaptation occurs" },
    ],
    explanation: "In **chronic COPD with hypercapnia**, **central chemoreceptors** become **adapted (desensitized) to elevated CO2/low pH**. As a result, **hypoxemia** (sensed by peripheral chemoreceptors) becomes the primary respiratory drive. Supplemental oxygen removes this drive, causing respiratory depression.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Regulation of Respiration", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-05-TOP-03",
    stem: "A patient with syndrome of inappropriate ADH (SIADH) develops severe hyponatremia. What is the renal mechanism?",
    clinicalVignette: "A 55-year-old female with small-cell lung cancer develops hyponatremia (Na+ 120 mEq/L). Urine osmolality is 400 mOsm/kg despite low plasma osmolality.",
    options: [
      { id: "a", text: "Inability to dilute urine due to excessive ADH", isCorrect: true, explanation: "SIADH prevents urine dilution" },
      { id: "b", text: "Primary renal salt wasting", isCorrect: false, explanation: "Secondary to SIADH" },
      { id: "c", text: "Decreased glomerular filtration", isCorrect: false, explanation: "GFR is typically normal" },
      { id: "d", text: "Increased aldosterone activity", isCorrect: false, explanation: "Not the primary mechanism" },
    ],
    explanation: "In **SIADH**, **excessive ADH (vasopressin)** causes the kidneys to **conserve water** by increasing aquaporin-2 channels in the collecting duct. This results in **hypotonic urine reabsorption** despite **low plasma osmolality**, leading to **hyponatremia** and **volume expansion** (euvolemic hyponatremia).",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Urine Concentration and Dilution", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-06-TOP-03",
    stem: "A patient with protein-energy malnutrition has decreased protein absorption. Which enzyme deficiency is responsible?",
    clinicalVignette: "A 50-year-old male with severe malnutrition has low serum albumin and edema. Protein intake is adequate but not being absorbed.",
    options: [
      { id: "a", text: "Pancreatic protease deficiency (trypsin, chymotrypsin)", isCorrect: true, explanation: "Proteases are essential for protein digestion" },
      { id: "b", text: "Gastric pepsin deficiency", isCorrect: false, explanation: "Pepsin is from stomach" },
      { id: "c", text: "Increased intestinal protease activity", isCorrect: false, explanation: "Activity is decreased" },
      { id: "d", text: "Loss of brush border disaccharidases", isCorrect: false, explanation: "These are for carbohydrate, not protein" },
    ],
    explanation: "**Protein digestion** requires **pancreatic proteases** (trypsin, chymotrypsin, carboxypeptidases) and **intestinal proteases** (peptidases). **Pancreatic insufficiency** or **malabsorption** leads to decreased protein absorption, contributing to hypoproteinemia and edema in severe malnutrition.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Digestion and Absorption", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-07-TOP-03",
    stem: "A patient with Cushing's syndrome develops muscle weakness. What is the primary mechanism?",
    clinicalVignette: "A 45-year-old female with adrenocorticoid-secreting pituitary adenoma develops proximal muscle weakness. Serum cortisol is elevated 10-fold.",
    options: [
      { id: "a", text: "Direct glucocorticoid-induced myopathy from protein catabolism", isCorrect: true, explanation: "Cortisol causes muscle protein breakdown" },
      { id: "b", text: "Hypokalemia from aldosterone excess", isCorrect: false, explanation: "Contributes but not primary" },
      { id: "c", text: "Myositis from immune dysfunction", isCorrect: false, explanation: "Not the primary mechanism" },
      { id: "d", text: "Rhabdomyolysis", isCorrect: false, explanation: "Severe but not typical" },
    ],
    explanation: "**Cushing's syndrome** (excess cortisol) causes **proximal muscle weakness** through **glucocorticoid-induced protein catabolism** and **decreased protein synthesis** in muscles. This leads to **muscle atrophy**, particularly of hip and shoulder muscles.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Adrenal Cortex", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-08-TOP-03",
    stem: "A patient with diabetic neuropathy has impaired pain sensation but preserved vibration sense. What is the anatomical basis?",
    clinicalVignette: "A 60-year-old male with type 2 diabetes develops loss of sharp pain sensation in a stocking-glove distribution but can still feel vibration.",
    options: [
      { id: "a", text: "Selective loss of small myelinated and unmyelinated fibers (pain/temperature)", isCorrect: true, explanation: "Diabetic neuropathy affects small fibers first" },
      { id: "b", text: "Loss of large myelinated fibers (vibration/proprioception)", isCorrect: false, explanation: "Vibration is preserved" },
      { id: "c", text: "Dorsal column degeneration", isCorrect: false, explanation: "Would affect vibration" },
      { id: "d", text: "Anterior horn cell degeneration", isCorrect: false, explanation: "Would cause motor weakness" },
    ],
    explanation: "**Diabetic neuropathy** typically causes **loss of small nerve fiber function** first (Aδ and C fibers for pain and temperature sensation), while **large myelinated fibers** (Aβ fibers for vibration and proprioception) are preserved. This creates a **dissociated sensory loss pattern**.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Sensory System", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-02-TOP-05",
    stem: "A patient with acute hemolytic transfusion reaction receives incompatible blood. Which cascade is activated?",
    clinicalVignette: "A 45-year-old male receives ABO-incompatible transfusion by mistake. Within minutes, he develops fever, chest pain, and hemoglobinuria.",
    options: [
      { id: "a", text: "Complement cascade (direct lysis of RBCs)", isCorrect: true, explanation: "IgM antibodies activate complement" },
      { id: "b", text: "Coagulation cascade alone", isCorrect: false, explanation: "Both complement and coagulation are activated" },
      { id: "c", text: "Fibrinolytic cascade alone", isCorrect: false, explanation: "Complement is primary" },
      { id: "d", text: "Kallikrein-kinin cascade", isCorrect: false, explanation: "Not the primary cascade" },
    ],
    explanation: "**ABO-incompatible blood transfusion** causes **immediate hemolytic transfusion reaction** through **IgM antibody activation of the complement cascade**. This leads to **complement-mediated RBC lysis**, **release of hemoglobin**, **hemoglobinuria**, **DIC**, and potential **acute kidney injury**.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Blood Groups and Transfusion", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-03-TOP-06",
    stem: "A patient with coronary artery occlusion develops myocardial infarction. Which region of the left ventricle is typically affected with left anterior descending (LAD) artery occlusion?",
    clinicalVignette: "A 60-year-old male presents with acute anterior ST-elevation MI. Electrocardiography shows ST elevation in leads I, aVL, and V1-V4.",
    options: [
      { id: "a", text: "Anterior and anteroseptal wall", isCorrect: true, explanation: "LAD supplies anterior and anteroseptal regions" },
      { id: "b", text: "Inferior wall", isCorrect: false, explanation: "RCA supplies inferior wall" },
      { id: "c", text: "Posterior wall", isCorrect: false, explanation: "LCx supplies lateral and posterior" },
      { id: "d", text: "Right ventricular wall", isCorrect: false, explanation: "May be involved but not typical" },
    ],
    explanation: "The **left anterior descending (LAD) artery** supplies the **anterior wall, anteroseptal region, and anterior two-thirds of the interventricular septum**. LAD occlusion causes **anterior/anteroseptal MI**, seen as ST elevation in precordial leads (V1-V4).",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Coronary Circulation", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-01-TOP-02",
    stem: "A patient with chronic renal disease develops metabolic acidosis with normal anion gap. Which mechanism explains this hyperchloremic acidosis?",
    clinicalVignette: "A 65-year-old male with stage 4 CKD has pH 7.30, HCO3- 18 mEq/L, and Cl- 108 mEq/L (anion gap normal).",
    options: [
      { id: "a", text: "Loss of bicarbonate in urine due to reduced GFR", isCorrect: false, explanation: "GFR reduction causes retention, not loss" },
      { id: "b", text: "Decreased ammonia excretion preventing acid loss in urine", isCorrect: true, explanation: "Impaired NH3 excretion reduces acid secretion" },
      { id: "c", text: "Increased chloride reabsorption alone", isCorrect: false, explanation: "Contributing but not primary" },
      { id: "d", text: "Metabolic generation of organic acids", isCorrect: false, explanation: "Would cause high anion gap" },
    ],
    explanation: "In **chronic renal disease**, **normal anion gap (hyperchloremic) metabolic acidosis** develops because the kidneys lose the ability to excrete **ammonia (NH3)** and titratable acid. This leads to **reduced acid secretion** despite **bicarbonate reabsorption** being relatively preserved.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Acid-Base Disorders", edition: "13th" }],
  },

  // ============ EXPERT (5 questions) ============
  // Complex Analysis and ProblemSolving
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-04-TOP-05",
    stem: "A patient with severe pneumonia develops hypoxemia refractory to supplemental oxygen. What is the primary pathophysiological mechanism (A-a gradient is high)?",
    clinicalVignette: "A 70-year-old male with pneumonia has FiO2 of 80% but remains hypoxemic (PaO2 60 mmHg). Calculated alveolar PO2 is normal.",
    options: [
      { id: "a", text: "Hypoventilation", isCorrect: false, explanation: "Would cause elevated PCO2" },
      { id: "b", text: "Right-to-left shunt (intrapulmonary shunting)", isCorrect: true, explanation: "Consolidation creates shunt physiology" },
      { id: "c", text: "Diffusion impairment alone", isCorrect: false, explanation: "Shunt is more likely" },
      { id: "d", text: "Low inspired oxygen pressure", isCorrect: false, explanation: "FiO2 is high" },
    ],
    explanation: "In **pneumonia**, **increased intrapulmonary shunting** (blood bypassing ventilated alveoli through consolidated lung) creates **refractory hypoxemia** despite high FiO2. A high **alveolar-arterial (A-a) gradient** indicates **V/Q mismatch or shunt**, not simply hypoventilation.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Gas Exchange and Transport", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-05-TOP-02",
    stem: "A patient with primary hyperaldosteronism develops hypertension with low-normal serum potassium. What maintains potassium homeostasis despite increased renal loss?",
    clinicalVignette: "A 50-year-old female with adrenal adenoma producing aldosterone has BP 160/95 mmHg, K+ 3.3 mEq/L (low-normal). Expected K+ should be <2.5 without compensation.",
    options: [
      { id: "a", text: "Increased proximal tubular K+ reabsorption", isCorrect: false, explanation: "Proximal cannot compensate fully" },
      { id: "b", text: "Volume expansion leads to pressure natriuresis, limiting further K+ loss", isCorrect: true, explanation: "Aldosterone escape phenomenon" },
      { id: "c", text: "Increased GFR from hypertension", isCorrect: false, explanation: "Would increase loss" },
      { id: "d", text: "Decreased ADH inhibiting K+ secretion", isCorrect: false, explanation: "Not the mechanism" },
    ],
    explanation: "In **primary hyperaldosteronism**, the **aldosterone escape phenomenon** limits progressive hypokalemia. **Volume expansion** from initial Na+ reabsorption leads to **atrial natriuretic peptide release**, **increased renal perfusion pressure**, and **pressure natriuresis** that counteracts continued aldosterone action, preventing severe hypokalemia.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Regulation of Blood Pressure", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-06-TOP-04",
    stem: "A patient with cirrhosis develops ascites despite normal plasma albumin levels. Which hemodynamic factor is responsible?",
    clinicalVignette: "A 55-year-old male with cirrhosis has ascites, but serum albumin is 3.5 g/dL (normal). Portal pressure is markedly elevated (25 mmHg).",
    options: [
      { id: "a", text: "Low plasma albumin (hypoproteinemia)", isCorrect: false, explanation: "Albumin is normal" },
      { id: "b", text: "Elevated portal venous pressure causing increased capillary hydrostatic pressure", isCorrect: true, explanation: "Portal HTN drives fluid transudation" },
      { id: "c", text: "Decreased lymphatic drainage alone", isCorrect: false, explanation: "Related but elevated hydrostatic pressure is primary" },
      { id: "d", text: "Increased vascular permeability", isCorrect: false, explanation: "No inflammation in uncomplicated ascites" },
    ],
    explanation: "In **cirrhotic ascites**, **elevated portal venous pressure** (from hepatic fibrosis/cirrhosis) increases **capillary hydrostatic pressure** in splanchnic vessels, forcing fluid transudation into the peritoneal cavity. This occurs despite **normal plasma albumin** and **normal colloid osmotic pressure**, indicating a **hemodynamic (hydrostatic pressure) mechanism**.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Liver Functions", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-07-TOP-07",
    stem: "A pregnant patient with preeclampsia has hypertension and proteinuria. What is the primary placental dysfunction?",
    clinicalVignette: "A 28-year-old primigravida at 32 weeks develops BP 160/105 mmHg, proteinuria 3+ and symptoms of preeclampsia. Placental pathology shows inadequate trophoblast invasion.",
    options: [
      { id: "a", text: "Inadequate remodeling of spiral arteries due to defective trophoblast invasion", isCorrect: true, explanation: "Trophoblast invasion failure causes placental ischemia" },
      { id: "b", text: "Excessive placental growth factor", isCorrect: false, explanation: "PlGF is reduced in preeclampsia" },
      { id: "c", text: "Normal placental development with systemic maternal disease", isCorrect: false, explanation: "Placental pathology is documented" },
      { id: "d", text: "Fetal chromosome abnormality", isCorrect: false, explanation: "Not causative" },
    ],
    explanation: "**Preeclampsia** is characterized by **inadequate trophoblastic invasion** of spiral arteries, leading to **placental ischemia**, **abnormal angiogenic factor balance** (↓PlGF, ↑sFlt-1), and **systemic endothelial dysfunction** manifesting as **hypertension, proteinuria, and multi-organ dysfunction**.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Maternal Physiology in Pregnancy", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "PY-MOD-08-TOP-07",
    stem: "A patient with dementia develops sleep disturbance with loss of normal sleep architecture. Which brain region dysfunction is responsible?",
    clinicalVignette: "A 75-year-old male with Alzheimer's disease has severely fragmented sleep with loss of REM sleep and slow-wave sleep. Polysomnography shows disorganized sleep architecture.",
    options: [
      { id: "a", text: "Degeneration of cholinergic neurons in basal forebrain (loss of REM sleep regulation)", isCorrect: true, explanation: "Cholinergic neurons regulate REM sleep" },
      { id: "b", text: "Loss of wake-promoting anterior hypothalamus neurons alone", isCorrect: false, explanation: "Contributing but not complete explanation" },
      { id: "c", text: "Increased melatonin production", isCorrect: false, explanation: "Usually decreased" },
      { id: "d", text: "Preserved sleep-wake architecture with behavioral disruption", isCorrect: false, explanation: "Architecture is genuinely disrupted" },
    ],
    explanation: "In **Alzheimer's disease**, **degeneration of cholinergic neurons** in the **basal forebrain** (particularly those projecting to cortex) leads to loss of **REM sleep regulation** and **slow-wave sleep**. Additionally, loss of **suprachiasmatic nucleus (SCN)** neurons impairs circadian rhythm, causing **severe sleep fragmentation and disorganized sleep architecture**.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Guyton and Hall", chapter: "Sleep and Wakefulness", edition: "13th" }],
  },
];
