// Pathology MCQs - Advanced topics with NEXT pattern
// 30 MCQs covering: cell injury, inflammation, neoplasia, genetic, hematology, immunopathology, systemic

export const pathologyMcqs2 = [
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 45-year-old diabetic patient presents with progressive left upper limb weakness and sensory loss in a stocking-glove distribution. Histology shows demyelination and axonal loss. Which of the following mechanisms is primarily responsible?",
    clinicalVignette: "A 45-year-old male with 20-year history of Type 2 diabetes presents with progressive left hand weakness and loss of fine motor control. Nerve biopsy shows segmental demyelination with onion-skin appearance of Schwann cells.",
    options: [
      { id: "a", text: "Non-enzymatic glycosylation of myelin proteins", isCorrect: true, explanation: "Advanced glycation end products (AGEs) cross-link myelin proteins, leading to structural damage and demyelination in diabetic neuropathy" },
      { id: "b", text: "Autoimmune destruction of myelin", isCorrect: false, explanation: "While present in MS, autoimmunity is not the primary mechanism in diabetic neuropathy" },
      { id: "c", text: "Viral infection of Schwann cells", isCorrect: false, explanation: "Not relevant to diabetic neuropathy pathogenesis" },
      { id: "d", text: "Toxic damage from insulin injections", isCorrect: false, explanation: "Insulin itself is not neurotoxic; hyperglycemia is the culprit" },
    ],
    explanation: "**Diabetic neuropathy** involves non-enzymatic glycosylation causing myelin degeneration. AGEs accumulate in basement membrane, reducing nerve blood flow and promoting demyelination.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-08-TOP-12",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Peripheral Nervous System - Ch 27", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 62-year-old smoker presents with hemoptysis. Chest X-ray shows a 4 cm cavitary lesion in the right upper lobe. Biopsy shows keratinizing squamous cell carcinoma with central necrosis. Which mutation is most likely driving this malignancy?",
    clinicalVignette: "A 62-year-old heavy smoker (50 pack-years) presents with a 2-month history of hemoptysis. CT chest reveals a cavitary lesion in the RUL with hilar lymphadenopathy.",
    options: [
      { id: "a", text: "TP53 mutation (>70% of cases)", isCorrect: true, explanation: "P53 inactivation is the most common genetic alteration in squamous cell lung cancer, especially in smokers" },
      { id: "b", text: "EGFR mutation", isCorrect: false, explanation: "EGFR mutations are more common in adenocarcinoma and non-smokers" },
      { id: "c", text: "ALK translocation", isCorrect: false, explanation: "ALK is associated with adenocarcinoma morphology" },
      { id: "d", text: "KRAS mutation alone", isCorrect: false, explanation: "While KRAS is involved, TP53 co-mutations are more prevalent" },
    ],
    explanation: "**Squamous cell lung cancer** in smokers typically has **TP53 mutations** (>70%) causing loss of cell cycle control and apoptosis. This is more common than EGFR mutations.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-10-TOP-08",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Lung Neoplasms - Ch 15", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 3-year-old child with cystic fibrosis develops recurrent respiratory infections. Which epithelial dysfunction best explains the predisposition?",
    clinicalVignette: "A 3-year-old boy with confirmed cystic fibrosis (CFTR F508del/F508del) presents with chronic cough and recurrent Pseudomonas aeruginosa infections.",
    options: [
      { id: "a", text: "Loss of CFTR chloride channel function leading to dehydrated mucus", isCorrect: true, explanation: "CFTR mutation causes defective Cl- secretion, reducing mucociliary clearance and promoting bacterial colonization" },
      { id: "b", text: "Primary immunodeficiency affecting neutrophils", isCorrect: false, explanation: "CF patients have normal immune function; the problem is mechanical clearance" },
      { id: "c", text: "Epithelial necrosis from chronic inflammation", isCorrect: false, explanation: "This is a consequence, not the primary cause of infection predisposition" },
      { id: "d", text: "Abnormal surfactant composition", isCorrect: false, explanation: "Surfactant is not the primary issue in CF pathogenesis" },
    ],
    explanation: "**Cystic fibrosis** results from CFTR dysfunction → impaired Cl- secretion → thick, dehydrated secretions → impaired mucociliary clearance → recurrent bacterial infections.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-04-TOP-03",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Genetic Disorders - Ch 5", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old woman presents with recurrent thrombosis and fetal loss. Anticardiolipin antibodies are detected. Which mechanism increases thrombotic risk?",
    clinicalVignette: "A 28-year-old nulligravida presents with recurrent DVT in the left leg and three consecutive miscarriages at 16-18 weeks. Lupus anticoagulant and anticardiolipin IgG are positive.",
    options: [
      { id: "a", text: "Direct platelet activation and tissue factor upregulation", isCorrect: true, explanation: "Anticardiolipin antibodies bind β2-glycoprotein I, activating platelets and upregulating tissue factor, promoting thrombosis" },
      { id: "b", text: "Primary hypercoagulability from increased prothrombin", isCorrect: false, explanation: "Antiphospholipid syndrome is not due to increased prothrombin levels" },
      { id: "c", text: "Deficiency of natural anticoagulants", isCorrect: false, explanation: "Protein C and S levels are typically normal in APS" },
      { id: "d", text: "Endothelial apoptosis from complement activation", isCorrect: false, explanation: "While complement is involved, platelet activation is the primary mechanism" },
    ],
    explanation: "**Antiphospholipid syndrome (APS)**: Anticardiolipin and lupus anticoagulant antibodies bind β2-glycoprotein I → platelet activation → tissue factor upregulation → thrombosis.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-09-TOP-05",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Hemostasis & Thrombosis - Ch 4", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 72-year-old man with chronic COPD presents with cor pulmonale. Histologically, the right ventricle shows eccentric hypertrophy. What is the pathophysiologic mechanism?",
    clinicalVignette: "A 72-year-old with 50 pack-year smoking history and GOLD Stage 4 COPD presents with dyspnea, peripheral edema, and elevated JVP. Echo shows RV dilation with preserved EF initially.",
    options: [
      { id: "a", text: "Sustained pulmonary hypertension from hypoxic vasoconstriction", isCorrect: true, explanation: "Chronic hypoxemia in COPD causes pulmonary vasoconstriction → RV pressure overload → eccentric hypertrophy and eventual dilation" },
      { id: "b", text: "Left ventricular dysfunction from left coronary steal", isCorrect: false, explanation: "Cor pulmonale is primarily RV disease; LV involvement is secondary" },
      { id: "c", text: "Myocardial infarction from atherosclerosis", isCorrect: false, explanation: "While MI can occur, it's not the primary mechanism of cor pulmonale" },
      { id: "d", text: "Viral myocarditis with RV tropism", isCorrect: false, explanation: "Myocarditis is not the primary cause of COPD-related cor pulmonale" },
    ],
    explanation: "**Cor pulmonale** from COPD: Chronic hypoxemia → sustained pulmonary vasoconstriction → RV pressure overload → eccentric hypertrophy → RV dilation and failure.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-07-TOP-02",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Heart - Ch 11", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 55-year-old with alcoholic cirrhosis develops spontaneous bacterial peritonitis (SBP). Which pathophysiologic factor most contributes to SBP risk?",
    clinicalVignette: "A 55-year-old with decompensated cirrhosis (Child-Pugh C) presents with fever and ascites. Ascitic tap shows protein 1.2 g/dL, PMN 250 cells/mm³, and positive cultures for E. coli.",
    options: [
      { id: "a", text: "Impaired complement and opsonin activity in low-protein ascites", isCorrect: true, explanation: "Low ascitic protein (<1.5 g/dL) means reduced opsonic activity and complement components → impaired bacterial killing → SBP risk" },
      { id: "b", text: "Direct bacterial translocation from bowel wall necrosis", isCorrect: false, explanation: "While translocation occurs, the main issue is inability to clear bacteria from ascites" },
      { id: "c", text: "Portal vein thrombosis obstructing antibody delivery", isCorrect: false, explanation: "Antibody delivery is not the limiting factor in SBP" },
      { id: "d", text: "Hepatic encephalopathy impairing neutrophil function", isCorrect: false, explanation: "Encephalopathy is a consequence, not the primary risk factor for SBP" },
    ],
    explanation: "**SBP risk factors**: Low ascitic protein (<1.5 g/dL) → impaired opsonin and complement activity → reduced bacterial clearance → spontaneous peritonitis.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-06-TOP-04",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Liver & Biliary System - Ch 18", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 68-year-old woman presents with progressive cognitive decline and gait disturbance. Brain biopsy shows spongiform changes with PrP deposition. Which protein is misfolded?",
    clinicalVignette: "A 68-year-old woman with rapidly progressive dementia (3-month duration), myoclonus, and gait ataxia. EEG shows periodic sharp wave complexes. MRI shows cortical atrophy and basal ganglia changes.",
    options: [
      { id: "a", text: "Prion protein (PrP) with abnormal β-pleated sheet conformation", isCorrect: true, explanation: "Creutzfeldt-Jakob disease (CJD) involves PrPsc (misfolded prion) → neurodegeneration → spongiform encephalopathy" },
      { id: "b", text: "Amyloid-β with α-helix accumulation", isCorrect: false, explanation: "Amyloid-β is β-sheet (not α-helix) and found in Alzheimer disease" },
      { id: "c", text: "Tau protein with hyperphosphorylation", isCorrect: false, explanation: "Tau is prominent in Alzheimer disease, not prion diseases" },
      { id: "d", text: "Synuclein with loss of N-terminal domain", isCorrect: false, explanation: "Synuclein aggregates are seen in Parkinson disease, not CJD" },
    ],
    explanation: "**Prion diseases (CJD)**: PrPsc (misfolded, infectious) → converts normal PrPc to abnormal form → neurodegeneration → spongiform changes with characteristic histology.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-08-TOP-06",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "CNS - Ch 28", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old woman with systemic lupus erythematosus develops kidney dysfunction with nephrotic syndrome. Kidney biopsy shows 'wire-loop' lesions. Which immune mechanism predominates?",
    clinicalVignette: "A 35-year-old female with confirmed SLE (4+ criteria) presents with nephrotic syndrome. Urinalysis shows 4+ proteinuria, RBC casts. Serum complement C3 and C4 are low.",
    options: [
      { id: "a", text: "Immune complex (Type III) deposition with complement activation", isCorrect: true, explanation: "Anti-dsDNA antibodies form immune complexes → deposition in GBM → complement activation → glomerulonephritis with 'wire-loop' appearance" },
      { id: "b", text: "Cytotoxic (Type II) antibody against GBM", isCorrect: false, explanation: "Type II is seen in Goodpasture syndrome, not SLE nephritis" },
      { id: "c", text: "Type I hypersensitivity with mast cell degranulation", isCorrect: false, explanation: "Type I is IgE-mediated, not relevant to lupus nephritis" },
      { id: "d", text: "Delayed-type hypersensitivity from T cell infiltration", isCorrect: false, explanation: "While T cells are involved, immune complexes are the primary pathology" },
    ],
    explanation: "**SLE nephritis**: Anti-dsDNA antibodies → immune complex formation → glomerular deposition → complement activation → 'wire-loop' lesions (subendothelial deposits).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-09-TOP-03",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Kidney - Ch 20", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 52-year-old patient with long-standing gastroesophageal reflux develops Barrett's esophagus. Which molecular change represents the first step in this metaplasia?",
    clinicalVignette: "A 52-year-old male with 15-year history of GERD presents with dysphagia. Upper endoscopy reveals salmon-pink mucosa proximal to the gastroesophageal junction.",
    options: [
      { id: "a", text: "Acid-induced chronic inflammation → loss of tight junctions → epithelial regeneration", isCorrect: true, explanation: "Chronic reflux → epithelial injury → repair → intestinal metaplasia (Barrett's) as part of tissue adaptation" },
      { id: "b", text: "Immediate malignant transformation to adenocarcinoma", isCorrect: false, explanation: "Barrett's is a precancerous lesion with ~0.3% annual progression to cancer" },
      { id: "c", text: "Viral infection (HPV) of squamous epithelium", isCorrect: false, explanation: "HPV is not associated with Barrett's esophagus" },
      { id: "d", text: "Genetic mutation in p53 as the initiating event", isCorrect: false, explanation: "While p53 mutations occur later, the initial change is inflammation-driven metaplasia" },
    ],
    explanation: "**Barrett's esophagus**: Chronic acid exposure → inflammation → squamous epithelium injury → intestinal metaplasia (columnar mucosa with goblet cells) as reparative response.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-06-TOP-01",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "GI Tract - Ch 17", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 4-year-old boy with β-thalassemia major develops extramedullary hematopoiesis. Which organ is most commonly affected and why?",
    clinicalVignette: "A 4-year-old boy with β-thalassemia major (transfusion-dependent) presents with hepatosplenomegaly, bone deformities, and growth retardation.",
    options: [
      { id: "a", text: "Spleen — due to its reticuloendothelial function and capacity for erythropoiesis", isCorrect: true, explanation: "Spleen is the primary site of extramedullary hematopoiesis due to RES macrophages and residual hematopoietic capability" },
      { id: "b", text: "Liver — due to hepatic regeneration capacity", isCorrect: false, explanation: "Liver participates but is not the primary site" },
      { id: "c", text: "Bone marrow — due to increased proliferation", isCorrect: false, explanation: "BM already maximally involved; extramedullary sites are needed" },
      { id: "d", text: "Thymus — due to T cell production", isCorrect: false, explanation: "Thymus produces T cells, not erythrocytes" },
    ],
    explanation: "**β-thalassemia**: Severe anemia triggers extramedullary hematopoiesis primarily in the **spleen** (due to RES cells and hematopoietic capability) → massive splenomegaly.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-11-TOP-02",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Hematologic Malignancies - Ch 13", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 58-year-old man with newly diagnosed chronic myeloid leukemia shows the Philadelphia chromosome t(9;22). Which oncogenic protein drives leukemogenesis?",
    clinicalVignette: "A 58-year-old male found to have WBC 180,000/μL with left shift on peripheral smear. Cytogenetics show Philadelphia chromosome. Molecular testing confirms BCR-ABL1 fusion.",
    options: [
      { id: "a", text: "BCR-ABL fusion protein with constitutive tyrosine kinase activity", isCorrect: true, explanation: "BCR-ABL1 → constitutive PTK activity → uncontrolled cell proliferation, reduced apoptosis, genomic instability → CML" },
      { id: "b", text: "HER2 with amplified receptor signaling", isCorrect: false, explanation: "HER2 is seen in some breast cancers, not CML" },
      { id: "c", text: "EGFR with activating mutations", isCorrect: false, explanation: "EGFR mutations are found in lung cancer, not CML" },
      { id: "d", text: "RAS with constitutive activation alone", isCorrect: false, explanation: "RAS alone is not sufficient; BCR-ABL is the driver" },
    ],
    explanation: "**Philadelphia chromosome** t(9;22) → **BCR-ABL1 fusion** → constitutive tyrosine kinase → uncontrolled proliferation, reduced apoptosis → chronic myeloid leukemia.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-11-TOP-05",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Hematologic Malignancies - Ch 13", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 48-year-old woman presents with autoimmune thyroiditis. Which mechanism of immune tolerance is primarily defective?",
    clinicalVignette: "A 48-year-old female with elevated TSH (12 mIU/L) and anti-TPO antibodies (>1000 IU/mL), anti-thyroglobulin antibodies. Clinical hypothyroidism confirmed.",
    options: [
      { id: "a", text: "Central tolerance — failure of negative selection in thymus", isCorrect: false, explanation: "Central tolerance is usually intact; the problem is peripheral tolerance" },
      { id: "b", text: "Peripheral tolerance — defective regulatory T cells and loss of immune suppression", isCorrect: true, explanation: "Hashimoto's thyroiditis results from impaired Treg function → loss of self-tolerance → anti-thyroid antibodies and T cell infiltration" },
      { id: "c", text: "Innate immunity activation alone", isCorrect: false, explanation: "While innate immunity is involved, adaptive immune tolerance failure is primary" },
      { id: "d", text: "Epitope spreading from environmental antigens", isCorrect: false, explanation: "Epitope spreading is a consequence, not the primary defect" },
    ],
    explanation: "**Autoimmune thyroiditis (Hashimoto's)**: Impaired Treg function → loss of peripheral tolerance → anti-TPO and anti-thyroglobulin antibodies → thyroid infiltration and destruction.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-09-TOP-02",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Immunopathology - Ch 6", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 70-year-old man with benign prostatic hyperplasia develops urinary retention and renal insufficiency. Which pathophysiologic mechanism explains the renal dysfunction?",
    clinicalVignette: "A 70-year-old male with severe LUTS (Qmax 8 mL/s) and post-void residual 300 mL develops acute kidney injury (Cr 3.2 mg/dL from baseline 1.0).",
    options: [
      { id: "a", text: "Elevated intrapelvic pressure from outlet obstruction → retrograde ureteral pressure transmission", isCorrect: true, explanation: "BPH-induced obstruction → elevated intrapelvic pressure → increased ureteral/renal pressure → glomerular filtration failure → AKI" },
      { id: "b", text: "Direct prostatic invasion of renal parenchyma", isCorrect: false, explanation: "BPH does not involve direct tumor invasion of kidney" },
      { id: "c", text: "Obstructive stone formation in the ureter", isCorrect: false, explanation: "Stones are not the mechanism of BPH-related renal failure" },
      { id: "d", text: "Autonomous neurogenic bladder dysfunction", isCorrect: false, explanation: "While detrusor dysfunction occurs, the renal damage is from mechanical obstruction" },
    ],
    explanation: "**BPH-induced obstructive nephropathy**: Urinary outlet obstruction → elevated intrapelvic/ureteral pressure → decreased glomerular filtration pressure → AKI with potential for chronic kidney disease.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-07-TOP-05",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Genitourinary System - Ch 21", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old with hereditary spherocytosis develops intermittent hemolytic episodes. Which osmotic mechanism explains red cell destruction?",
    clinicalVignette: "A 35-year-old male with family history of HS (father, grandfather) presents with jaundice during infection. Labs show reticulocytosis 15%, indirect bilirubin 6 mg/dL, LDH elevated.",
    options: [
      { id: "a", text: "Loss of membrane deformability due to spectrin deficiency → osmotic lysis in hypotonic spleen cords", isCorrect: true, explanation: "Spectrin mutations → loss of RBC membrane stability → osmotic fragility → hypotonic environment of splenic sinusoids → hemolysis" },
      { id: "b", text: "Direct complement-mediated membrane lysis", isCorrect: false, explanation: "HS is not primarily complement-mediated" },
      { id: "c", text: "Hemoglobin S polymerization", isCorrect: false, explanation: "That's sickle cell disease, not hereditary spherocytosis" },
      { id: "d", text: "Glucose-6-phosphatase deficiency", isCorrect: false, explanation: "G6PD deficiency is a different RBC defect" },
    ],
    explanation: "**Hereditary spherocytosis**: Spectrin/membrane protein mutations → loss of RBC deformability → osmotic fragility → hemolysis in hypotonic spleen cords during splenic passage.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-11-TOP-01",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Hematologic Disorders - Ch 12", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 56-year-old smoker develops squamous cell carcinoma of the anal canal. Which HPV type is most likely responsible?",
    clinicalVignette: "A 56-year-old male smoker with history of anal receptive intercourse presents with anal mass and inguinal lymphadenopathy. HPV PCR on biopsy is positive.",
    options: [
      { id: "a", text: "HPV-16/18 (high-risk oncogenic types)", isCorrect: true, explanation: "HPV-16 (>90% of cases) and HPV-18 cause squamous cell cancers via E6/E7 oncoproteins inactivating p53 and Rb" },
      { id: "b", text: "HPV-6/11 (low-risk types)", isCorrect: false, explanation: "HPV-6/11 cause benign warts, not malignant transformation" },
      { id: "c", text: "HPV-31/33", isCorrect: false, explanation: "While involved, HPV-16/18 are far more common in anal SCC" },
      { id: "d", text: "No HPV involvement", isCorrect: false, explanation: "HPV is present in >85% of anal cancers" },
    ],
    explanation: "**Anal SCC**: HPV-16 (90%+) → E6 inactivates p53, E7 inactivates Rb → loss of cell cycle control → malignant transformation, especially in immunosuppressed or smokers.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-10-TOP-04",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "GI Neoplasms - Ch 17", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 22-year-old woman with Marfan syndrome develops acute aortic dissection. Which connective tissue defect explains the vascular fragility?",
    clinicalVignette: "A 22-year-old tall female with family history of Marfan syndrome presents with sudden-onset tearing chest pain radiating to back. CT angiography shows Type A aortic dissection.",
    options: [
      { id: "a", text: "FBN1 mutation → defective fibrillin-1 → impaired TGF-β signaling → medial necrosis", isCorrect: true, explanation: "Marfan syndrome: FBN1 mutation → fibrillin defects → increased TGF-β signaling → vascular smooth muscle apoptosis → cystic medial necrosis → dissection risk" },
      { id: "b", text: "Type I collagen defect → defective cross-linking", isCorrect: false, explanation: "Type I collagen defects are seen in Ehlers-Danlos syndrome, not Marfan" },
      { id: "c", text: "Elastin degradation from metalloproteinase overgrowth", isCorrect: false, explanation: "While elastin is affected, the primary defect is fibrillin" },
      { id: "d", text: "Smooth muscle hyperplasia from growth hormone excess", isCorrect: false, explanation: "Growth hormone is not the mechanism in Marfan syndrome" },
    ],
    explanation: "**Marfan syndrome**: FBN1 mutations → fibrillin-1 defects → increased TGF-β signaling → vascular smooth muscle cell apoptosis → cystic medial necrosis → aortic dissection risk.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-04-TOP-02",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Genetic Disorders - Ch 5", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 60-year-old presents with renal cell carcinoma. Genetic testing shows VHL gene mutation. Which metabolic derangement contributes to tumorigenesis?",
    clinicalVignette: "A 60-year-old male with family history of renal cancer presents with hematuria and flank pain. Imaging shows bilateral RCC. Genetic testing confirms VHL mutation.",
    options: [
      { id: "a", text: "Loss of VHL → HIF-α accumulation → hypoxia-inducible gene activation → VEGF/PDGF overexpression", isCorrect: true, explanation: "VHL inactivation → HIF-α stabilization → increased VEGF (angiogenesis), PDGF, and other oncogenic pathways → RCC development" },
      { id: "b", text: "Increased p53 activity from loss of negative regulation", isCorrect: false, explanation: "VHL doesn't directly regulate p53 degradation in this manner" },
      { id: "c", text: "Primary mitochondrial dysfunction from energy depletion", isCorrect: false, explanation: "While hypoxia affects metabolism, HIF-α upregulation is the key driver" },
      { id: "d", text: "Chronic hyperkalemia from renal tubular dysfunction", isCorrect: false, explanation: "Hyperkalemia is not the mechanism of VHL-driven RCC" },
    ],
    explanation: "**VHL mutations in RCC**: Loss of VHL protein → HIF-α stabilization → increased VEGF and PDGF → angiogenesis, proliferation → renal cell carcinoma development.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-10-TOP-07",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Kidney Neoplasms - Ch 20", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 40-year-old woman with systemic sclerosis develops progressive renal dysfunction and hypertension. Which pathophysiologic mechanism drives scleroderma renal crisis?",
    clinicalVignette: "A 40-year-old female with diffuse cutaneous scleroderma presents with acute hypertension (200/130 mmHg), rising creatinine (2.8 mg/dL), and hemolytic anemia with schistocytes.",
    options: [
      { id: "a", text: "Endothelial injury → increased renin → severe vasoconstriction → acute cortical necrosis", isCorrect: true, explanation: "Scleroderma renal crisis (SRC): Endothelial damage → renin surge → intense renal vasoconstriction → acute cortical necrosis, MAHA, acute renal failure" },
      { id: "b", text: "Collagen deposition in Bowman's capsule", isCorrect: false, explanation: "Collagen is involved in fibrosis but acute necrosis is from vasoconstriction" },
      { id: "c", text: "Complement activation from immune complex deposition", isCorrect: false, explanation: "Immune complexes are not the primary mechanism in SRC" },
      { id: "d", text: "Direct glomerular basement membrane attack", isCorrect: false, explanation: "Basement membrane attack is seen in ANCA vasculitis, not scleroderma" },
    ],
    explanation: "**Scleroderma renal crisis**: Endothelial injury → renin surge → intense vasoconstriction → acute glomerular capillary necrosis, MAHA, acute kidney injury with hypertension.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-09-TOP-04",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Kidney - Ch 20", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old with familial hypercholesterolemia has LDL-C of 450 mg/dL despite statin therapy. Which genetic defect prevents LDL clearance?",
    clinicalVignette: "A 28-year-old heterozygous FH patient has severe hypercholesterolemia (LDL 450 mg/dL) and tendon xanthomas. Despite atorvastatin 80mg, LDL not well controlled.",
    options: [
      { id: "a", text: "LDL receptor mutations → impaired hepatic LDL uptake", isCorrect: true, explanation: "FH: Heterozygous LDLR mutations (50% of receptors defective) → reduced hepatic LDL clearance → elevated plasma LDL-C" },
      { id: "b", text: "APOE4 polymorphism causing impaired clearance", isCorrect: false, explanation: "APOE4 increases risk but is not the primary cause of FH" },
      { id: "c", text: "Overproduction of apoB from increased liver synthesis", isCorrect: false, explanation: "Overproduction causes FDB (Familial Defective ApoB), not classic FH" },
      { id: "d", text: "Gain-of-function mutation in PCSK9 alone", isCorrect: false, explanation: "PCSK9 mutations are rarer; LDLR mutations are most common" },
    ],
    explanation: "**Familial hypercholesterolemia**: LDLR mutations → 50% (heterozygous) receptor deficiency → impaired hepatic LDL clearance → severe hypercholesterolemia from childhood.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-04-TOP-01",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Genetic Disorders - Ch 5", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 50-year-old with chronic kidney disease develops secondary hyperparathyroidism. Which mechanism explains this paradox despite elevated serum calcium?",
    clinicalVignette: "A 50-year-old with Stage 4 CKD (GFR 20 mL/min) presents with elevated PTH (250 pg/mL), serum Ca 9.2 mg/dL (corrected), PO4 5.8 mg/dL.",
    options: [
      { id: "a", text: "Phosphate retention → FGF23 and PTH elevation → hyperparathyroidism despite normal/high calcium", isCorrect: true, explanation: "CKD: Phosphate retention → FGF23 rise (suppresses 1,25D) → low 1,25D → impaired Ca absorption → PTH rises to maintain Ca despite phosphate problem" },
      { id: "b", text: "Sudden vitamin D toxicity from sunlight exposure", isCorrect: false, explanation: "CKD patients typically have low 1,25D, not toxicity" },
      { id: "c", text: "Autonomous PTH secretion from malignancy", isCorrect: false, explanation: "PTH elevation in CKD is physiologic, not from PTHrP-secreting tumor" },
      { id: "d", text: "Parathyroid adenoma as primary cause", isCorrect: false, explanation: "Secondary hyperparathyroidism is reactive, not adenoma-driven" },
    ],
    explanation: "**CKD-driven secondary hyperparathyroidism**: Phosphate retention → FGF23 ↑ → 1,25D ↓ → Ca ↓ (despite normal corrected) → PTH rises to compensate (vicious cycle).",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-07-TOP-03",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Kidney - Ch 20", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 65-year-old with type 2 diabetes develops albuminuria despite antihypertensive therapy. Which glomerular lesion is characteristic?",
    clinicalVignette: "A 65-year-old with 20-year history of diabetes, HTN, presents with microalbuminuria (80 mg/g) despite ACE inhibitor therapy. Kidney biopsy shows nodular lesions.",
    options: [
      { id: "a", text: "Kimmelstiel-Wilson nodules (mesangial PAS+ matrix expansion)", isCorrect: true, explanation: "Diabetic nephropathy: Hyperglycemia → glomerular basement membrane thickening, mesangial expansion with PAS+ material → Kimmelstiel-Wilson nodules" },
      { id: "b", text: "Crescent formation with fibrinoid necrosis", isCorrect: false, explanation: "Crescents are seen in rapidly progressive GN, not diabetic nephropathy" },
      { id: "c", text: "Wire-loop lesions from immune complex deposition", isCorrect: false, explanation: "Wire-loops are seen in SLE nephritis, not diabetes" },
      { id: "d", text: "Red blood cell casts from acute tubulitis", isCorrect: false, explanation: "RBC casts indicate RPGN, not diabetic changes" },
    ],
    explanation: "**Diabetic nephropathy**: Hyperglycemia → non-enzymatic glycosylation → mesangial expansion with PAS+ material → **Kimmelstiel-Wilson nodules** (pathognomonic lesion).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-07-TOP-01",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Kidney - Ch 20", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 32-year-old woman presents with thrombosis and recurrent miscarriages. Elevated homocysteine (45 μmol/L) is noted. Which enzyme deficiency is most likely?",
    clinicalVignette: "A 32-year-old nulligravida with three consecutive miscarriages, DVT in RLE. Labs: homocysteine 45 μmol/L (normal <15), normal coagulation studies.",
    options: [
      { id: "a", text: "Cystathionine β-synthase deficiency → elevated homocysteine", isCorrect: true, explanation: "CBS deficiency → homocysteine accumulation → endothelial injury, platelet hyperactivation, thrombosis, fetal loss" },
      { id: "b", text: "MTHFR deficiency → impaired methionine synthesis", isCorrect: false, explanation: "MTHFR mutations are common but rarely cause severe elevation" },
      { id: "c", text: "Methionine synthase deficiency", isCorrect: false, explanation: "Rare; less common than CBS deficiency" },
      { id: "d", text: "Primary hepatic disease reducing homocysteine metabolism", isCorrect: false, explanation: "While liver disease can elevate homocysteine, CBS deficiency is more likely here" },
    ],
    explanation: "**Homocystinuria (CBS deficiency)**: Cystathionine β-synthase mutations → homocysteine accumulation → endothelial damage, thrombosis, fetal loss, lens dislocation.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-04-TOP-04",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Genetic Disorders - Ch 5", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 72-year-old man develops acute leukostasis syndrome with WBC count >200,000/μL. Which pathophysiologic mechanism explains the clinical urgency?",
    clinicalVignette: "A 72-year-old male with newly diagnosed AML (blasts 95%) presents with dyspnea, confusion, and blurred vision. WBC 250,000/μL, hematocrit 28%.",
    options: [
      { id: "a", text: "Blast-laden capillaries → impaired microcirculation → hypoxia and hemorrhage", isCorrect: true, explanation: "Leukostasis: Immature blasts → increased blood viscosity → capillary occlusion → tissue hypoxia, RBC extravasation → pulmonary/CNS hemorrhage" },
      { id: "b", text: "Tumor lysis syndrome with hyperkalemia", isCorrect: false, explanation: "Tumor lysis is a consequence, not the primary mechanism of leukostasis" },
      { id: "c", text: "Disseminated intravascular coagulation", isCorrect: false, explanation: "DIC can occur but leukostasis is from pure viscosity/mechanical obstruction" },
      { id: "d", text: "Sepsis from immunosuppression", isCorrect: false, explanation: "Sepsis is a separate concern, not the cause of acute leukostasis" },
    ],
    explanation: "**Leukostasis**: Immature blasts → increased blood viscosity → capillary occlusion → tissue hypoxia, hemorrhage. Emergency cytoreduction needed to prevent death.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-11-TOP-04",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Hematologic Malignancies - Ch 13", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 58-year-old with cirrhosis develops hepatic encephalopathy. Which amino acid imbalance is pathognomonic?",
    clinicalVignette: "A 58-year-old with decompensated cirrhosis (hepatic dysfunction, ascites) presents with confusion, asterixis, and elevated ammonia (180 μmol/L).",
    options: [
      { id: "a", text: "Elevated aromatic amino acids (AAA), low branched-chain amino acids (BCAA) → increased AAA/BCAA ratio", isCorrect: true, explanation: "Cirrhosis: Impaired hepatic metabolism → AAA (tyrosine, phenylalanine) accumulate → BCAA (leucine, isoleucine) depleted → neurotoxic aromatic compound synthesis" },
      { id: "b", text: "Selective glutamine depletion", isCorrect: false, explanation: "While glutamine is involved, the AAA/BCAA ratio imbalance is pathognomonic" },
      { id: "c", text: "Exclusive ammonia accumulation without amino acid changes", isCorrect: false, explanation: "Ammonia is involved but amino acid imbalance is more specific" },
      { id: "d", text: "Increased histidine and lysine", isCorrect: false, explanation: "These amino acids are not the hallmark imbalance" },
    ],
    explanation: "**Hepatic encephalopathy**: Cirrhosis → impaired hepatic metabolism → AAA ↑ (tyrosine, phenylalanine), BCAA ↓ (leucine, isoleucine) → increased AAA/BCAA ratio → neurotoxic compound synthesis.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-06-TOP-04",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Liver & Biliary System - Ch 18", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 6-year-old boy with sickle cell disease develops acute chest syndrome. Which vaso-occlusive mechanism is operative?",
    clinicalVignette: "A 6-year-old with sickle cell disease presents with fever, chest pain, and new infiltrate on CXR. Oxygen saturation 88%, respiratory rate elevated.",
    options: [
      { id: "a", text: "Polymerization of deoxygenated HbS → RBC sickling → vaso-occlusion and hemolysis", isCorrect: true, explanation: "Hypoxemia/acidosis → HbS polymerization → RBC rigidity → capillary occlusion → tissue infarction, acute chest syndrome with pulmonary infiltrates" },
      { id: "b", text: "Autoimmune hemolytic anemia from warm antibodies", isCorrect: false, explanation: "Hemolysis in SCD is from polymerization, not autoimmunity" },
      { id: "c", text: "Pulmonary edema from renal failure", isCorrect: false, explanation: "Renal involvement can occur but ACS is primarily from vaso-occlusion" },
      { id: "d", text: "Fat embolism from bone marrow necrosis alone", isCorrect: false, explanation: "While fat emboli can occur, sickling is the primary mechanism" },
    ],
    explanation: "**Sickle cell disease and acute chest syndrome**: Hypoxemia → HbS polymerization → RBC sickling → vaso-occlusion → pulmonary infarction with fever and infiltrates.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-11-TOP-03",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Hematologic Disorders - Ch 12", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 40-year-old with chronic hepatitis B presents with jaundice, ascites, and variceal bleeding. Liver biopsy shows hepatic fibrosis with bridging necrosis. What is the grade of fibrosis?",
    clinicalVignette: "A 40-year-old with HBsAg positive for 15 years develops decompensated cirrhosis with variceal bleeding. Liver biopsy: septal fibrosis bridging across hepatic sinusoids.",
    options: [
      { id: "a", text: "Ishak fibrosis score 5-6 (bridging fibrosis/early cirrhosis) indicating advanced disease", isCorrect: true, explanation: "Ishak scoring: 0-no fibrosis, 1-portal fibrosis, 2-periportal fibrosis, 3-bridging fibrosis, 4-incomplete cirrhosis, 5-complete cirrhosis. Bridging fibrosis (Ishak 3-4) indicates advanced disease with cirrhosis risk." },
      { id: "b", text: "Metavir score F1 (minimal fibrosis)", isCorrect: false, explanation: "F1 is minimal; bridging is F3-F4" },
      { id: "c", text: "No fibrosis despite bridging pattern", isCorrect: false, explanation: "Bridging specifically indicates F3+ disease" },
      { id: "d", text: "Simple portal inflammation without fibrosis", isCorrect: false, explanation: "Bridging fibrosis is extensive" },
    ],
    explanation: "**Bridging fibrosis**: Ishak score 3-4, Metavir F3-F4 = advanced fibrosis with bridging between portal/central areas. High risk of cirrhosis progression.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-06-TOP-02",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Liver & Biliary System - Ch 18", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 55-year-old smoker develops small cell lung cancer (SCLC) with ectopic ACTH syndrome. Which hormone is overproduced and causes hypokalemia?",
    clinicalVignette: "55-year-old smoker with SCLC presents with hypertension (BP 165/100), severe hypokalemia (K 2.8), hyperglycemia (180 mg/dL), and muscle weakness.",
    options: [
      { id: "a", text: "Ectopic ACTH from SCLC → stimulates cortisol release → hypokalemic metabolic alkalosis", isCorrect: true, explanation: "SCLC secretes ACTH → excessive cortisol → mineralocorticoid effect → Na+ retention, K+ wasting → hypokalemia, hypertension, metabolic alkalosis, hyperglycemia" },
      { id: "b", text: "Ectopic vasopressin (ADH) causing hyponatremia", isCorrect: false, explanation: "While SCLC does secrete ADH, this case has hypokalemia, not hyponatremia" },
      { id: "c", text: "Ectopic PTHrP causing hypercalcemia", isCorrect: false, explanation: "PTHrP is more common in squamous cell lung cancer" },
      { id: "d", text: "Direct renal infiltration from tumor", isCorrect: false, explanation: "The mechanism is paraneoplastic (ectopic hormone production)" },
    ],
    explanation: "**SCLC with ectopic ACTH**: Overproduction of cortisol → mineralocorticoid effects → hypokalemia, hypertension, metabolic alkalosis, hyperglycemia.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-10-TOP-09",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Lung Neoplasms - Ch 15", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 65-year-old with chronic kidney disease develops bone pain and pathologic fractures. X-ray shows 'rugger jersey spine' appearance. What is the metabolic bone disease?",
    clinicalVignette: "65-year-old with CKD Stage 5 (GFR 8) develops bone pain, vertebral fractures. X-ray: alternating bands of sclerosis and osteopenia in spine.",
    options: [
      { id: "a", text: "Renal osteodystrophy with secondary hyperparathyroidism → mixed pattern of osteosclerosis and osteopenia", isCorrect: true, explanation: "CKD → phosphate retention → FGF23 ↑, 1,25D ↓ → secondary hyperparathyroidism → 'rugger jersey spine' (alternating dense/lucent bands) from abnormal bone turnover" },
      { id: "b", text: "Primary hyperparathyroidism with parathyroid adenoma", isCorrect: false, explanation: "Primary HPT has different radiographic features" },
      { id: "c", text: "Pure osteoporosis from disuse atrophy", isCorrect: false, explanation: "Rugger jersey pattern is specific to renal osteodystrophy" },
      { id: "d", text: "Paget disease with jigsaw-puzzle pattern", isCorrect: false, explanation: "Paget disease has different appearance" },
    ],
    explanation: "**Renal osteodystrophy**: Secondary hyperparathyroidism → abnormal bone turnover → 'rugger jersey spine' (alternating bands of dense/lucent vertebrae).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-07-TOP-04",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Kidney - Ch 20", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old with Crohn disease develops erythema nodosum (tender nodules on shins) during an inflammatory flare. Which immunopathologic mechanism is operative?",
    clinicalVignette: "28-year-old with Crohn disease and active diarrhea develops painful nodules on lower legs. Biopsy shows septal inflammation without vasculitis.",
    options: [
      { id: "a", text: "Type III hypersensitivity — immune complex deposition in septal tissue, septal (non-vasculitic) inflammation", isCorrect: true, explanation: "Erythema nodosum: Type III reaction with septal inflammation (NOT vasculitis, unlike erythema multiforme). Immune complexes deposit in dermis → neutrophilic infiltration of fat septa." },
      { id: "b", text: "Type II hypersensitivity from antibodies to skin antigens", isCorrect: false, explanation: "Erythema nodosum is not antibody-mediated directly" },
      { id: "c", text: "Type I hypersensitivity with mast cell-mediated vasodilation", isCorrect: false, explanation: "Type I is not involved; this is immune complex-mediated" },
      { id: "d", text: "Type IV hypersensitivity from activated T cells", isCorrect: false, explanation: "While T cells are involved, the primary mechanism is immune complex deposition" },
    ],
    explanation: "**Erythema nodosum in IBD**: Type III (immune complex) hypersensitivity with septal (non-vasculitic) inflammation. Associated with Crohn disease activity.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-09-TOP-06",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Immunopathology - Ch 6", edition: "10th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 72-year-old with chronic obstructive pulmonary disease develops acute pulmonary embolism. Which pathophysiologic mechanism explains the sudden increase in right ventricular afterload?",
    clinicalVignette: "72-year-old with COPD develops sudden dyspnea, chest pain. CT pulmonary angiography (CTPA) shows bilateral PE. Sudden RV dilatation on echocardiography.",
    options: [
      { id: "a", text: "Acute increase in pulmonary vascular resistance (PVR) from thromboembolism and hypoxic vasoconstriction", isCorrect: true, explanation: "Acute PE: Thromboembolism obstructs pulmonary vessels → ↑PVR. Additionally, hypoxemia triggers hypoxic pulmonary vasoconstriction → further ↑PVR → RV afterload ↑ → RV dilatation, potential cardiogenic shock." },
      { id: "b", text: "Left ventricular dysfunction from myocardial infarction", isCorrect: false, explanation: "While RV infarction can occur with RV PE, primary mechanism is PVR ↑" },
      { id: "c", text: "Cardiac tamponade from pericardial effusion", isCorrect: false, explanation: "Tamponade is not the primary mechanism of PE-related RV failure" },
      { id: "d", text: "Myocardial contractility loss from septic shock", isCorrect: false, explanation: "PE is thrombotic, not infectious" },
    ],
    explanation: "**PE pathophysiology**: Acute pulmonary vascular obstruction + hypoxic vasoconstriction → ↑PVR → RV afterload ↑ → RV failure, shock.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"],
    subjectCode: "PA",
    topicCode: "PA-MOD-07-TOP-06",
    textbookRefs: [{ book: "Robbins & Cotran", chapter: "Heart - Ch 11", edition: "10th" }],
  },
];
