// Biochemistry MCQs - NEXT pattern (50 questions) - Phase 1
// Distribution: 25% EASY, 40% MEDIUM, 25% HARD, 10% EXPERT
// Pattern: 60% ProblemSolving, 30% Analysis, 10% Recall

export const biochemistryFullMcqs = [
  // ============ EASY (12 questions) ============
  // Mostly Recall and some Analysis
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-01-TOP-01",
    stem: "Which monosaccharide is the primary fuel for the brain under normal conditions?",
    options: [
      { id: "a", text: "Fructose", isCorrect: false, explanation: "Fructose is processed primarily by liver" },
      { id: "b", text: "Glucose", isCorrect: true, explanation: "Glucose is the preferred brain fuel (5-6 mg/kg/min)" },
      { id: "c", text: "Galactose", isCorrect: false, explanation: "Galactose is from lactose" },
      { id: "d", text: "Glyceraldehyde", isCorrect: false, explanation: "Not a major fuel source" },
    ],
    explanation: "**Glucose** is the **primary fuel source for the brain** under normal conditions, accounting for virtually all brain energy production. The brain utilizes **5-6 mg/kg/min** of glucose and cannot efficiently use long-chain fatty acids.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Carbohydrate Metabolism", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-01-TOP-02",
    stem: "Which lipid class has the highest energy density?",
    options: [
      { id: "a", text: "Carbohydrates", isCorrect: false, explanation: "4 kcal/g" },
      { id: "b", text: "Proteins", isCorrect: false, explanation: "4 kcal/g" },
      { id: "c", text: "Fats", isCorrect: true, explanation: "9 kcal/g — highest energy density" },
      { id: "d", text: "Nucleic acids", isCorrect: false, explanation: "4 kcal/g" },
    ],
    explanation: "**Fats (lipids)** provide **9 kcal/g**, while carbohydrates and proteins provide **4 kcal/g**. This makes fat storage the most efficient form of energy for the body.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Lipid Metabolism", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-01-TOP-03",
    stem: "Which amino acid is the only one that does NOT contain a chiral center?",
    options: [
      { id: "a", text: "Alanine", isCorrect: false, explanation: "Alanine has a chiral center" },
      { id: "b", text: "Glycine", isCorrect: true, explanation: "Glycine has no chiral center (H is both R groups)" },
      { id: "c", text: "Serine", isCorrect: false, explanation: "Serine has a chiral center" },
      { id: "d", text: "Cysteine", isCorrect: false, explanation: "Cysteine has a chiral center" },
    ],
    explanation: "**Glycine** is the only amino acid without a chiral center because its side chain (R group) is simply a hydrogen atom. All other amino acids have 4 different groups attached to the alpha carbon.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Amino Acids and Proteins", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-02-TOP-01",
    stem: "Enzymes increase the rate of reactions by:",
    options: [
      { id: "a", text: "Increasing the free energy of products", isCorrect: false, explanation: "ΔG remains unchanged" },
      { id: "b", text: "Decreasing the activation energy (Ea)", isCorrect: true, explanation: "Enzymes lower Ea" },
      { id: "c", text: "Changing the equilibrium constant", isCorrect: false, explanation: "Keq remains unchanged" },
      { id: "d", text: "Changing the overall free energy change", isCorrect: false, explanation: "ΔG is unaffected" },
    ],
    explanation: "**Enzymes** accelerate reactions by **lowering the activation energy (Ea)** required for substrate conversion to product. They do NOT change the thermodynamic properties (ΔG, Keq) of the reaction.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Enzyme Kinetics", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-03-TOP-01",
    stem: "The first committed step of glycolysis is catalyzed by:",
    options: [
      { id: "a", text: "Hexokinase", isCorrect: false, explanation: "Glucose phosphorylation can be reversible" },
      { id: "b", text: "Phosphofructokinase-1 (PFK-1)", isCorrect: true, explanation: "PFK-1 catalyzes the first committed, rate-limiting step" },
      { id: "c", text: "Pyruvate kinase", isCorrect: false, explanation: "Final step of glycolysis" },
      { id: "d", text: "Glucose-6-phosphatase", isCorrect: false, explanation: "Reverses hexokinase reaction" },
    ],
    explanation: "**Phosphofructokinase-1 (PFK-1)** catalyzes the conversion of **fructose-6-phosphate to fructose-1,6-bisphosphate**. This is the **first committed and rate-limiting step** of glycolysis (not hexokinase, which is reversible).",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Glycolysis", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-04-TOP-01",
    stem: "Which organ is the primary site of ketone body formation?",
    options: [
      { id: "a", text: "Brain", isCorrect: false, explanation: "Brain uses ketones but doesn't produce them" },
      { id: "b", text: "Liver", isCorrect: true, explanation: "Liver is the primary site of ketogenesis" },
      { id: "c", text: "Heart", isCorrect: false, explanation: "Heart uses ketones but doesn't produce them" },
      { id: "d", text: "Adipose tissue", isCorrect: false, explanation: "Adipose provides fatty acids" },
    ],
    explanation: "The **liver** is the **primary site of ketone body formation** during **fasting, starvation, or diabetes**. Ketones (acetoacetate, β-hydroxybutyrate, acetone) are produced from acetyl-CoA derived from fatty acid oxidation.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Lipid Metabolism", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-05-TOP-01",
    stem: "Which enzyme catalyzes the first step of the urea cycle?",
    options: [
      { id: "a", text: "Carbamoyl phosphate synthetase I (CPS I)", isCorrect: true, explanation: "CPS I catalyzes ammonia fixation" },
      { id: "b", text: "Ornithine transcarbamylase", isCorrect: false, explanation: "OTC catalyzes step 2" },
      { id: "c", text: "Argininosuccinate synthetase", isCorrect: false, explanation: "Catalyzes step 4" },
      { id: "d", text: "Arginase", isCorrect: false, explanation: "Final step" },
    ],
    explanation: "**Carbamoyl phosphate synthetase I (CPS I)** catalyzes the **first step of the urea cycle**, incorporating ammonia (NH3) into **carbamoyl phosphate**. This enzyme is located in **mitochondria** and is highly regulated by **N-acetylglutamate**.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Urea Cycle", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-06-TOP-01",
    stem: "DNA replication is semiconservative, meaning:",
    options: [
      { id: "a", text: "Each daughter DNA contains one old and one new strand", isCorrect: true, explanation: "Meselson-Stahl experiment proved this" },
      { id: "b", text: "Each daughter DNA contains two new strands", isCorrect: false, explanation: "Conservative replication" },
      { id: "c", text: "DNA is partially degraded and resynthesized", isCorrect: false, explanation: "DNA is conserved, not degraded" },
      { id: "d", text: "Only one strand is copied", isCorrect: false, explanation: "Both strands serve as templates" },
    ],
    explanation: "**Semiconservative replication** means each daughter DNA molecule contains **one original (parental) strand** and **one newly synthesized strand**. This was demonstrated by **Meselson and Stahl** using nitrogen isotopes.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "DNA Replication", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-06-TOP-03",
    stem: "Which component of the ribosome catalyzes peptide bond formation?",
    options: [
      { id: "a", text: "Ribosomal protein", isCorrect: false, explanation: "Proteins are structural" },
      { id: "b", text: "23S rRNA (28S in eukaryotes) — the peptidyl transferase center", isCorrect: true, explanation: "Ribozyme activity" },
      { id: "c", text: "tRNA", isCorrect: false, explanation: "tRNA brings amino acids" },
      { id: "d", text: "mRNA", isCorrect: false, explanation: "mRNA carries genetic information" },
    ],
    explanation: "**Peptide bond formation** is catalyzed by the **23S rRNA** (or **28S rRNA in eukaryotes**), which acts as a **ribozyme** with **peptidyl transferase activity**. This demonstrates that ribosomal function depends on RNA catalysis, not protein catalysis.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Translation", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-07-TOP-03",
    stem: "Which vitamin acts as a coenzyme for transaminases?",
    options: [
      { id: "a", text: "Vitamin B1 (thiamine)", isCorrect: false, explanation: "Thiamine is for dehydrogenases" },
      { id: "b", text: "Vitamin B6 (pyridoxal phosphate)", isCorrect: true, explanation: "PLP is the cofactor for transaminases" },
      { id: "c", text: "Vitamin C", isCorrect: false, explanation: "Ascorbic acid is a reducing agent" },
      { id: "d", text: "Vitamin B12", isCorrect: false, explanation: "B12 is for methyltransferases" },
    ],
    explanation: "**Vitamin B6 (pyridoxal phosphate - PLP)** serves as the coenzyme for **transaminases (aminotransferases)** and **decarboxylases**. It facilitates the transfer of amino groups between amino acids and alpha-keto acids.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Vitamins and Coenzymes", edition: "7th" }],
  },

  // ============ MEDIUM (20 questions) ============
  // Mostly ProblemSolving and some Analysis
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-02-TOP-02",
    stem: "A patient with enzyme inhibitor poisoning has a decreased Vmax but normal Km. What type of inhibition occurred?",
    clinicalVignette: "A 35-year-old patient exposed to organophosphate pesticide shows decreased ability to metabolize substrates. Kinetic analysis shows reduced maximum velocity.",
    options: [
      { id: "a", text: "Competitive inhibition", isCorrect: false, explanation: "Increases Km, doesn't change Vmax" },
      { id: "b", text: "Noncompetitive inhibition", isCorrect: true, explanation: "Decreases Vmax, normal Km" },
      { id: "c", text: "Uncompetitive inhibition", isCorrect: false, explanation: "Decreases both Vmax and Km" },
      { id: "d", text: "Mixed inhibition", isCorrect: false, explanation: "Changes both parameters" },
    ],
    explanation: "**Noncompetitive inhibition** decreases **Vmax** (maximum velocity) while keeping **Km** unchanged. The inhibitor binds to enzyme or enzyme-substrate complex with equal affinity, regardless of substrate concentration. This cannot be overcome by increasing substrate concentration.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Enzyme Inhibition", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-03-TOP-02",
    stem: "A diabetic patient develops diabetic ketoacidosis. Which enzyme is overactive, producing excess acetyl-CoA?",
    clinicalVignette: "A 18-year-old type 1 diabetic stops insulin therapy and develops severe hyperglycemia, metabolic acidosis, and ketonemia. Fatty acid oxidation is uncontrolled.",
    options: [
      { id: "a", text: "Glycolysis enzymes", isCorrect: false, explanation: "Glycolysis is inhibited in DKA" },
      { id: "b", text: "Carnitine palmitoyltransferase I (CPT I)", isCorrect: true, explanation: "CPT I allows fatty acid entry into mitochondria for oxidation" },
      { id: "c", text: "Acetyl-CoA carboxylase", isCorrect: false, explanation: "Inhibited in fasting" },
      { id: "d", text: "Glycogen phosphorylase", isCorrect: false, explanation: "Causes glucose release" },
    ],
    explanation: "In **diabetic ketoacidosis**, **loss of insulin** leads to loss of inhibition of **CPT I** (carnitine palmitoyltransferase I). This allows **massive fatty acid oxidation** in hepatic mitochondria, generating excessive **acetyl-CoA** that enters ketogenesis pathway.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Fatty Acid Oxidation", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-04-TOP-03",
    stem: "A patient with familial hypercholesterolemia has very high LDL cholesterol despite low dietary cholesterol. What is the molecular defect?",
    clinicalVignette: "A 45-year-old male with genetic predisposition has LDL-C of 450 mg/dL. Dietary restriction has minimal effect. He develops early coronary artery disease.",
    options: [
      { id: "a", text: "Increased HMG-CoA reductase activity", isCorrect: false, explanation: "Would be secondary" },
      { id: "b", text: "Loss or dysfunction of LDL receptor", isCorrect: true, explanation: "Familial hypercholesterolemia is LDL-R deficiency" },
      { id: "c", text: "Increased VLDL production", isCorrect: false, explanation: "Could be secondary" },
      { id: "d", text: "Increased apoB-100 synthesis", isCorrect: false, explanation: "Would increase particle number" },
    ],
    explanation: "**Familial hypercholesterolemia (FH)** is caused by **loss or dysfunction of the LDL receptor gene**. Without functional LDL receptors, cells cannot take up LDL particles, leading to **severe LDL accumulation** in blood and **premature cardiovascular disease**.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Cholesterol and Lipoproteins", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-05-TOP-02",
    stem: "A patient with ornithine transcarbamylase (OTC) deficiency accumulates ammonia. What is the biochemical consequence?",
    clinicalVignette: "A newborn with OTC deficiency presents with hyperammonemia (>1000 μmol/L), lethargy, and seizures. Urine orotic acid is markedly elevated.",
    options: [
      { id: "a", text: "Inability to form carbamoyl phosphate", isCorrect: false, explanation: "CPS I still forms carbamoyl phosphate" },
      { id: "b", text: "Inability to incorporate ammonia into the urea cycle", isCorrect: true, explanation: "OTC catalyzes ammonia fixation into carbamoyl phosphate" },
      { id: "c", text: "Loss of mitochondrial integrity", isCorrect: false, explanation: "Specific enzyme defect" },
      { id: "d", text: "Increased urinary urea", isCorrect: false, explanation: "Urea production is decreased" },
    ],
    explanation: "**OTC (ornithine transcarbamylase) deficiency** blocks the urea cycle at the step where **carbamoyl phosphate** is combined with **ornithine**. This prevents **ammonia incorporation into the urea cycle**, leading to **severe hyperammonemia** and **neurological toxicity**.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Inborn Errors of Urea Cycle", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-06-TOP-02",
    stem: "A patient with RNA polymerase II inhibitor toxin develops transcriptional shutdown. Which type of genes are affected?",
    clinicalVignette: "A patient exposed to alpha-amanitin (RPII inhibitor) loses ability to synthesize mRNA. Ribosomal RNA synthesis continues.",
    options: [
      { id: "a", text: "All genes equally", isCorrect: false, explanation: "Specific RNA polymerase" },
      { id: "b", text: "Protein-coding genes (mRNA synthesis)", isCorrect: true, explanation: "RNA Pol II transcribes protein-coding genes" },
      { id: "c", text: "Only ribosomal RNA genes", isCorrect: false, explanation: "RNA Pol I transcribes rRNA" },
      { id: "d", text: "Only transfer RNA genes", isCorrect: false, explanation: "RNA Pol III transcribes tRNA" },
    ],
    explanation: "**RNA polymerase II** transcribes **protein-coding genes** (producing mRNA) and **non-coding RNA genes**. **RNA Pol I** transcribes **rRNA** (except 5S), and **RNA Pol III** transcribes **tRNA** and **5S rRNA**. Alpha-amanitin selectively inhibits **Pol II** and **Pol III**, leaving **Pol I** relatively unaffected.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Transcription", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-01-TOP-04",
    stem: "A patient with glycogen storage disease type I (Von Gierke disease) cannot form glucose from glucose-6-phosphate. Which enzyme is deficient?",
    clinicalVignette: "A 3-year-old child with severe hypoglycemia, hepatomegaly, and growth retardation is found to have glucose-6-phosphatase deficiency.",
    options: [
      { id: "a", text: "Phosphorylase", isCorrect: false, explanation: "Would affect glycogen breakdown" },
      { id: "b", text: "Glucose-6-phosphatase", isCorrect: true, explanation: "GSD type I from glucose-6-phosphatase deficiency" },
      { id: "c", text: "Glycogen synthase", isCorrect: false, explanation: "Would increase glycogen" },
      { id: "d", text: "Hexokinase", isCorrect: false, explanation: "Would affect glucose entry" },
    ],
    explanation: "**Glycogen storage disease type I (Von Gierke disease)** results from **glucose-6-phosphatase deficiency**. This enzyme catalyzes the **final step of both gluconeogenesis and glycogenolysis**, converting **glucose-6-phosphate to free glucose** for release into blood. Deficiency causes **severe fasting hypoglycemia, massive hepatomegaly, and lactic acidosis**.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Glycogen Storage Diseases", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-02-TOP-03",
    stem: "A patient on long-term antibiotic therapy develops niacin (vitamin B3) deficiency and pellagra. What is the mechanism?",
    clinicalVignette: "A 50-year-old on prolonged antibiotic therapy for TB develops dermatitis, diarrhea, and dementia consistent with pellagra despite adequate dietary niacin intake.",
    options: [
      { id: "a", text: "Antibiotics directly decrease niacin absorption", isCorrect: false, explanation: "Absorption is normal" },
      { id: "b", text: "Antibiotics eliminate commensal bacteria that synthesize niacin", isCorrect: true, explanation: "Gut bacteria produce niacin" },
      { id: "c", text: "Decreased hepatic metabolism", isCorrect: false, explanation: "Not the mechanism" },
      { id: "d", text: "Increased urinary niacin loss", isCorrect: false, explanation: "Not increased" },
    ],
    explanation: "**Commensal bacteria in the gut** synthesize **niacin (vitamin B3)**. **Antibiotics** eliminate these bacteria, reducing endogenous niacin production. Combined with dietary restriction, this can lead to **niacin deficiency and pellagra** (dermatitis, diarrhea, dementia, death — the 4 Ds).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Niacin and NAD", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-03-TOP-04",
    stem: "A patient with glycogen phosphorylase deficiency presents with exercise-induced muscle cramps. Why does exercise worsen symptoms?",
    clinicalVignette: "A young athlete with glycogen phosphorylase deficiency (McArdle disease) develops muscle pain and weakness during exercise. Glycolysis is impaired despite adequate glucose.",
    options: [
      { id: "a", text: "Cannot break down glycogen to glucose-1-phosphate in muscles", isCorrect: true, explanation: "Glycolysis depends on muscle glycogen breakdown" },
      { id: "b", text: "Hyperammonemia from muscle metabolism", isCorrect: false, explanation: "Related but not primary" },
      { id: "c", text: "Increased lactate production", isCorrect: false, explanation: "Lactate is not produced" },
      { id: "d", text: "Mitochondrial dysfunction", isCorrect: false, explanation: "Mitochondria are intact" },
    ],
    explanation: "**McArdle disease** (glycogen phosphorylase deficiency) prevents **muscle glycogen breakdown**. During exercise, muscles cannot mobilize glycogen for glycolysis, causing **"second wind" phenomenon** (symptoms improve as blood glucose enters muscle), **myoglobinuria**, and **permanent muscle damage** with repeated episodes.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Glycogen Storage Diseases", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-05-TOP-04",
    stem: "A newborn with jaundice and dark urine has elevated unconjugated bilirubin. What is the primary defect?",
    clinicalVignette: "A 3-day-old with Crigler-Najjar syndrome presents with severe unconjugated hyperbilirubinemia. Urine appears dark (biliary pigments) despite low direct bilirubin.",
    options: [
      { id: "a", text: "Impaired hemoglobin degradation", isCorrect: false, explanation: "Heme breakdown is normal" },
      { id: "b", text: "Impaired bilirubin conjugation (UDP-glucuronosyltransferase deficiency)", isCorrect: true, explanation: "UGTIA1 deficiency in Crigler-Najjar" },
      { id: "c", text: "Impaired bilirubin excretion", isCorrect: false, explanation: "Would cause conjugated hyperbilirubinemia" },
      { id: "d", text: "Increased hemolysis", isCorrect: false, explanation: "Would cause secondary elevation" },
    ],
    explanation: "**Crigler-Najjar syndrome** results from **UDP-glucuronosyltransferase (UGTIA1) deficiency**, preventing **bilirubin conjugation**. This causes **unconjugated hyperbilirubinemia** with risk of **kernicterus** (bilirubin encephalopathy). Type I is severe and progressive; Type II is milder.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Bilirubin Metabolism", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-01-TOP-05",
    stem: "A patient with abnormal hemoglobin has decreased oxygen binding despite normal oxygen saturation at high partial pressures. What is the likely defect?",
    clinicalVignette: "A 40-year-old with an abnormal hemoglobin variant has a right-shifted oxygen-hemoglobin dissociation curve but normal P50 measurement.",
    options: [
      { id: "a", text: "Decreased cooperativity (abnormal Hill coefficient)", isCorrect: true, explanation: "Loss of cooperativity impairs oxygen binding" },
      { id: "b", text: "Increased 2,3-BPG binding", isCorrect: false, explanation: "Would decrease oxygen affinity" },
      { id: "c", text: "Increased fetal hemoglobin", isCorrect: false, explanation: "Would increase oxygen affinity" },
      { id: "d", text: "Increased methemoglobin", isCorrect: false, explanation: "Would impair function" },
    ],
    explanation: "**Hemoglobin cooperativity** (Hill coefficient ~2.8) allows **sigmoidal binding curve** where **oxygen binding to one subunit increases affinity** of other subunits. Mutations affecting cooperativity (like hemoglobin Kansas) impair oxygen uptake but may allow near-normal saturation at high PO2 in lungs.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Hemoglobin Structure and Function", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-03-TOP-02",
    stem: "A diabetic patient on long-term metformin therapy develops vitamin B12 deficiency. What is the mechanism?",
    clinicalVignette: "A 60-year-old on metformin for 10 years develops megaloblastic anemia and peripheral neuropathy from B12 deficiency despite normal intrinsic factor.",
    options: [
      { id: "a", text: "Metformin inhibits intrinsic factor production", isCorrect: false, explanation: "Intrinsic factor is normal" },
      { id: "b", text: "Metformin impairs terminal ileum calcium-dependent B12 absorption", isCorrect: true, explanation: "Metformin affects B12 transport mechanism" },
      { id: "c", text: "Increased urinary B12 loss", isCorrect: false, explanation: "B12 is not lost in urine" },
      { id: "d", text: "Direct B12 metabolism inhibition", isCorrect: false, explanation: "Transport is the issue" },
    ],
    explanation: "**Metformin** can impair **B12 absorption** in the **terminal ileum** by interfering with the **calcium-dependent absorption mechanism**. While the incidence is low (10-30% of long-term users), screening and supplementation are recommended for at-risk patients.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Vitamin B12 Metabolism", edition: "7th" }],
  },

  // ============ HARD (12 questions) ============
  // Mostly ProblemSolving and Analysis
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-03-TOP-01",
    stem: "A patient with Pasteur effect deficiency loses the normal feedback inhibition when transitioning from anaerobic to aerobic metabolism. What is the critical enzyme?",
    clinicalVignette: "A cancer cell line shows enhanced glycolysis even in the presence of adequate oxygen (Warburg effect). The key regulatory enzyme is dysregulated.",
    options: [
      { id: "a", text: "Hexokinase", isCorrect: false, explanation: "Regulated by glucose availability" },
      { id: "b", text: "Phosphofructokinase-1 (PFK-1)", isCorrect: true, explanation: "PFK-1 is inhibited by ATP and citrate in Pasteur effect" },
      { id: "c", text: "Pyruvate kinase", isCorrect: false, explanation: "Final step" },
      { id: "d", text: "Glucose-6-phosphatase", isCorrect: false, explanation: "Not in glycolysis" },
    ],
    explanation: "The **Pasteur effect** describes the **inhibition of glycolysis by oxidative phosphorylation** when oxygen is available. **PFK-1** is inhibited by **ATP and citrate** (products of oxidative metabolism). Loss of this regulation (as in cancer) leads to continued high glycolysis despite oxygen availability (**Warburg effect**).",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Glycolysis Regulation", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-04-TOP-04",
    stem: "A patient develops xanthomas and accelerated atherosclerosis from elevated cholesterol. Which regulatory mechanism is dysregulated?",
    clinicalVignette: "A 50-year-old with familial defective apoB-100 has mutations that prevent LDL-R binding. Cholesterol feedback inhibition of HMG-CoA reductase is impaired.",
    options: [
      { id: "a", text: "Loss of SREBP (sterol regulatory element-binding protein) activation", isCorrect: true, explanation: "SREBP senses cholesterol and regulates HMG-CoA reductase" },
      { id: "b", text: "Increased HMG-CoA reductase transcription", isCorrect: false, explanation: "This is the consequence" },
      { id: "c", text: "Decreased LDL-R transcription", isCorrect: false, explanation: "Result of SREBP dysfunction" },
      { id: "d", text: "Loss of apoB-100 synthesis", isCorrect: false, explanation: "AppB is synthesized" },
    ],
    explanation: "**SREBP (sterol regulatory element-binding protein)** senses **intracellular cholesterol levels**. When cholesterol is low, **SREBP** is activated and increases transcription of **HMG-CoA reductase** (cholesterol synthesis) and **LDL-R** (cholesterol uptake). When cholesterol is high, **SREBP** remains inactive, preventing synthesis. Mutations affecting LDL-R function impair this feedback loop.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Cholesterol Regulation", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-06-TOP-04",
    stem: "A patient with cancer develops resistance to transcription factor inhibitors through epigenetic modification. Which mechanism allows gene reactivation?",
    clinicalVignette: "A cancer patient initially responds to a transcription factor inhibitor but later develops resistance. DNA methylation patterns have changed, reactivating silenced genes.",
    options: [
      { id: "a", text: "Loss of DNA methylation at promoter regions", isCorrect: true, explanation: "Methylation normally silences genes; loss reactivates them" },
      { id: "b", text: "Increased histone acetylation", isCorrect: false, explanation: "Would open chromatin" },
      { id: "c", text: "Decreased histone deacetylation", isCorrect: false, explanation: "Would open chromatin" },
      { id: "d", text: "Increased chromatin condensation", isCorrect: false, explanation: "Would silence genes further" },
    ],
    explanation: "**DNA methylation** at **CpG islands** in gene promoters typically **silences transcription**. **Epigenetic reactivation** can occur through **loss of DNA methylation** (via DNMT inhibitors or passive demethylation), reopening **chromatin structure** and allowing **transcription factor access**.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Epigenetics and Gene Regulation", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-05-TOP-05",
    stem: "A patient with acute leukemia has elevated serum urate and risk of tumor lysis syndrome. What causes the hyperuricemia?",
    clinicalVignette: "A 45-year-old with acute myeloid leukemia undergoing chemotherapy develops severe hyperuricemia, acute kidney injury, and gout. Massive cell death overwhelms uric acid excretion.",
    options: [
      { id: "a", text: "Increased nucleotide catabolism from tumor cell death", isCorrect: true, explanation: "Cell death releases nucleotides converted to uric acid" },
      { id: "b", text: "Decreased xanthine oxidase activity", isCorrect: false, explanation: "Activity is normal" },
      { id: "c", text: "Impaired renal urate excretion alone", isCorrect: false, explanation: "Overproduction is primary" },
      { id: "d", text: "Increased urinary uric acid clearance", isCorrect: false, explanation: "Clearance is impaired" },
    ],
    explanation: "**Tumor lysis syndrome** occurs when **chemotherapy kills rapidly dividing cancer cells**, releasing **nucleotides, proteins, and potassium**. **Purine and pyrimidine metabolism** of released nucleotides produces **uric acid** faster than kidneys can excrete it, causing **severe hyperuricemia** and **acute kidney injury** (urate crystal precipitation).",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Nucleotide Metabolism", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-02-TOP-01",
    stem: "A patient with a genetic mutation has altered enzyme kinetics showing a dramatically increased Km for substrate. What is the likely consequence?",
    clinicalVignette: "A 35-year-old carries a missense mutation in hexokinase that increases Km for glucose by 10-fold. What is the metabolic consequence?",
    options: [
      { id: "a", text: "Decreased glucose phosphorylation at physiological glucose concentrations", isCorrect: true, explanation: "Higher Km means lower affinity" },
      { id: "b", text: "Increased glucose phosphorylation", isCorrect: false, explanation: "Opposite occurs" },
      { id: "c", text: "No change in enzyme function", isCorrect: false, explanation: "Km change affects activity" },
      { id: "d", text: "Increased enzyme stability", isCorrect: false, explanation: "Kinetic parameter change" },
    ],
    explanation: "**Km (Michaelis constant)** represents the substrate concentration at which enzyme velocity is half-maximal. **Increased Km** indicates **decreased substrate affinity**. At physiological glucose concentrations (5 mM), an enzyme with increased Km would operate at lower velocity, reducing glucose phosphorylation capacity.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Enzyme Kinetics", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-07-TOP-05",
    stem: "A patient with phenylketonuria (PKU) has elevated phenylalanine due to enzyme deficiency. Why is early dietary restriction critical?",
    clinicalVignette: "A newborn screened positive for PKU with phenylalanine >1200 μmol/L. Immediate dietary restriction is started to prevent permanent neurological damage.",
    options: [
      { id: "a", text: "Excess phenylalanine is converted to phenylacetate causing neurotoxicity", isCorrect: true, explanation: "Metabolite accumulation causes damage" },
      { id: "b", text: "Direct enzyme deficiency causes neuronal apoptosis", isCorrect: false, explanation: "Indirect through metabolites" },
      { id: "c", text: "Increased tyrosine production is toxic", isCorrect: false, explanation: "Tyrosine levels are low" },
      { id: "d", text: "Loss of dopamine synthesis", isCorrect: false, explanation: "Related but not primary toxin" },
    ],
    explanation: "**PKU** results from **phenylalanine hydroxylase deficiency**, preventing conversion of **phenylalanine to tyrosine**. Excess **phenylalanine** accumulates and is converted to **phenylpyruvate** → **phenylacetate** → **phenylacetyl-CoA**, which interferes with **dopamine synthesis** and causes **irreversible intellectual disability**. Early **dietary restriction** to keep phenylalanine <10 mg/dL prevents damage.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Inborn Errors of Amino Acid Metabolism", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-03-TOP-05",
    stem: "A patient with pentose phosphate pathway deficiency develops hemolytic anemia triggered by oxidative stress (G6PD deficiency). Why are RBCs vulnerable?",
    clinicalVignette: "A 25-year-old male with G6PD deficiency develops acute hemolytic anemia after taking sulfonamides. RBCs lack adequate reducing power to neutralize oxidative stress.",
    options: [
      { id: "a", text: "Decreased NADPH production impairs glutathione reduction", isCorrect: true, explanation: "NADPH is essential for maintaining reduced glutathione" },
      { id: "b", text: "Increased glucose-6-phosphate accumulation", isCorrect: false, explanation: "G6P is not toxic" },
      { id: "c", text: "Loss of ATP production", isCorrect: false, explanation: "ATP is still produced" },
      { id: "d", text: "Impaired hemoglobin synthesis", isCorrect: false, explanation: "Hemoglobin synthesis is normal" },
    ],
    explanation: "The **pentose phosphate pathway (HMP shunt)** is the primary source of **NADPH** in RBCs. **NADPH** reduces **oxidized glutathione (GSSG)** back to reduced **glutathione (GSH)**, which neutralizes **hydrogen peroxide** and **free radicals**. **G6PD deficiency** → low **NADPH** → inability to regenerate **GSH** → oxidative damage to RBCs → hemolysis.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Pentose Phosphate Pathway", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-01-TOP-02",
    stem: "A patient with severe malnutrition has very low levels of plasma proteins. Which organ synthesis is primarily impaired?",
    clinicalVignette: "A 50-year-old with protein-energy malnutrition (PEM) has serum albumin <2 g/dL and severe edema. Liver function tests are relatively normal.",
    options: [
      { id: "a", text: "Hepatic protein synthesis impaired by amino acid deficiency", isCorrect: true, explanation: "Liver is primary site of plasma protein synthesis" },
      { id: "b", text: "Renal filtration of plasma proteins", isCorrect: false, explanation: "Would cause proteinuria" },
      { id: "c", text: "Increased plasma protein catabolism", isCorrect: false, explanation: "Some but not primary" },
      { id: "d", text: "Loss of transcription factors", isCorrect: false, explanation: "Transcription factors are intact" },
    ],
    explanation: "The **liver** synthesizes **plasma proteins** (albumin, immunoglobulins, clotting factors, binding proteins). In **protein-energy malnutrition**, **amino acid substrate deficiency** limits **hepatic protein synthesis**. This leads to **hypoproteinemia**, **decreased colloid osmotic pressure**, and **malnutrition edema**.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Protein Synthesis and Nutrition", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-04-TOP-05",
    stem: "A newborn with Gaucher disease accumulates glucocerebroside due to enzyme deficiency. Which lysosomal enzyme is deficient?",
    clinicalVignette: "A 3-month-old with Gaucher disease presents with hepatosplenomegaly and bone involvement. Macrophages are enlarged from glucocerebroside accumulation.",
    options: [
      { id: "a", text: "β-glucosidase (glucocerebrosidase)", isCorrect: true, explanation: "Gaucher = β-glucosidase deficiency" },
      { id: "b", text: "α-galactosidase", isCorrect: false, explanation: "Fabry disease" },
      { id: "c", text: "Sphingomyelinase", isCorrect: false, explanation: "Niemann-Pick disease" },
      { id: "d", text: "Galactocerebrosidase", isCorrect: false, explanation: "Krabbe disease" },
    ],
    explanation: "**Gaucher disease** is caused by **β-glucosidase (glucocerebrosidase) deficiency**, preventing hydrolysis of **glucocerebroside**. This leads to **accumulation in macrophages** (Gaucher cells), causing **hepatosplenomegaly, anemia, and bone involvement**. It's the most common lysosomal storage disorder.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Lipid Storage Diseases", edition: "7th" }],
  },

  // ============ EXPERT (5 questions) ============
  // Complex Analysis and ProblemSolving
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-06-TOP-01",
    stem: "A patient with xeroderma pigmentosum (XP) cannot repair UV-induced DNA damage. Which repair mechanism is defective?",
    clinicalVignette: "A 10-year-old child with XP develops multiple skin cancers from minimal sun exposure. Normal cells repair UV damage; XP cells cannot.",
    options: [
      { id: "a", text: "Base excision repair (BER)", isCorrect: false, explanation: "BER handles oxidative damage" },
      { id: "b", text: "Nucleotide excision repair (NER)", isCorrect: true, explanation: "XP is NER deficiency" },
      { id: "c", text: "Mismatch repair (MMR)", isCorrect: false, explanation: "MMR handles replication errors" },
      { id: "d", text: "Homologous recombination", isCorrect: false, explanation: "HR handles double-strand breaks" },
    ],
    explanation: "**Xeroderma pigmentosum** results from **nucleotide excision repair (NER) deficiency**. NER removes **bulky DNA lesions** like UV-induced **thymine dimers**. Without NER, UV damage accumulates, leading to **uncontrolled mutations** and **aggressive skin cancers** even with minimal sun exposure.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "DNA Repair Mechanisms", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-07-TOP-01",
    stem: "A patient develops type 2 diabetes with insulin resistance. What is the molecular basis of impaired insulin signaling?",
    clinicalVignette: "A 55-year-old obese male with type 2 diabetes shows normal insulin levels but elevated glucose. Insulin receptor signaling is impaired despite normal receptor number.",
    options: [
      { id: "a", text: "Loss of insulin receptor expression", isCorrect: false, explanation: "Receptors are present" },
      { id: "b", text: "Impaired IRS-1 (insulin receptor substrate) phosphorylation and PI3K activation", isCorrect: true, explanation: "Downstream signaling defect in IR2" },
      { id: "c", text: "Increased insulin degradation", isCorrect: false, explanation: "Insulin levels are high" },
      { id: "d", text: "Loss of GLUT4 transporters", isCorrect: false, explanation: "GLUT4 function is impaired but expression remains" },
    ],
    explanation: "In **type 2 diabetes**, **insulin receptor signaling** is impaired through multiple mechanisms: **reduced IRS-1 phosphorylation**, **decreased PI3K activation**, **impaired GLUT4 translocation**, and **increased inflammatory cytokines** (TNFα, IL-6) that suppress **insulin signaling proteins**. This occurs despite normal or elevated insulin levels, defining **insulin resistance**.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Insulin Signaling and Metabolism", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-03-TOP-02",
    stem: "A patient with septic shock develops metabolic acidosis with elevated lactate despite adequate oxygenation. What metabolic shift occurs?",
    clinicalVignette: "A 65-year-old with sepsis has persistent lactate >4 mmoL/L and metabolic acidosis despite aggressive oxygen therapy and fluid resuscitation. The organ failure is evident.",
    options: [
      { id: "a", text: "Shift from oxidative phosphorylation to glycolysis due to mitochondrial dysfunction", isCorrect: true, explanation: "Sepsis causes mitochondrial impairment" },
      { id: "b", text: "Hypoxic lactic acidosis from hypoperfusion", isCorrect: false, explanation: "Oxygenation is adequate" },
      { id: "c", text: "Increased pyruvate carboxylase activity", isCorrect: false, explanation: "Would consume lactate" },
      { id: "d", text: "Decreased lactate dehydrogenase activity", isCorrect: false, explanation: "Activity is normal or increased" },
    ],
    explanation: "In **septic shock**, despite **adequate oxygen delivery**, **mitochondrial dysfunction** (from inflammatory mediators, ROS) shifts cells toward **anaerobic glycolysis** even with oxygen available. This produces excessive **lactate** faster than it can be cleared, causing **type B lactate acidosis** — a marker of severe sepsis and poor prognosis.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Metabolic Adaptation to Sepsis", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-02-TOP-02",
    stem: "A patient with acute promyelocytic leukemia (APL) responds dramatically to all-trans retinoic acid (ATRA). What is the molecular mechanism?",
    clinicalVignette: "A 35-year-old with APL t(15;17) translocation has abnormal retinoic acid receptor (RAR) fusion protein. ATRA treatment leads to complete remission through epigenetic remodeling.",
    options: [
      { id: "a", text: "ATRA binds abnormal RAR-PML fusion protein, recruiting coactivators and allowing differentiation", isCorrect: true, explanation: "ATRA restores transcription" },
      { id: "b", text: "Direct cytotoxic effect on leukemic cells", isCorrect: false, explanation: "Mechanism is differentiation" },
      { id: "c", text: "Immune system activation", isCorrect: false, explanation: "Direct molecular mechanism" },
      { id: "d", text: "Inhibition of telomerase", isCorrect: false, explanation: "Not the mechanism" },
    ],
    explanation: "In **APL**, the **t(15;17) translocation** fuses **PML gene** with **retinoic acid receptor (RAR)**. The **PML-RAR fusion** recruits **corepressors** and blocks differentiation. **ATRA** binds the fusion protein, recruiting **coactivators** and **histone acetyltransferases**, leading to **chromatin remodeling**, **gene reactivation**, and **leukemic cell differentiation** — a paradigm of targeted molecular therapy.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Retinoic Acid Signaling", edition: "7th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "BI-MOD-05-TOP-03",
    stem: "A patient with homocystinuria due to cystathionine β-synthase (CBS) deficiency develops thrombosis and neuropsychiatric disease. Why is homocysteine accumulation toxic?",
    clinicalVignette: "A 25-year-old with untreated CBS deficiency has elevated homocysteine >100 μmol/L, thrombosis, lens dislocation, and psychiatric symptoms.",
    options: [
      { id: "a", text: "Homocysteine promotes oxidative stress and endothelial dysfunction", isCorrect: true, explanation: "Homocysteine is prothrombotic and neurotoxic" },
      { id: "b", text: "Direct inhibition of vitamin B12 function", isCorrect: false, explanation: "B12 is not directly inhibited" },
      { id: "c", text: "Accumulation in brain causing neuronal toxicity", isCorrect: false, explanation: "Related but not primary mechanism" },
      { id: "d", text: "Loss of methionine synthesis", isCorrect: false, explanation: "Methionine is synthesized normally" },
    ],
    explanation: "**Elevated homocysteine** (>15 μmol/L is abnormal) causes **endothelial dysfunction**, **oxidative stress**, **platelet activation**, and **thrombosis**. It also causes **neuropsychiatric symptoms** through **N-methyl-D-aspartate (NMDA) receptor overstimulation** and **neurotoxicity**. **CBS deficiency** → **homocystinuria** → **thrombosis, lens dislocation, intellectual disability** (classic triad). **Vitamin B6** supplementation and **dietary methionine restriction** are therapeutic.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Lehninger Principles of Biochemistry", chapter: "Homocysteine Metabolism", edition: "7th" }],
  },
];
