// Cross-Subject MCQs 3 - Advanced/Integration MCQs
// 30 MCQs: Dermatology (6), Psychiatry (6), Orthopedics (6), Anesthesiology (6), Radiology (6)

export const crossSubjectMcqs3 = [
  // DERMATOLOGY (6) - Drug reactions, leprosy, STIs
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 42-year-old on antiretroviral therapy (nevirapine) develops a diffuse maculopapular rash with facial edema, fever, and elevated liver enzymes. Which drug reaction is this?",
    clinicalVignette: "42-year-old HIV+ patient 2 weeks post-initiation of nevirapine develops maculopapular rash (face, trunk), facial edema, fever (39°C), AST 280, ALT 320.",
    options: [
      { id: "a", text: "Drug reaction with eosinophilia and systemic symptoms (DRESS) — nevirapine-induced hypersensitivity syndrome", isCorrect: true, explanation: "Nevirapine DRESS: Delayed hypersensitivity (days-weeks after initiation) with rash, facial edema, fever, hepatitis, and eosinophilia. Rash progresses from maculopapular to atypical lymphocytosis. Life-threatening if not discontinued." },
      { id: "b", text: "Acute urticaria from drug allergy", isCorrect: false, explanation: "Urticaria lacks systemic features; DRESS has fever, hepatitis, etc." },
      { id: "c", text: "Stevens-Johnson syndrome (SJS) — mucosal involvement required", isCorrect: false, explanation: "SJS has mucous membrane involvement, not just facial edema" },
      { id: "d", text: "Morbilliform rash from acute toxicity", isCorrect: false, explanation: "While morbilliform, the systemic features (hepatitis, fever, eosinophilia) define DRESS, not simple toxicity" },
    ],
    explanation: "**Nevirapine-induced DRESS**: Delayed hypersensitivity syndrome with rash, facial edema, fever, hepatitis (elevated transaminases). Discontinue immediately; can progress to fulminant hepatic failure.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "DR",
    topicCode: "DR-MOD-04-TOP-05",
    textbookRefs: [{ book: "Rook's Textbook of Dermatology", chapter: "Drug Reactions - Ch 17", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old with lepromatous leprosy on rifampicin monotherapy for 6 months develops painful nodules and fever. What is this immunologic phenomenon?",
    clinicalVignette: "35-year-old with lepromatous leprosy on rifampicin monotherapy for 6 months develops tender nodules, fever (38.5°C), and arthritis. Peripheral blood shows elevated WBC.",
    options: [
      { id: "a", text: "Erythema nodosum leprosum (ENL) — Type III (immune complex) hypersensitivity from antigen-antibody immune complex deposition", isCorrect: true, explanation: "Erythema nodosum leprosum (ENL/Type 2 reaction): Occurs in lepromatous/borderline lepromatous leprosy (high bacillary load). Immune complexes deposit in tissues → vasculitis, nodules, fever, neuritis, ocular involvement." },
      { id: "b", text: "Type 1 lepra reaction (reversal reaction) from impaired cell-mediated immunity", isCorrect: false, explanation: "Type 1 occurs with treatment in borderline forms; ENL occurs in lepromatous forms" },
      { id: "c", text: "Tuberculoid leprosy transformation", isCorrect: false, explanation: "Leprosy type doesn't transform in this manner; ENL is immune complex phenomenon" },
      { id: "d", text: "Secondary infection with mycobacterial superinfection", isCorrect: false, explanation: "ENL is immunologic, not from secondary infection" },
    ],
    explanation: "**Erythema nodosum leprosum (ENL/Type 2 reaction)**: Immune complex vasculitis in lepromatous leprosy. Occurs during/after treatment when immune system mobilizes. Treat with NSAIDs or thalidomide.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "DR",
    topicCode: "DR-MOD-02-TOP-04",
    textbookRefs: [{ book: "Rook's Textbook of Dermatology", chapter: "Leprosy - Ch 35", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old sexually active female presents with multiple painful vesicles on the vulva and severe dysuria. PCR confirms HSV-2. Which complication should be anticipated in pregnancy?",
    clinicalVignette: "28-year-old with primary HSV-2 (confirmed by PCR), severe vulvar pain, dysuria, fever (38.2°C). Now 8 weeks pregnant (unaware at initial presentation).",
    options: [
      { id: "a", text: "Neonatal herpes simplex if vaginal delivery during primary HSV-2 infection (risk ~30-50%)", isCorrect: true, explanation: "Primary HSV-2 in pregnancy: High viral shedding and absent maternal antibodies → 30-50% neonatal transmission risk with vaginal delivery → neonatal herpes (disseminated disease, CNS, keratitis, death if untreated)." },
      { id: "b", text: "Spontaneous abortion from teratogenic HSV-2 effects", isCorrect: false, explanation: "HSV-2 is not teratogenic; transmission risk is primarily neonatal" },
      { id: "c", text: "Congenital varicella syndrome from HSV cross-reactivity", isCorrect: false, explanation: "Varicella and HSV are distinct; VZV causes congenital syndrome, not HSV-2" },
      { id: "d", text: "Maternal disseminated disease with hepatitis only", isCorrect: false, explanation: "While maternal hepatitis can occur, neonatal infection is the primary concern" },
    ],
    explanation: "**Primary HSV-2 in pregnancy**: High maternal viral load and absent IgG antibodies → 30-50% neonatal transmission with vaginal delivery → severe neonatal herpes. Recommend cesare sections.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "DR",
    topicCode: "DR-MOD-03-TOP-02",
    textbookRefs: [{ book: "Rook's Textbook of Dermatology", chapter: "Viral Infections - Ch 25", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 45-year-old with syphilis (secondary stage) presents with maculopapular rash on trunk and palms, lymphadenopathy, and condylomata lata. Which test best diagnoses this stage?",
    clinicalVignette: "45-year-old male with rash (palms included), generalized lymphadenopathy, fever, and moist nodular lesions in groin. RPR/VDRL positive with high titer (1:32).",
    options: [
      { id: "a", text: "Non-treponemal test (RPR/VDRL) with high titer (>1:16) — indicates active secondary syphilis", isCorrect: true, explanation: "Secondary syphilis: High titer non-treponemal antibodies (RPR >1:16) with positive FTA-ABS/TP-PA. Rash on palms/soles is pathognomonic. Titer correlates with disease activity." },
      { id: "b", text: "Treponemal test (FTA-ABS) alone — confirms diagnosis", isCorrect: false, explanation: "FTA-ABS confirms treponemal exposure but doesn't assess activity; high-titer RPR indicates secondary stage" },
      { id: "c", text: "Darkfield microscopy of rash exudate", isCorrect: false, explanation: "While darkfield can identify spirochetes, serologic testing is standard for secondary syphilis diagnosis" },
      { id: "d", text: "CSF VDRL and FTA-ABS to exclude neurosyphilis", isCorrect: false, explanation: "CSF testing is for neurosyphilis; this is clinical secondary syphilis" },
    ],
    explanation: "**Secondary syphilis diagnosis**: High-titer RPR/VDRL (>1:16) with positive FTA-ABS/TP-PA. Rash on trunk/palms, lymphadenopathy, condylomata lata are clinical hallmarks.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "DR",
    topicCode: "DR-MOD-03-TOP-04",
    textbookRefs: [{ book: "Rook's Textbook of Dermatology", chapter: "Syphilis - Ch 27", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 22-year-old with severe acne is started on isotretinoin. Which adverse effect requires MANDATORY monthly pregnancy tests and dual contraception?",
    clinicalVignette: "22-year-old female with severe nodular acne started on isotretinoin. Counseled about teratogenicity. Enrolled in iPLEDGE program.",
    options: [
      { id: "a", text: "Teratogenicity — isotretinoin causes severe craniofacial, cardiac, thymic, CNS anomalies (20-25% risk)", isCorrect: true, explanation: "Isotretinoin (13-cis-retinoic acid): Highly teratogenic with 20-25% congenital abnormality risk. Absolute contraindication in pregnancy. Female patients require iPLEDGE registration, dual contraception, monthly pregnancy tests." },
      { id: "b", text: "Hepatotoxicity requiring liver function monitoring", isCorrect: false, explanation: "Hepatotoxicity occurs but is not the reason for pregnancy testing" },
      { id: "c", text: "Hyperlipidemia requiring lipid panel monitoring", isCorrect: false, explanation: "Lipid elevation is common but not the teratogenic risk" },
      { id: "d", text: "Photosensitivity requiring strict sun protection alone", isCorrect: false, explanation: "While photosensitivity occurs, teratogenicity is the critical concern" },
    ],
    explanation: "**Isotretinoin teratogenicity**: 20-25% risk of congenital anomalies (craniofacial, cardiac, thymic, CNS). Absolute contraindication in pregnancy. Requires iPLEDGE, dual contraception, monthly pregnancy tests.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "DR",
    topicCode: "DR-MOD-04-TOP-03",
    textbookRefs: [{ book: "Rook's Textbook of Dermatology", chapter: "Acne - Ch 40", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 55-year-old with chronic eczema develops generalized pustular lesions and fever. Culture from pustules reveals Staphylococcus aureus. Which phenomenon explains the acute flare?",
    clinicalVignette: "55-year-old with chronic atopic dermatitis develops sudden onset of pustules and fever (39°C) during mild atopic flare. S. aureus MRSA isolated from pustular fluid.",
    options: [
      { id: "a", text: "Eczema herpeticum-like secondary bacterial infection with exotoxin production (Panton-Valentine leukocidin from S. aureus)", isCorrect: true, explanation: "Atopic dermatitis patients have impaired innate immunity (low antimicrobial peptides, defective TLR) → susceptibility to S. aureus superinfection. Exotoxins (PVL, α-toxin) → acute pustulation and systemic symptoms." },
      { id: "b", text: "Direct HSV-1 infection with bacterial superinfection", isCorrect: false, explanation: "While eczema herpeticum is HSV, this is bacterial (S. aureus) exotoxin-mediated" },
      { id: "c", text: "Contact dermatitis to antibiotic ointments", isCorrect: false, explanation: "The pustulation is from S. aureus exotoxin, not contact dermatitis" },
      { id: "d", text: "Autoimmune exacerbation independent of infection", isCorrect: false, explanation: "The bacterial exotoxin is the trigger for acute pustulation" },
    ],
    explanation: "**Eczema with S. aureus superinfection**: Atopic dermatitis impaired innate immunity → S. aureus colonization/infection. Panton-Valentine leukocidin (PVL) and other exotoxins → acute pustulation.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "DR",
    topicCode: "DR-MOD-01-TOP-04",
    textbookRefs: [{ book: "Rook's Textbook of Dermatology", chapter: "Atopic Eczema - Ch 4", edition: "9th" }],
  },

  // PSYCHIATRY (6) - Psychopharmacology & substance abuse
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old on fluoxetine (SSRI) for depression suddenly discontinues the medication after 6 weeks. Within 48 hours, develops dizziness, brain zaps, and nausea. Which phenomenon is this?",
    clinicalVignette: "35-year-old on fluoxetine 20mg for 6 weeks suddenly stops medication. Within 48 hours: dizziness, electric shock sensations in head, nausea, anxiety, insomnia.",
    options: [
      { id: "a", text: "Selective serotonin reuptake inhibitor (SSRI) discontinuation syndrome — abrupt serotonin depletion from blocked reuptake suddenly reversing", isCorrect: true, explanation: "SSRI discontinuation syndrome: Abrupt SSRI cessation → sudden loss of serotonin reuptake block → serotonin depletion. Brain zaps (paresthesias), dizziness, nausea, anxiety, insomnia within 48 hours. Risk highest with shorter-acting SSRIs (paroxetine, fluoxetine less than fluoxetine with longer half-life)." },
      { id: "b", text: "Major depressive episode recurrence", isCorrect: false, explanation: "Depression recurrence takes days-weeks; discontinuation syndrome is within 48 hours" },
      { id: "c", text: "Serotonin syndrome from drug interaction", isCorrect: false, explanation: "Serotonin syndrome requires concurrent serotonergic drugs; this is withdrawal" },
      { id: "d", text: "Unrelated viral infection causing systemic symptoms", isCorrect: false, explanation: "The temporal relationship to SSRI cessation makes discontinuation syndrome diagnosis clear" },
    ],
    explanation: "**SSRI discontinuation syndrome**: Abrupt cessation → serotonin depletion → brain zaps, dizziness, nausea, anxiety. Prevent by slow tapering (25% reduction every 1-2 weeks).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "PS",
    topicCode: "PS-MOD-02-TOP-04",
    textbookRefs: [{ book: "Kaplan & Sadock's Psychiatry", chapter: "Psychopharmacology - Ch 31", edition: "12th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 28-year-old with bipolar disorder on lithium therapy develops tremor, confusion, and polyuria (4L/day). Serum lithium level is 1.8 mEq/L (therapeutic 0.6-1.2). What is this state?",
    clinicalVignette: "28-year-old with bipolar I disorder on lithium (maintained on 900mg daily for 2 years) develops tremor, confusion, polyuria (4L), and increased thirst. Lithium level 1.8 mEq/L.",
    options: [
      { id: "a", text: "Lithium toxicity (mild) with nephrogenic diabetes insipidus from lithium-induced ADH resistance", isCorrect: true, explanation: "Lithium toxicity at level 1.8: Fine tremor, confusion (mild toxicity). Chronic lithium → nephrogenic DI (ADH resistance in collecting duct) → polyuria/polydipsia. Requires discontinuation and fluid/electrolyte management." },
      { id: "b", text: "Therapeutic lithium effect with normal tolerance", isCorrect: false, explanation: "Level 1.8 exceeds therapeutic range (0.6-1.2); toxicity is present" },
      { id: "c", text: "Serotonin syndrome from concurrent SSRI use", isCorrect: false, explanation: "Serotonin syndrome doesn't cause lithium toxicity signs" },
      { id: "d", text: "Acute psychotic exacerbation requiring dose increase", isCorrect: false, explanation: "Confusion is from toxicity, not psychosis; dose should be DECREASED" },
    ],
    explanation: "**Lithium toxicity**: Levels >1.5 mEq/L → tremor, confusion, ataxia. Chronic toxicity → nephrogenic DI. Requires discontinuation and supportive care.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "PS",
    topicCode: "PS-MOD-03-TOP-02",
    textbookRefs: [{ book: "Kaplan & Sadock's Psychiatry", chapter: "Mood Disorders - Ch 6", edition: "12th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 42-year-old with alcohol use disorder undergoes rapid alcohol cessation for medical reasons. 24 hours later develops autonomic hyperactivity (HR 120, BP 155/95), anxiety, and tremor. What is the pathophysiology?",
    clinicalVignette: "42-year-old with heavy daily alcohol use (1 liter/day for 10 years) undergoes sudden cessation. 24 hours later: tachycardia, hypertension, tremor, severe anxiety, diaphoresis.",
    options: [
      { id: "a", text: "Alcohol withdrawal syndrome from loss of GABA-enhancing effect → CNS hyperexcitability", isCorrect: true, explanation: "Alcohol withdrawal: Chronic alcohol enhances GABA inhibition. Acute cessation → loss of GABAergic tone → unopposed glutamate excitation → autonomic hyperactivity, tremor, anxiety. Without treatment, progresses to seizures (6-48h) and delirium tremens." },
      { id: "b", text: "Hepatic encephalopathy from underlying liver disease", isCorrect: false, explanation: "While liver disease is common, the acute presentation is alcohol withdrawal, not encephalopathy" },
      { id: "c", text: "Sepsis from aspiration pneumonia", isCorrect: false, explanation: "Sepsis doesn't cause this specific timing and presentation" },
      { id: "d", text: "Thyroid storm from underlying hyperthyroidism", isCorrect: false, explanation: "Thyroid storm is distinct and would show different metabolic signs" },
    ],
    explanation: "**Alcohol withdrawal syndrome**: Chronic alcohol → GABA enhancement. Acute cessation → GABA tone loss → CNS hyperexcitability. Autonomic hyperactivity, tremor, anxiety within 6-24 hours. Treat with benzodiazepines.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "PS",
    topicCode: "PS-MOD-04-TOP-02",
    textbookRefs: [{ book: "Kaplan & Sadock's Psychiatry", chapter: "Substance-Related Disorders - Ch 20", edition: "12th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 19-year-old with recent onset schizophrenia is started on risperidone. After 2 weeks, develops galactorrhea, amenorrhea, and sexual dysfunction. Which mechanism explains these side effects?",
    clinicalVignette: "19-year-old female with first-episode psychosis on risperidone 4mg daily develops galactorrhea, missed period, and decreased libido.",
    options: [
      { id: "a", text: "D2 dopamine receptor blockade in tuberoinfundibular pathway → increased prolactin (hyperprolactinemia)", isCorrect: true, explanation: "Antipsychotics block D2 receptors in tuberoinfundibular pathway → remove dopamine's inhibition of prolactin → prolactin ↑ → galactorrhea, amenorrhea, sexual dysfunction. Risperidone has high D2 affinity → hyperprolactinemia more than aripiprazole (partial agonist)." },
      { id: "b", text: "Direct thyrotropin-releasing hormone (TRH) stimulation", isCorrect: false, explanation: "Antipsychotics don't stimulate TRH" },
      { id: "c", text: "Estrogen depletion from gonadal suppression", isCorrect: false, explanation: "The mechanism is prolactin ↑, not direct gonadal suppression" },
      { id: "d", text: "Serotonin syndrome from off-target 5HT2A blockade", isCorrect: false, explanation: "5HT2A blockade is not the mechanism; D2 blockade is" },
    ],
    explanation: "**Antipsychotic-induced hyperprolactinemia**: D2 blockade in tuberoinfundibular pathway → loss of prolactin inhibition → galactorrhea, amenorrhea, sexual dysfunction. Higher risk with risperidone vs aripiprazole.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "PS",
    topicCode: "PS-MOD-01-TOP-05",
    textbookRefs: [{ book: "Kaplan & Sadock's Psychiatry", chapter: "Schizophrenia - Ch 2", edition: "12th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 32-year-old with alcohol use disorder develops cognitive impairment (memory loss, confabulation) and ataxia. Which vitamin deficiency is responsible?",
    clinicalVignette: "32-year-old with 15-year alcohol dependence develops memory loss (cannot remember recent events), confabulation, and gait ataxia. MRI shows mammillary body atrophy.",
    options: [
      { id: "a", text: "Thiamine (Vitamin B1) deficiency → Wernicke-Korsakoff syndrome with mammillary body degeneration", isCorrect: true, explanation: "Alcohol use → thiamine malabsorption and impaired phosphorylation → neuronal damage in mammillary bodies, medial thalamus → Wernicke (acute: ataxia, ophthalmoplegia, confusion) and Korsakoff (chronic: anterograde amnesia, confabulation)." },
      { id: "b", text: "Niacin (B3) deficiency causing pellagra-related dementia", isCorrect: false, explanation: "Pellagra causes dermatitis and dementia but not the mammillary body findings" },
      { id: "c", text: "Cobalamin (B12) deficiency with subacute combined degeneration", isCorrect: false, explanation: "B12 deficiency affects spinal cord more than mammillary bodies" },
      { id: "d", text: "Pyridoxine (B6) deficiency causing seizures and neuropathy", isCorrect: false, explanation: "B6 deficiency presents differently; thiamine is the alcohol-related deficiency" },
    ],
    explanation: "**Wernicke-Korsakoff syndrome**: Thiamine deficiency from alcohol → mammillary body degeneration. Wernicke acute phase (ataxia, ophthalmoplegia, confusion); Korsakoff chronic (anterograde amnesia, confabulation).",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "PS",
    topicCode: "PS-MOD-04-TOP-04",
    textbookRefs: [{ book: "Kaplan & Sadock's Psychiatry", chapter: "Substance-Related Disorders - Ch 20", edition: "12th" }],
  },

  // ORTHOPEDICS (6) - Fracture management & bone tumors
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 22-year-old with a comminuted tibial shaft fracture develops pain out of proportion to clinical findings within 6 hours of injury. Which complication should be immediately evaluated?",
    clinicalVignette: "22-year-old with tibia fracture (motor vehicle accident) develops severe pain (10/10), tense compartments, paresthesias, and cool foot. Injury only 6 hours old.",
    options: [
      { id: "a", text: "Compartment syndrome — increased pressure in closed fascial compartment impairs microcirculation → tissue necrosis", isCorrect: true, explanation: "Compartment syndrome: Post-traumatic edema/hemorrhage → pressure ↑ in closed compartment → capillary perfusion drops below venous pressure → tissue ischemia → myonecrosis. Pain out of proportion is cardinal sign. Urgent fasciotomy needed within 6-8 hours." },
      { id: "b", text: "Rhabdomyolysis from crush injury", isCorrect: false, explanation: "While rhabdo can occur, compartment syndrome is the acute surgical emergency" },
      { id: "c", text: "Deep vein thrombosis from immobilization", isCorrect: false, explanation: "DVT develops over hours-days; compartment syndrome is immediate" },
      { id: "d", text: "Fat embolism from marrow exposure", isCorrect: false, explanation: "Fat embolism develops later (12-72 hours)" },
    ],
    explanation: "**Compartment syndrome**: Pain out of proportion is pathognomonic sign. Requires urgent fasciotomy within 6-8 hours to prevent permanent muscle necrosis and contracture.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "OR",
    topicCode: "OR-MOD-06-TOP-03",
    textbookRefs: [{ book: "Rockwood & Green's Fractures in Adults", chapter: "Tibia & Fibula - Ch 45", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 68-year-old woman with osteoporosis (T-score -3.2) sustains a simple fall and develops hip pain. X-ray is initially normal. Which imaging is most sensitive for femoral neck fracture?",
    clinicalVignette: "68-year-old post-menopausal woman falls at home. Hip pain and inability to bear weight. X-ray of pelvis/hip appears normal. High suspicion for occult fracture.",
    options: [
      { id: "a", text: "MRI (STIR sequence) — most sensitive for occult bone marrow edema in femoral neck stress fractures", isCorrect: true, explanation: "Occult femoral neck fracture: X-ray often normal initially (especially stress fractures in osteoporosis). MRI (STIR, T2) shows bone marrow edema and fracture line. CT and bone scan also sensitive but MRI is gold standard." },
      { id: "b", text: "Plain radiographs with special views (45° and 90° flexion)", isCorrect: false, explanation: "While special views help, MRI is more sensitive" },
      { id: "c", text: "CT scan with 3D reconstruction", isCorrect: false, explanation: "CT is sensitive but MRI is gold standard for marrow edema" },
      { id: "d", text: "Bone scan with technetium-99m", isCorrect: false, explanation: "Bone scan takes 24-48 hours to show uptake; MRI is immediate" },
    ],
    explanation: "**Occult femoral neck fracture**: X-ray may be normal. MRI (STIR sequence) shows bone marrow edema → most sensitive. Early diagnosis prevents complications (AVN, nonunion).",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "OR",
    topicCode: "OR-MOD-02-TOP-04",
    textbookRefs: [{ book: "Rockwood & Green's Fractures in Adults", chapter: "Hip - Ch 42", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 45-year-old presents with bone pain (femur, tibia, pelvis), elevated alkaline phosphatase, and elevated bone turnover markers. X-ray shows areas of increased bone density with jigsaw-puzzle appearance. What is the diagnosis?",
    clinicalVignette: "45-year-old with bone pain in multiple sites, elevated ALP (250 U/L), elevated P1NP (bone formation marker), and X-ray showing mixed lytic/sclerotic lesions with pagetic appearance.",
    options: [
      { id: "a", text: "Paget's disease of bone — abnormal osteoclast activity → increased bone turnover → mixed sclerotic/lytic lesions", isCorrect: true, explanation: "Paget disease: Hyperactive osteoclasts → excessive bone resorption, followed by disorganized osteoblast activity → bizarre bone architecture with 'jigsaw puzzle' pattern. Elevated ALP and bone turnover markers. Risk of pathologic fracture and sarcomatous transformation (1-3%)." },
      { id: "b", text: "Hyperparathyroidism with osteitis fibrosa cystica", isCorrect: false, explanation: "Osteitis fibrosa shows 'brown tumor' lesions, not jigsaw-puzzle pattern" },
      { id: "c", text: "Multiple myeloma with osteolytic lesions", isCorrect: false, explanation: "Myeloma shows lytic lesions; Paget is mixed" },
      { id: "d", text: "Metastatic bone disease with mixed response", isCorrect: false, explanation: "Paget has characteristic jigsaw pattern and specific enzyme elevation" },
    ],
    explanation: "**Paget's disease of bone**: Abnormal osteoclast activity → hypercellular bone → jigsaw-puzzle pattern on X-ray. Elevated ALP and bone turnover markers. Complications: fracture, deformity, cardiac high-output failure, sarcoma.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "OR",
    topicCode: "OR-MOD-04-TOP-02",
    textbookRefs: [{ book: "Campbell's Operative Orthopaedics", chapter: "Metabolic Bone Disease - Ch 12", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old with osteosarcoma of the distal femur is staged and found to have pulmonary metastases. Which combination therapy offers the best survival?",
    clinicalVignette: "35-year-old with osteosarcoma (distal femur) presenting with chest pain. CT chest shows bilateral pulmonary nodules (metastases).",
    options: [
      { id: "a", text: "Neoadjuvant chemotherapy (doxorubicin, cisplatin, high-dose methotrexate) → surgical resection → adjuvant chemotherapy", isCorrect: true, explanation: "Osteosarcoma management: Neoadjuvant chemo (doxo, cisplatin, MTX) to downstage tumor, then wide surgical resection of primary + metastasectomy if feasible. Adjuvant chemo completes therapy. 5-year survival ~65-70% with metastases initially." },
      { id: "b", text: "Primary surgical resection followed by radiation therapy alone", isCorrect: false, explanation: "Surgery alone without neoadjuvant chemo has worse outcomes" },
      { id: "c", text: "Palliative chemotherapy only (no surgery)", isCorrect: false, explanation: "Chemotherapy + surgery offers better survival than chemo alone" },
      { id: "d", text: "Radiation therapy to primary + pulmonary lesions", isCorrect: false, explanation: "Chemotherapy and surgery are mainstays; radiation is adjunctive" },
    ],
    explanation: "**Osteosarcoma with metastases**: Neoadjuvant chemotherapy → surgical resection (primary + metastasectomy) → adjuvant chemotherapy. Improves 5-year survival to ~65-70%.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "OR",
    topicCode: "OR-MOD-05-TOP-03",
    textbookRefs: [{ book: "Campbell's Operative Orthopaedics", chapter: "Bone Tumors - Ch 28", edition: "13th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 62-year-old with severe knee osteoarthritis and failed conservative management is evaluated for total knee arthroplasty. Which radiographic finding indicates bone-on-bone contact and severity?",
    clinicalVignette: "62-year-old with chronic knee pain, swelling, and mechanical symptoms. X-ray shows narrowed joint space and osteophytes. Considering TKA.",
    options: [
      { id: "a", text: "Kellgren-Lawrence Grade IV (bone-on-bone contact) — indicates severe OA with loss of cartilage and subchondral bone changes", isCorrect: true, explanation: "Kellgren-Lawrence grading: Grade IV shows bone-on-bone contact (complete joint space loss), osteophytes, and sclerosis. Indicates severe OA warranting TKA consideration if symptoms severe." },
      { id: "b", text: "Grade II (minimal joint space narrowing) — early OA", isCorrect: false, explanation: "Grade II is early; Grade IV indicates severe disease" },
      { id: "c", text: "Grade III (moderate narrowing) — indicates TKA decision", isCorrect: false, explanation: "Grade III is moderate; Grade IV is required for TKA in most cases" },
      { id: "d", text: "Presence of joint effusion alone — indicates need for TKA", isCorrect: false, explanation: "Effusion can occur in any grade; bone-on-bone is the severity indicator" },
    ],
    explanation: "**Kellgren-Lawrence Grade IV (severe OA)**: Bone-on-bone contact with complete cartilage loss, osteophytes, sclerosis. Indicates severe disease warranting TKA if patient symptomatic.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "OR",
    topicCode: "OR-MOD-03-TOP-02",
    textbookRefs: [{ book: "Campbell's Operative Orthopaedics", chapter: "Knee Arthroplasty - Ch 66", edition: "13th" }],
  },

  // ANESTHESIOLOGY (6) - Preop assessment & emergencies
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 68-year-old with chronic hypertension and unstable angina is scheduled for urgent hip fracture repair. Which cardiovascular parameter has highest predictive value for perioperative cardiac complications?",
    clinicalVignette: "68-year-old with recurrent angina (last episode 2 weeks ago), hypertension (BP 165/95), scheduled for urgent ORIF hip fracture. Considering perioperative cardiac risk.",
    options: [
      { id: "a", text: "Revised Cardiac Risk Index (RCRI) score incorporating clinical predictors: age, functional status, cardiac history, surgery type", isCorrect: true, explanation: "RCRI predicts perioperative cardiac events better than individual parameters. Score 0-1: low risk (<1%), 2: intermediate (1-2%), ≥3: high (>3-5%). Incorporates age, HTN, CAD, diabetes, renal insufficiency, high-risk surgery." },
      { id: "b", text: "Resting heart rate alone", isCorrect: false, explanation: "HR is not specific; RCRI is more predictive" },
      { id: "c", text: "Presence of systolic hypertension on preop exam", isCorrect: false, explanation: "While HTN is risk factor, RCRI score is more comprehensive" },
      { id: "d", text: "Age >65 years alone", isCorrect: false, explanation: "Age is one factor; RCRI combines multiple parameters" },
    ],
    explanation: "**Revised Cardiac Risk Index (RCRI)**: Predictive tool for perioperative cardiac events (MI, unstable angina, cardiac death). Incorporates age, cardiac history, surgery type, and functional status.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "AS",
    topicCode: "AS-MOD-01-TOP-02",
    textbookRefs: [{ book: "Miller's Anesthesia", chapter: "Preoperative Evaluation - Ch 10", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "During general anesthesia induction in a 45-year-old, the patient develops jaw rigidity, elevated temperature (38.5°C), dark urine, and myoglobinuria. Which pharmacogenetic mutation is responsible?",
    clinicalVignette: "Intraoperative: 45-year-old develops jaw tightness, masseter muscle rigidity, body temperature 38.5°C, dark cola-colored urine, rising CK (3500 U/L).",
    options: [
      { id: "a", text: "Ryanodine receptor (RYR1) or calcium channel mutations → malignant hyperthermia with uncontrolled calcium release", isCorrect: true, explanation: "Malignant hyperthermia: Succinylcholine/volatile anesthetics trigger RYR1/CACNA1S mutations → uncontrolled intracellular Ca2+ release → sustained muscle contraction → hyperthermia, myoglobinuria, hyperkalemia, DIC, death if untreated." },
      { id: "b", text: "Pseudocholinesterase deficiency (butyrylcholinesterase) → prolonged succinylcholine action", isCorrect: false, explanation: "Pseudocholinesterase causes prolonged paralysis, not hyperthermia" },
      { id: "c", text: "Malignant neuroleptic syndrome from anesthetic interaction", isCorrect: false, explanation: "NMS is from antipsychotics, not anesthetics" },
      { id: "d", text: "Thyroid storm from undiagnosed hyperthyroidism", isCorrect: false, explanation: "Thyroid storm is distinct and slower onset" },
    ],
    explanation: "**Malignant hyperthermia**: RYR1/CACNA1S mutations + succinylcholine/volatiles → uncontrolled Ca2+ release → sustained contraction → hyperthermia, myoglobinuria, hyperkalemia. Treat with dantrolene immediately.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "AS",
    topicCode: "AS-MOD-03-TOP-05",
    textbookRefs: [{ book: "Miller's Anesthesia", chapter: "Adverse Events - Ch 31", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 55-year-old on chronic beta-blocker therapy for hypertension requires emergent surgery. Which induction agent should be avoided?",
    clinicalVignette: "55-year-old on metoprolol (50mg daily) for 5 years, requires urgent abdominal surgery. Considering induction agents for general anesthesia.",
    options: [
      { id: "a", text: "Propofol — causes myocardial depression and vasodilation → severe hypotension with unopposed sympathetic withdrawal in beta-blocked patients", isCorrect: true, explanation: "Propofol + beta-blockers: Propofol depresses myocardium and causes vasodilation. Beta-blockers remove compensatory sympathetic response → profound hypotension. Prefer etomidate or ketamine (maintain SVR)." },
      { id: "b", text: "Etomidate — minimal cardiac effects", isCorrect: false, explanation: "Etomidate is safer in beta-blocked patients (preserves catecholamine response)" },
      { id: "c", text: "Ketamine — maintains cardiovascular stability", isCorrect: false, explanation: "Ketamine preserves sympathetic tone, preferred in beta-blocked patients" },
      { id: "d", text: "Succinylcholine — paralytic agent unaffected by beta-blockers", isCorrect: false, explanation: "Succinylcholine is muscle relaxant; the concern is induction agent" },
    ],
    explanation: "**Propofol in beta-blocked patients**: Myocardial depression + vasodilation + loss of sympathetic compensation → severe hypotension. Use etomidate or ketamine instead.",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "AS",
    topicCode: "AS-MOD-02-TOP-03",
    textbookRefs: [{ book: "Miller's Anesthesia", chapter: "Intravenous Agents - Ch 9", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 62-year-old with COPD and asthma requiring emergency intubation for respiratory failure. Which induction agent is contraindicated?",
    clinicalVignette: "62-year-old with GOLD Stage 4 COPD + asthma, respiratory failure (pCO2 65), requiring emergent intubation. Selecting induction agent.",
    options: [
      { id: "a", text: "Atracurium or mivacurium — release histamine → bronchoconstriction in asthmatic patients", isCorrect: true, explanation: "Atracurium/mivacurium release histamine → bronchoconstriction, hypotension. Contraindicated in COPD/asthma. Use rocuronium (non-histamine releasing) for paralysis. Induction: avoid propofol (↓airways reflexes); use etomidate or ketamine." },
      { id: "b", text: "Succinylcholine — short-acting acetylcholine agonist", isCorrect: false, explanation: "Succinylcholine is quick-onset but can cause hyperkalemia" },
      { id: "c", text: "Rocuronium — steroidal, non-histamine releasing", isCorrect: false, explanation: "Rocuronium is safe in asthma/COPD" },
      { id: "d", text: "Cisatracurium — benzylisoquinolinium agent", isCorrect: false, explanation: "Cisatracurium is non-histamine releasing (unlike atracurium)" },
    ],
    explanation: "**Atracurium/mivacurium in COPD/asthma**: Histamine release → bronchoconstriction. Use rocuronium (non-histamine) and avoid histamine-releasing agents in reactive airway disease.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "AS",
    topicCode: "AS-MOD-02-TOP-04",
    textbookRefs: [{ book: "Miller's Anesthesia", chapter: "Neuromuscular Blockers - Ch 11", edition: "9th" }],
  },

  // RADIOLOGY (6) - Imaging findings & modality selection
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 45-year-old with recent MI and chest pain has persistent troponin elevation but ejection fraction 55% on echo. Which imaging modality would best identify myocardial infarction with preserved ejection fraction?",
    clinicalVignette: "45-year-old post-MI with elevated troponin for 5 days, but EF 55% on echo. Concerned about non-ST elevation MI (NSTEMI) with preserved function.",
    options: [
      { id: "a", text: "Cardiac MRI with late gadolinium enhancement (LGE) — shows transmural fibrosis/scarring from infarction", isCorrect: true, explanation: "Cardiac MRI (LGE): Gold standard for detecting myocardial infarction regardless of size or function. Shows transmural enhancement pattern (scarring) from necrosis. Sensitivity >90% for MI detection." },
      { id: "b", text: "Transthoracic echocardiography alone", isCorrect: false, explanation: "Echo evaluates function but may miss small infarcts or wall motion abnormalities" },
      { id: "c", text: "Coronary angiography for vessel visualization", isCorrect: false, explanation: "Angio shows stenosis/occlusion but not myocardial damage directly" },
      { id: "d", text: "Stress testing to assess functional ischemia", isCorrect: false, explanation: "Stress testing is risky post-MI and doesn't identify infarction zone" },
    ],
    explanation: "**Cardiac MRI for MI detection**: LGE protocol shows transmural fibrosis pattern diagnostic of myocardial infarction, regardless of ejection fraction. Gold standard sensitivity.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-02-TOP-03",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Cardiac Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 72-year-old with acute flank pain and hypotension has CT showing abdominal aortic aneurysm (AAA) 6.5 cm with no rupture on imaging. What is the immediate management?",
    clinicalVignette: "72-year-old with sudden flank pain, hypotension (BP 95/60). CT: AAA 6.5 cm with contained rupture (contrast pooling near aorta but no free intraperitoneal fluid).",
    options: [
      { id: "a", text: "Immediate vascular surgery evaluation for emergency repair — contained rupture is imminent threat", isCorrect: true, explanation: "AAA 6.5 cm with imaging signs of rupture (contained hematomata, contrast extravasation) = surgical emergency. Mortality without repair ~50%; with surgery ~10%. Requires immediate OR." },
      { id: "b", text: "Medical management with beta-blockers and antihypertensives to control BP", isCorrect: false, explanation: "Medical management is only for asymptomatic AAA <5.5 cm" },
      { id: "c", text: "Observation with serial CT imaging every 3 months", isCorrect: false, explanation: "Contained rupture requires urgent surgery, not observation" },
      { id: "d", text: "Endovascular stent-graft placement as first-line if anatomy suitable", isCorrect: false, explanation: "Emergency open repair is preferred over EVAR in rupture scenarios" },
    ],
    explanation: "**AAA rupture/contained rupture**: Surgical emergency. 6.5 cm with imaging evidence of rupture requires immediate OR. Medical management inappropriate for ruptured AAA.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-03-TOP-04",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Vascular Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 58-year-old with pulmonary embolism (PE) has a contraindication to anticoagulation. Which imaging modality is used to assess for inferior vena cava (IVC) filter placement?",
    clinicalVignette: "58-year-old with acute PE but active bleeding from GI ulcer (cannot use anticoagulation). Requires IVC filter to prevent recurrent PE.",
    options: [
      { id: "a", text: "Duplex ultrasound or CT venography to measure IVC size and confirm patency above/below renal veins", isCorrect: true, explanation: "IVC filter placement requires imaging to confirm IVC diameter (<28 mm optimal), confirm thrombus above/below renal veins, and establish anatomic suitability. CT venography or duplex ultrasound are modalities of choice." },
      { id: "b", text: "Chest X-ray alone to assess cardiac silhouette", isCorrect: false, explanation: "CXR doesn't visualize IVC adequately" },
      { id: "c", text: "D-dimer level to assess thrombus burden", isCorrect: false, explanation: "D-dimer is a marker, not an imaging modality" },
      { id: "d", text: "Ventilation-perfusion (V/Q) scan to assess perfusion defects", isCorrect: false, explanation: "V/Q scan diagnoses PE; it doesn't assess IVC anatomy" },
    ],
    explanation: "**IVC filter imaging**: CT venography or duplex ultrasound needed to assess IVC diameter, anatomy, and confirm suitability for filter placement.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-03-TOP-02",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Vascular Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 52-year-old with jaundice and weight loss has abdominal ultrasound showing dilated intrahepatic bile ducts (>10 mm) and normal common bile duct. Which diagnosis should be excluded first with MRCP?",
    clinicalVignette: "52-year-old smoker with painless jaundice, weight loss. Ultrasound: dilated IHD, normal CBD. MRCP pending to rule out malignancy.",
    options: [
      { id: "a", text: "Klatskin tumor (cholangiocarcinoma at hepatic duct confluence) — causes selective left/right hepatic duct obstruction", isCorrect: true, explanation: "Klatskin tumor: Isoechoic mass at hepatic hilum causes selective hepatic duct dilation with normal CBD. MRCP visualizes stricture pattern ('double stricture' sign). High-risk: smoking, PSC." },
      { id: "b", text: "Gallstone obstruction from choledocholithiasis", isCorrect: false, explanation: "Stones would dilate CBD, not spare it" },
      { id: "c", text: "Hepatitis with ductal dilation only", isCorrect: false, explanation: "Hepatitis causes less selective obstruction pattern" },
      { id: "d", text: "Benign stricture from previous biliary injury", isCorrect: false, explanation: "While benign stricture is possible, malignancy (Klatskin) is most important to exclude" },
    ],
    explanation: "**Klatskin tumor (hepatic duct cholangiocarcinoma)**: Selective hepatic duct obstruction with normal CBD. MRCP shows stricture at duct confluence. Risk factors: smoking, PSC.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-01-TOP-05",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Biliary Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old with sudden-onset dyspnea has chest X-ray showing a white-out of the right hemithorax and tracheal deviation to the left. Which diagnosis is most likely?",
    clinicalVignette: "35-year-old with sudden severe dyspnea, hemodynamic instability. CXR: complete white-out right lung, mediastinal shift to left, no hemidiaphragm visualization.",
    options: [
      { id: "a", text: "Tension pneumothorax or massive pleural effusion/hemothorax — mediastinal shift indicates pressure effect compressing left lung", isCorrect: true, explanation: "White-out hemithorax + contralateral mediastinal shift = massive pneumothorax (under pressure), hemothorax, or effusion. Tension physiology requires emergent decompression/intervention." },
      { id: "b", text: "Lobar consolidation from pneumonia", isCorrect: false, explanation: "Consolidation doesn't cause complete white-out or mediastinal shift at this degree" },
      { id: "c", text: "Atelectasis from airway obstruction", isCorrect: false, explanation: "Atelectasis is localized; this is massive" },
      { id: "d", text: "Pulmonary edema with unilateral distribution", isCorrect: false, explanation: "Edema typically bilateral; this is unilateral with shift" },
    ],
    explanation: "**Tension pneumothorax/massive effusion**: White-out hemithorax with contralateral mediastinal shift indicates life-threatening pressure physiology. Requires urgent decompression.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-02-TOP-01",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Thoracic Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 68-year-old with dementia and fall presents with acute focal neurologic deficit. CT head shows a lens-shaped hyperdensity not crossing the midline. Which injury is this?",
    clinicalVignette: "68-year-old with dementia, fall, acute confusion and right-sided weakness. CT: lens-shaped (biconvex) hyperdensity in left temporal region.",
    options: [
      { id: "a", text: "Epidural hematoma — bleeding between dura and skull from torn meningeal artery, does not cross sutures (lens-shaped)", isCorrect: true, explanation: "Epidural hematoma: Between dura and skull, does not cross sutures (restricted by dural attachments) → lens-shaped (biconvex) appearance. Acute: hyperdense on CT. Common in middle meningeal artery laceration." },
      { id: "b", text: "Subdural hematoma — between dura and brain, crosses sutures", isCorrect: false, explanation: "Subdural crosses sutures/dural attachments → crescent shape, not lens" },
      { id: "c", text: "Subarachnoid hemorrhage (SAH) in basal cisterns", isCorrect: false, explanation: "SAH distributes in basal cisterns, not lens-shaped collection" },
      { id: "d", text: "Acute ischemic stroke with hyperdensity artifact", isCorrect: false, explanation: "Acute stroke is hypodense, not hyperdense" },
    ],
    explanation: "**Epidural hematoma**: Lens-shaped hyperdensity between dura and skull, doesn't cross sutures. From meningeal artery laceration. Neurosurgical emergency.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-04-TOP-02",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Neuroradiology", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 48-year-old with hypertension presents with acute flank pain. CT angiography shows dissection of the renal artery with 50% narrowing. Which imaging feature suggests acute dissection?",
    clinicalVignette: "48-year-old with HTN and acute flank pain. CT angiography: renal artery with intimal flap and true/false lumen visualization.",
    options: [
      { id: "a", text: "Intimal flap separating true and false lumens — pathognomonic for arterial dissection", isCorrect: true, explanation: "Arterial dissection: Intimal tear → dissection plane between media and intima/adventitia → true lumen (continues into distal vessel) and false lumen (often thrombosed). Intimal flap visible on CT/MRI." },
      { id: "b", text: "Eccentric atherosclerotic plaque with ulceration", isCorrect: false, explanation: "Atherosclerosis shows plaque, not intimal flap" },
      { id: "c", text: "Smooth tapering of vessel without filling defect", isCorrect: false, explanation: "Tapered stenosis is typical of atherosclerosis, not dissection" },
      { id: "d", text: "Concentric calcification of vessel wall", isCorrect: false, explanation: "Calcification suggests chronic disease, not acute dissection" },
    ],
    explanation: "**Arterial dissection imaging**: Intimal flap separating true and false lumens. True lumen continues distally; false lumen often thrombosed. Pathognomonic sign on CT/MRI.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-03-TOP-03",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Vascular Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 62-year-old with back pain has MRI of the lumbar spine showing decreased signal intensity on T2-weighted images in the L4-L5 disc. What does this indicate?",
    clinicalVignette: "62-year-old with chronic back pain, limited flexibility. MRI L-spine: L4-L5 disc dark on T2 (low signal), T1 normal. No acute findings.",
    options: [
      { id: "a", text: "Disc degeneration with loss of water content (desiccation) — low T2 signal indicates reduced disc hydration", isCorrect: true, explanation: "Disc desiccation: Loss of water content from degeneration → decreased T2 signal (T2 weighted images detect water/fluids). Low T2 signal = 'black disc' = degenerate disc. Common in degenerative disc disease." },
      { id: "b", text: "Acute disc herniation with protrusion", isCorrect: false, explanation: "Acute herniation would show normal/high T2 signal" },
      { id: "c", text: "Spinal cord ischemia", isCorrect: false, explanation: "Cord ischemia affects cord, not disc specifically" },
      { id: "d", text: "Infection (discitis) from abscess formation", isCorrect: false, explanation: "Discitis shows high T2 signal (edema), not low" },
    ],
    explanation: "**Disc desiccation (degenerative disc disease)**: Low T2 signal ('black disc') indicates loss of disc water content. Associated with chronic back pain and degenerative changes.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-05-TOP-01",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Musculoskeletal Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 45-year-old with polymyalgia rheumatica develops sudden vision loss and temporal headache. Which imaging finding would be most consistent with giant cell (temporal) arteritis?",
    clinicalVignette: "45-year-old with polymyalgia rheumatica now develops left temporal headache, jaw claudication, and sudden loss of vision (amaurosis fugax).",
    options: [
      { id: "a", text: "Temporal artery biopsy showing granulomatous inflammation with giant cells — confirms GCA diagnosis", isCorrect: true, explanation: "Giant cell (temporal) arteritis: Granulomatous vasculitis of medium/large vessels. Biopsy shows granulomas, giant cells, intimal thickening, and patchy transmural inflammation. PMR precedes GCA in 15-20%." },
      { id: "b", text: "MRI brain showing territorial infarction", isCorrect: false, explanation: "While infarction can occur, biopsy diagnosis is definitive" },
      { id: "c", text: "Carotid ultrasound showing >50% stenosis", isCorrect: false, explanation: "Ultrasound may show vessel changes but biopsy is gold standard" },
      { id: "d", text: "PET scan showing increased glucose uptake in large arteries", isCorrect: false, explanation: "PET shows inflammation but biopsy confirms diagnosis" },
    ],
    explanation: "**GCA diagnosis**: Temporal artery biopsy (within 1 week of diagnosis) showing granulomatous inflammation with giant cells. Start high-dose corticosteroids immediately (don't wait for biopsy).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-06-TOP-02",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Vascular Imaging", edition: "5th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    stem: "A 35-year-old with Marfan syndrome undergoes preoperative screening for aortic root dilation. Which imaging modality is preferred for measuring aortic root diameter and assessing for dissection risk?",
    clinicalVignette: "35-year-old with Marfan syndrome and family history of aortic dissection. Requires preoperative clearance. Need aortic root measurement and assessment of fibrillin defects.",
    options: [
      { id: "a", text: "Transthoracic echocardiography (TTE) to measure aortic root diameter at sinuses of Valsalva", isCorrect: true, explanation: "Aortic root assessment in Marfan: TTE measures aortic root diameter (sinuses of Valsalva) and assesses valve function. If >5.0 cm or family dissection history, prophylactic repair indicated. TTE is cost-effective and non-invasive." },
      { id: "b", text: "Chest X-ray for cardiomediastinal silhouette", isCorrect: false, explanation: "CXR is insensitive for aortic root measurement" },
      { id: "c", text: "CT angiography for definitive diagnosis", isCorrect: false, explanation: "CT is accurate but unnecessary for routine screening; TTE is first-line" },
      { id: "d", text: "Cardiac MRI for tissue characterization", isCorrect: false, explanation: "MRI is complementary but TTE is preferred for serial monitoring" },
    ],
    explanation: "**Marfan syndrome aortic assessment**: TTE measures aortic root diameter at sinuses of Valsalva. Prophylactic repair if >5.0 cm or family dissection history.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as const[],
    subjectCode: "RD",
    topicCode: "RD-MOD-02-TOP-04",
    textbookRefs: [{ book: "Taverna's Radiology Review", chapter: "Cardiac Imaging", edition: "5th" }],
  },
];
