// ENT MCQs - NEXT pattern (40 questions)
// Distribution: 10 EASY (mostly Recall), 15 MEDIUM (ProblemSolving), 10 HARD (Analysis), 5 EXPERT
// Pattern: 60% ProblemSolving, 30% Analysis, 10% Recall

export const entFullMcqs = [
  // ============ EASY (10 questions) - Recall dominant ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-01-TOP-01",
    stem: "The blood supply to the vocal cords is primarily from:",
    options: [
      { id: "a", text: "Anterior laryngeal artery only", isCorrect: false, explanation: "Anterior laryngeal supplies anterior vocal cords; not sole supply" },
      { id: "b", text: "Superior thyroid artery only", isCorrect: false, explanation: "Superior laryngeal artery (branch of STA) supplies vocal cords, but not only source" },
      { id: "c", text: "Superior and inferior laryngeal arteries", isCorrect: true, explanation: "Superior laryngeal artery (above vocal cords) and inferior laryngeal artery (below) supply true vocal cords" },
      { id: "d", text: "Lingual artery", isCorrect: false, explanation: "Lingual artery supplies tongue, not vocal cords" },
    ],
    explanation: "The vocal cords receive dual blood supply: superior laryngeal artery (from superior thyroid) above, and inferior laryngeal artery (from inferior thyroid) below. This dual supply explains why complete vocal cord ischemia is rare.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG", "NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "5", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-02-TOP-01",
    stem: "Sudden unilateral conductive hearing loss with normal tympanic membrane suggests:",
    options: [
      { id: "a", text: "Cerumen impaction", isCorrect: false, explanation: "Cerumen impaction visible on otoscopy; TM normal but canal obstructed" },
      { id: "b", text: "Serous otitis media", isCorrect: false, explanation: "Serous otitis media shows TM retraction, level of fluid; not normal TM" },
      { id: "c", text: "Ossicular discontinuity", isCorrect: true, explanation: "Ossicular chain disruption (malleus handle fracture, incus erosion) presents with sudden CHL and normal TM appearance on otoscopy" },
      { id: "d", text: "Outer ear canal cholesteatoma", isCorrect: false, explanation: "Cholesteatoma usually shows abnormal TM perforation or retraction pocket" },
    ],
    explanation: "Normal tympanic membrane with conductive hearing loss = ossicular chain problem. Ossicular discontinuity from trauma (temporal bone fracture) or pathology (ossicular erosion from infection) is key differential.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG", "NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "4", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-03-TOP-02",
    stem: "Nasal polyps with asthma and NSAID sensitivity (Samter's triad) are associated with:",
    options: [
      { id: "a", text: "IgE-mediated allergy", isCorrect: false, explanation: "IgE allergy involves mast cells; Samter's is arachidonic acid metabolism abnormality" },
      { id: "b", text: "Leukotrienes and COX-1 pathway abnormality", isCorrect: true, explanation: "Samter's: NSAID blocking COX-1 → shunting to 5-LO pathway → leukotriene increase → symptoms" },
      { id: "c", text: "Staphylococcal superantigen", isCorrect: false, explanation: "Superantigen may contribute to eosinophilic disease but not primary Samter's" },
      { id: "d", text: "Ciliary dysfunction", isCorrect: false, explanation: "Ciliary dysfunction seen in PCD/Kartag syndrome, not Samter's" },
    ],
    explanation: "Samter's triad (aspirin exacerbated respiratory disease): NSAID-induced release of leukotrienes via COX-1 inhibition → arachidonic acid shunted to 5-lipoxygenase. Avoid NSAIDs; aspirin desensitization sometimes used.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "8", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-04-TOP-01",
    stem: "Acute mastoiditis with purulent discharge from postauricular area indicates:",
    options: [
      { id: "a", text: "Acute otitis media alone (AOM)", isCorrect: false, explanation: "AOM confined to middle ear; mastoid bone involvement = acute mastoiditis" },
      { id: "b", text: "Mastoid osteitis with cortical erosion", isCorrect: true, explanation: "Purulent postauricular swelling/discharge = mastoid cortical bone erosion; pus tracking through cortex to skin" },
      { id: "c", text: "Simple subperiosteal abscess (no bone erosion)", isCorrect: false, explanation: "Subperiosteal abscess implies cortical erosion has already occurred" },
      { id: "d", text: "Serous mastoiditis only", isCorrect: false, explanation: "Serous mastoiditis shows fluid without purulent discharge" },
    ],
    explanation: "Postauricular discharge/swelling in mastoiditis = cortical bone erosion. This is NOT simple AOM anymore; bone-invasive infection requiring imaging (CT mastoids) and likely mastoidectomy.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "3", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-05-TOP-02",
    stem: "Pharyngeal pouch (Zenker diverticulum) location is in:",
    options: [
      { id: "a", text: "Pharyngeal constrictor muscle (Killian triangle)", isCorrect: true, explanation: "Killian triangle = space between inferior pharyngeal constrictor and thyropharyngeus; most common site (90%)" },
      { id: "b", text: "Tracheoesophageal groove", isCorrect: false, explanation: "This is location for esophageal diverticula, not Zenker" },
      { id: "c", text: "Lateral pharyngeal wall", isCorrect: false, explanation: "Lateral wall not typical Zenker location" },
      { id: "d", text: "Anterior to epiglottis", isCorrect: false, explanation: "Not the typical pharyngeal pouch location" },
    ],
    explanation: "Pharyngeal pouch (Zenker diverticulum) occurs at Killian triangle (weak point between inferior pharyngeal constrictor above and cricopharyngeus below). Typically presents with dysphagia, halitosis, regurgitation of undigested food.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "11", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-06-TOP-01",
    stem: "The recurrent laryngeal nerve has a longer course on which side?",
    options: [
      { id: "a", text: "Right side (longer RLN path)", isCorrect: false, explanation: "Right RLN shorter (loops under right subclavian artery)" },
      { id: "b", text: "Left side (loops under aorta)", isCorrect: true, explanation: "Left RLN loops under aortic arch; longer course than right which loops under subclavian" },
      { id: "c", text: "Bilateral equal length", isCorrect: false, explanation: "RLN courses differ between sides" },
      { id: "d", text: "Variable (unpredictable)", isCorrect: false, explanation: "RLN anatomy consistent; left typically longer" },
    ],
    explanation: "Left RLN loops under aortic arch → longer course → longer nerve. Right RLN loops under right subclavian artery → shorter course. Left RLN at higher risk from aortic pathology, left lung pathology.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "5", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-01-TOP-02",
    stem: "Weber test shows lateralization to the affected ear in:",
    options: [
      { id: "a", text: "Sensorineural hearing loss (SNHL)", isCorrect: false, explanation: "Weber lateralizes to NORMAL ear in SNHL" },
      { id: "b", text: "Conductive hearing loss (CHL)", isCorrect: true, explanation: "Weber lateralizes to AFFECTED ear in CHL (vibrations travel through bone to intact ossicles)" },
      { id: "c", text: "Sudden SNHL", isCorrect: false, explanation: "Sudden SNHL still shows Weber lateralizing to normal side" },
      { id: "d", text: "Mixed hearing loss", isCorrect: false, explanation: "Mixed HL depends on whether conductive or sensorineural component predominates" },
    ],
    explanation: "Weber (bone conduction tuning fork on midline): **Conductive loss → lateralizes to affected (bad) ear**; **SNHL → lateralizes to normal (better) ear**. This is because CHL actually helps bone conduction reach the ossicular chain.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG", "NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "2", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-04-TOP-02",
    stem: "Oval window of the inner ear is connected to:",
    options: [
      { id: "a", text: "Incus", isCorrect: false, explanation: "Incus connects to stapes (not directly to oval window, but stapes is)" },
      { id: "b", text: "Stapes footplate", isCorrect: true, explanation: "Stapes footplate sits in oval window membrane (fenestra vestibuli); transmits vibrations to perilymph" },
      { id: "c", text: "Round window", isCorrect: false, explanation: "Round window is separate, inferior fenestra" },
      { id: "d", text: "Tensor tympani muscle", isCorrect: false, explanation: "Tensor tympani attaches to malleus handle, not oval window" },
    ],
    explanation: "Ossicular chain: malleus → incus → stapes footplate in oval window. Stapes transmits vibrations to perilymph via oval window. Round window (fenestra cochleae) below allows fluid escape.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "1", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-02-TOP-02",
    stem: "Most common cause of sensorineural hearing loss in children in India:",
    options: [
      { id: "a", text: "Congenital CMV infection", isCorrect: false, explanation: "CMV important cause but trachoma corneal scarring more common in India specifically for overall blindness" },
      { id: "b", text: "Congenital rubella syndrome", isCorrect: false, explanation: "Rubella is cause but less prevalent in vaccinated areas" },
      { id: "c", text: "Ototoxic medications (aminoglycosides)", isCorrect: true, explanation: "Ototoxicity from aminoglycoside use in India (TB treatment, neonatal sepsis) is major preventable cause of pediatric SNHL" },
      { id: "d", text: "Nonsyndromic congenital SNHL", isCorrect: false, explanation: "While common globally, ototoxicity more preventable/actionable in India context" },
    ],
    explanation: "In India, aminoglycoside ototoxicity from TB treatment (streptomycin, gentamicin) in pregnant women or in neonates causes significant preventable SNHL in children. Genetic counseling and family screening also important for nonsyndromic causes.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "2", edition: "9th" }],
  },

  // ============ MEDIUM (15 questions) - ProblemSolving dominant ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-01-TOP-03",
    stem: "27-year-old with sudden SNHL OD and vertigo. Audiometry shows profound SNHL 4000-8000 Hz worst (peak at 6000 Hz). Weber lateralizes to normal ear. Most likely diagnosis:",
    options: [
      { id: "a", text: "Sudden sensorineural hearing loss (SSNHL)", isCorrect: true, explanation: "SSNHL classic: sudden HL, audiometric peak (dip) pattern variable, can have vertigo in viral etiology; Weber to normal ear confirms SNHL" },
      { id: "b", text: "Acoustic neuroma", isCorrect: false, explanation: "Neuroma gradual; audiometry shows sloping HL, not peak pattern; vertigo less likely unless large" },
      { id: "c", text: "Noise-induced HL", isCorrect: false, explanation: "Noise HL gradual; notch at 3000-6000 Hz; no vertigo" },
      { id: "d", text: "Perilymphatic fistula", isCorrect: false, explanation: "Fistula presents with fluctuating HL + severe vertigo; audiometry less distinctive" },
    ],
    explanation: "SSNHL: viral labyrinthitis or viral endolymphatic hydrops. Audiometric peak (dip) at 4-6 kHz is characteristic. Sudden onset + SNHL + vertigo = SSNHL. Urgent audiometry, imaging (MRI IAC to rule out neuroma), and treatment (steroids, antivirals debated).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG", "NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "4", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-02-TOP-03",
    stem: "12-year-old with recurrent acute otitis media (≥4 times/year), small tympanic membrane perforations, mild CHL. Tympanometry shows Type A. Most likely diagnosis and management:",
    options: [
      { id: "a", text: "Secretory otitis media; grommet insertion", isCorrect: false, explanation: "SOM would show Type B tympanogram (flat); Type A suggests normal compliance" },
      { id: "b", text: "Recurrent AOM with ossicular erosion; ossiculoplasty", isCorrect: false, explanation: "Ossicular erosion would show worse CHL; Type A TM compliance normal argues against" },
      { id: "c", text: "Recurrent AOM from eustachian tube dysfunction; adenoidectomy ± grommet consideration", isCorrect: true, explanation: "Normal Type A tympanogram despite CHL suggests ossicular problem is post-infection (scarring/stiffness from repeated infection). Adenoidectomy addresses ETD. CHL mild suggests ossicles intact but stiffened." },
      { id: "d", text: "Cholesteatoma; mastoidectomy", isCorrect: false, explanation: "Cholesteatoma would show TM abnormality (perforation pattern), not just small perforations" },
    ],
    explanation: "Recurrent AOM + CHL + normal Type A tympanogram = ossicular stiffness/scarring from repeated infection, not structural discontinuity. Management: Address ETD (adenoidectomy if adenoid pathology), antimicrobial prophylaxis, grommet if persistent conductive loss.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "3", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-03-TOP-01",
    stem: "45-year-old smoker with 6-week history of nasal obstruction, clear nasal discharge, and headache. CT shows unilateral maxillary sinus opacity with fluid level. Otoscopy normal. Most likely diagnosis:",
    options: [
      { id: "a", text: "Acute maxillary sinusitis from bacterial infection", isCorrect: false, explanation: "Acute sinusitis would show systemic symptoms (fever, facial pain); 6 weeks is not typical acute" },
      { id: "b", text: "Chronic rhinosinusitis with secondary bacterial sinusitis", isCorrect: true, explanation: "6 weeks chronic nasal obstruction → CRS. Unilateral maxillary sinus opacity suggests secondary ABS superimposed on CRS (smoker risk for CRS)" },
      { id: "c", text: "Sinus malignancy (carcinoma)", isCorrect: false, explanation: "Malignancy would show mass, bone destruction; fluid level suggests infection" },
      { id: "d", text: "Silent sinus syndrome", isCorrect: false, explanation: "Silent sinus (chronic negative pressure) causes painless unilateral proptosis, not fluid level" },
    ],
    explanation: "Unilateral maxillary opacity with fluid level = secondary bacterial sinusitis. Chronic nasal obstruction 6 weeks = CRS underlying. Smoking increases CRS risk. Management: Nasal saline, topical corticosteroid, trial antibiotics if systemically unwell; imaging shows fluid drainage may improve.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "8", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-04-TOP-03",
    stem: "8-year-old with conductive hearing loss, recurrent ear infections, and short stature with intellectual disability. Audiometry shows low-frequency CHL (250-500 Hz worst). Diagnosis hint: skeletal dysplasia features present.",
    options: [
      { id: "a", text: "Down syndrome (trisomy 21)", isCorrect: false, explanation: "Down syndrome causes CHL but doesn't cause short stature with specific skeletal dysplasia features" },
      { id: "b", text: "Treacher Collins syndrome (zygoticles hypoplasia)", isCorrect: false, explanation: "Treacher Collins: craniofacial features with ossicular abnormality; not associated with ID" },
      { id: "c", text: "Achondroplasia with otosclerosis-like CHL", isCorrect: false, explanation: "Achondroplasia causes short stature and intellectual disability, but CHL mechanism different" },
      { id: "d", text: "Mucopolysaccharidosis (MPS) with ossicular fixation", isCorrect: true, explanation: "MPS: skeletal dysplasia (short stature, dysostosis multiplex), ID (CNS involvement), CHL from ossicular accumulation/fixation (low-freq HL characteristic)" },
    ],
    explanation: "MPS: multisystem lysosomal storage disease. CHL from accumulated glycosaminoglycans in ossicles → fixation. Short stature (bone dysplasia) + ID (CNS) + low-frequency CHL = MPS classic triad affecting ENT. Audiogram shows conductive pattern.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "2", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-05-TOP-01",
    stem: "68-year-old with 3-month progressive dysphagia (solids > liquids), regurgitation of undigested food, halitosis, normal barium swallow. Most likely diagnosis:",
    options: [
      { id: "a", text: "Esophageal carcinoma", isCorrect: false, explanation: "Carcinoma shows stricture/mass on barium; not normal" },
      { id: "b", text: "Achalasia", isCorrect: false, explanation: "Achalasia shows 'bird's beak' on barium; liquids > solids dysphagia" },
      { id: "c", text: "Pharyngeal pouch (Zenker diverticulum)", isCorrect: true, explanation: "Zenker: dysphagia solids > liquids, regurgitation undigested food, halitosis, normal barium (pouch may not fill) → diagnosis with careful endoscopy or videofluoroscopy" },
      { id: "d", text: "Diffuse esophageal spasm", isCorrect: false, explanation: "Spasm intermittent; normal barium possible but symptom pattern different" },
    ],
    explanation: "Pharyngeal pouch (Zenker diverticulum) at Killian triangle: pathognomonic for dysphagia solids, regurgitation undigested food hours after eating, bad breath. Barium may not fill pouch reliably. Videofluoroscopy or flexible endoscopy for diagnosis.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "11", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-06-TOP-02",
    stem: "Patient with history of hyperthyroidism treated with radioactive iodine now presents with breathy voice, weak cry, and weak cough. Laryngoscopy shows bilateral vocal cord abduction (paramedian position). Most likely nerve involvement:",
    options: [
      { id: "a", text: "Bilateral superior laryngeal nerve (SLN) injury", isCorrect: false, explanation: "SLN injury causes voice fatigue, loss of high pitches; vocal cords remain mobile" },
      { id: "b", text: "Bilateral recurrent laryngeal nerve (RLN) injury", isCorrect: true, explanation: "Bilateral RLN injury: vocal cords fixed in paramedian (abducted) position → breathy voice (incomplete closure), weak cry. RAI thyroid → RLN injury bilateral (vascular injury to both recurrent nerves)" },
      { id: "c", text: "Unilateral RLN injury", isCorrect: false, explanation: "Unilateral RLN: one cord abducted, voice hoarse not breathy" },
      { id: "d", text: "Vagus nerve (CN X) injury", isCorrect: false, explanation: "Vagus injury would show broader findings (pharyngeal, vocal, palatal signs)" },
    ],
    explanation: "Bilateral RLN injury (from RAI thyroid treatment, post-thyroidectomy, or vascular injury): both cords paramedian → inadequate glottic closure → breathy voice, weak cry, weak cough. Emergency: may need tracheostomy if airway compromised. Bilateral abduction position pathognomonic.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "5", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-01-TOP-04",
    stem: "24-year-old woman with chronic otorrhea (purulent discharge 6 months), mild CHL, and normal TM on otoscopy. Discharge culture shows Pseudomonas aeruginosa. Most likely diagnosis:",
    options: [
      { id: "a", text: "Chronic suppurative otitis media (CSOM) with central perforation", isCorrect: false, explanation: "CSOM with central perforation would show TM perforation on otoscopy" },
      { id: "b", text: "Cholesteatoma (attic disease)", isCorrect: false, explanation: "Cholesteatoma often shows marginal perforation or attic retraction" },
      { id: "c", text: "Otitis externa (malignant/necrotizing)", isCorrect: false, explanation: "Malignant OE would show ear canal abnormality (granulation, swelling)" },
      { id: "d", text: "Chronic external auditory canal disease with microperforations of tympanum", isCorrect: true, explanation: "Chronic suppurative disease of external auditory canal (drainage bypassing TM; microperforations not visible) causing TM secondary disease; Pseudomonas common. Mild CHL from TM edema/irritation" },
    ],
    explanation: "Normal-appearing TM with chronic purulent discharge suggests external canal disease extending into middle ear via microperforations. Pseudomonas suggests external canal source (water exposure risk). Otomicroscopy/endoscopy needed to visualize microperforations.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "4", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-02-TOP-04",
    stem: "Newborn screening test (auditory brainstem response) abnormal bilaterally. Follow-up ABR shows asymmetric response (right better than left). MRI shows small left acoustic neuroma. Likely diagnosis:",
    options: [
      { id: "a", text: "Sporadic bilateral acoustic neuromas", isCorrect: false, explanation: "Sporadic AN unilateral; bilateral suggests hereditary syndrome" },
      { id: "b", text: "Neurofibromatosis type 2 (NF2)", isCorrect: true, explanation: "NF2: bilateral acoustic neuromas (pathognomonic). Neonatal screening may detect early. Asymmetric SNHL typical as tumors grow at different rates" },
      { id: "c", text: "Congenital CMV infection", isCorrect: false, explanation: "CMV causes symmetric bilateral SNHL from labyrinthitis; not mass-forming" },
      { id: "d", text: "Nonsyndromic hereditary deafness", isCorrect: false, explanation: "Hereditary deafness congenital; doesn't involve acoustic neuroma" },
    ],
    explanation: "NF2: bilateral acoustic neuromas by age 30 (diagnostic criterion). Early presentation in infancy possible. Asymmetric SNHL as tumors grow differently. Management: surveillance (MRI) for tumor growth, hearing preservation surgery if needed, genetic counseling (autosomal dominant).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "2", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-03-TOP-03",
    stem: "52-year-old with post-nasal drip, chronic cough, and normal laryngeal exam. Flexible nasopharyngoscopy shows isolated adenoid hypertrophy (normal in adults). Most likely diagnosis:",
    options: [
      { id: "a", text: "Adenoiditis (infection)", isCorrect: false, explanation: "Adenoiditis would show inflamed/purulent adenoid tissue" },
      { id: "b", text: "Nasopharyngeal carcinoma masked by adenoid tissue", isCorrect: true, explanation: "Adenoid hypertrophy in adult (unusual) may mask underlying nasopharyngeal malignancy. Biopsy adenoid tissue needed to rule out lymphoma or carcinoma" },
      { id: "c", text: "Eustachian tube obstruction", isCorrect: false, explanation: "ETD would show different nasopharyngeal findings; not isolated adenoid" },
      { id: "d", text: "Primary adenoid hypertrophy (benign)", isCorrect: false, explanation: "Benign adenoid hypertrophy rare in adult (usually atrophies); need to rule out malignancy first" },
    ],
    explanation: "Adult adenoid hypertrophy is UNUSUAL and should prompt biopsy to rule out lymphoma (primary MALT lymphoma) or nasopharyngeal carcinoma. Never assume benign in adults; imaging (CT/MRI) and biopsy essential.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "8", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-04-TOP-04",
    stem: "60-year-old male smoker with unilateral conductive hearing loss, ipsilateral otosclerosis risk factors, and mixed hearing loss pattern on audiometry. Impedance audiometry shows Type As tympanogram (stiffened middle ear system). Diagnosis:",
    options: [
      { id: "a", text: "Otosclerosis", isCorrect: true, explanation: "Otosclerosis: stiffening of stapes footplate → ↓ compliance → Type As tympanogram (normal pressure, reduced compliance). Mixed HL (conductive + SNHL) common. More common in women, but smokers also at risk" },
      { id: "b", text: "Congenital stapes fixation", isCorrect: false, explanation: "Congenital fixation would present in childhood, not age 60" },
      { id: "c", text: "Malleus fixation from trauma", isCorrect: false, explanation: "Trauma fixation would show Type Ad (very stiff); otosclerosis more gradual" },
      { id: "d", text: "Cerumen impaction", isCorrect: false, explanation: "Cerumen wouldn't cause Type As (would show normal stiffness)" },
    ],
    explanation: "Otosclerosis: bone overgrowth around stapes footplate → fixation → conductive HL. Type As (reduced compliance) on tympanometry. Mixed HL (cochlear effect from stapes fixation). Smoking, female gender, family history risk factors.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "4", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-05-TOP-03",
    stem: "35-year-old with severe angular cheilitis (corner of mouth ulceration), angular stomatitis, and associated glossitis. B12 and folate normal. Most likely diagnosis:",
    options: [
      { id: "a", text: "Iron deficiency anemia (Plummer-Vinson syndrome)", isCorrect: true, explanation: "Plummer-Vinson: iron deficiency → angular cheilitis, angular stomatitis, glossitis (sore tongue), esophageal webs. Treatable cause of dysphagia in iron deficiency" },
      { id: "b", text: "Vitamin B12 deficiency alone", isCorrect: false, explanation: "B12 normal; causes different pattern of glossitis (beefy red)" },
      { id: "c", text: "Oral candidiasis", isCorrect: false, explanation: "Oral thrush shows white plaques; angular cheilitis different pattern" },
      { id: "d", text: "Behçet disease", isCorrect: false, explanation: "Behçet's shows aphthous ulcers, not angular cheilitis pattern specifically" },
    ],
    explanation: "Plummer-Vinson: iron deficiency anemia → atrophic glossitis, angular cheilitis (corners), dysphagia (esophageal webs). Screening: iron studies (ferritin, TIBC), treat iron deficiency. Associated esophageal malignancy risk (post-platin radiotherapy for caustic ingestion).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "11", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-06-TOP-03",
    stem: "48-year-old with chronic laryngitis, voice hoarseness 3 months, smokes 20 cigarettes/day, denies throat pain. Laryngoscopy shows bilateral white patches on vocal cords (not candidiasis on culture). Diagnosis and next step:",
    options: [
      { id: "a", text: "Vocal cord nodules; voice rest", isCorrect: false, explanation: "Nodules benign; white patches on laryngoscopy suggest dysplasia/malignancy" },
      { id: "b", text: "Laryngeal leukoplakia; biopsy for dysplasia/malignancy screening", isCorrect: true, explanation: "Laryngeal leukoplakia (white patches not removable) in smoker → high risk dysplasia or squamous carcinoma. Biopsy mandatory to assess for malignancy" },
      { id: "c", text: "Chronic laryngitis from smoking; smoking cessation only", isCorrect: false, explanation: "White patches require biopsy; cannot assume benign inflammation in smoker" },
      { id: "d", text: "Vocal cord paralysis; EMG assessment", isCorrect: false, explanation: "Paralysis would show asymmetric motion; white patches point to dysplasia" },
    ],
    explanation: "Laryngeal leukoplakia (white patches): premalignant. Biopsy essential to assess for dysplasia/carcinoma. Smoking #1 risk factor. Risk transformation to cancer ~5-30% depending on severity of dysplasia (mild < moderate < severe).",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "7", edition: "9th" }],
  },

  // ============ HARD (10 questions) - Analysis dominant ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-01-TOP-05",
    stem: "5-year-old with congenital conductive hearing loss, blue sclera, bone fragility, and lax ligaments. Audiometry shows CHL with normal bone conduction until age-related changes. Genetic diagnosis and mechanism of hearing loss:",
    options: [
      { id: "a", text: "Osteogenesis imperfecta (OI); defective collagen → abnormal ossicular ossification", isCorrect: true, explanation: "OI: collagen defect → abnormal bone formation. Ossicles underdeveloped/malformed. Blue sclera, bone fragility, lax ligaments pathognomonic. CHL congenital from ossicular dysgenesis" },
      { id: "b", text: "Ehlers-Danlos syndrome; connective tissue defect → ossicular malfunction", isCorrect: false, explanation: "EDS causes ligament laxity but not typical CHL pattern; ossicular structure usually normal" },
      { id: "c", text: "Marfan syndrome; fibrillin defect → middle ear dysplasia", isCorrect: false, explanation: "Marfan associated with ectopia lentis, aortic aneurysm; not typical with OI phenotype" },
      { id: "d", text: "Treacher Collins syndrome; bilateral mandibular/middle ear dysplasia", isCorrect: false, explanation: "Treacher Collins: craniofacial features; doesn't present with blue sclera/bone fragility" },
    ],
    explanation: "Osteogenesis imperfecta: autosomal dominant collagen I defect. Type I (mild) common, presents with CHL from ossicular dysgenesis (underdeveloped malformed ossicles). Blue sclera, bone fragility pathognomonic. Genetic counseling, audiologic monitoring, hearing aids often needed.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "2", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-02-TOP-05",
    stem: "Patient with recurrent vertigo episodes (hours duration), fluctuating SNHL, and tinnitus with aural fullness. Audiometry shows low-frequency SNHL that improves between episodes. Electrocochleography shows elevated SP/AP ratio. Diagnosis pathophysiology:",
    options: [
      { id: "a", text: "Benign paroxysmal positional vertigo (BPPV); otolith displacement", isCorrect: false, explanation: "BPPV: vertigo seconds-minutes duration, not fluctuating HL; normal audiometry" },
      { id: "b", text: "Ménière disease; endolymphatic hydrops → excessive endolymph volume", isCorrect: true, explanation: "Ménière: tetrad (vertigo, HL, tinnitus, aural fullness) + fluctuating low-frequency SNHL that recovers between episodes. Electrocochleography (elevated SP/AP) = endolymphatic hydrops diagnostic. Endolymph volume ↑ → cochlear symptoms" },
      { id: "c", text: "Perilymphatic fistula; round window rupture allowing perilymph leak", isCorrect: false, explanation: "PLF sudden HL, not fluctuating; no tinnitus/aural fullness typical" },
      { id: "d", text: "Superior semicircular canal dehiscence (SSCD); bone thinning", isCorrect: false, explanation: "SSCD: vertigo triggered by loud sounds/pressure; CHL common; not typical low-frequency SNHL" },
    ],
    explanation: "Ménière disease: endolymphatic hydrops (excessive endolymph volume) → fluctuating low-frequency SNHL (reversible early, permanent late), vertigo attacks (hours), tinnitus, aural fullness. SP/AP (summating potential/action potential) ratio elevated on electrocochleography = endolymphatic hydrops diagnostic.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "6", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-03-TOP-04",
    stem: "Patient with chronic rhinosinusitis refractory to 3 courses of antibiotics and nasal corticosteroids. CT shows pansinusitis with opacification of all sinuses + ethmoid remodeling. Immunologic workup shows low IgA but normal IgG/IgM. Most likely diagnosis and mechanism:",
    options: [
      { id: "a", text: "Selective IgA deficiency; impaired mucosal immunity → recurrent infections", isCorrect: true, explanation: "Selective IgA deficiency (1:400-700 prevalence): low IgA but normal total Ig. IgA main mucosal antibody → deficiency → recurrent infections, CRS, autoimmune disease risk. Pansinusitis refractory pattern typical" },
      { id: "b", text: "Common variable immunodeficiency (CVID); hypogammaglobulinemia", isCorrect: false, explanation: "CVID: low IgG/IgM too; this patient has normal levels" },
      { id: "c", text: "Primary ciliary dyskinesia; impaired mucociliary clearance", isCorrect: false, explanation: "PCD shows ciliary dysfunction; immunology normal" },
      { id: "d", text: "Allergic fungal sinusitis; fungal colonization + allergic response", isCorrect: false, explanation: "AFS shows allergic mucin; immunology can be normal; pattern less diffuse" },
    ],
    explanation: "Selective IgA deficiency: mucosal immunity impaired (IgA main mucosal antibody). CRS, recurrent otitis media, allergies, autoimmune disease risk. Management: avoid blood products (sensitization risk); antibiotics for infections; monitor for CVID progression.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "8", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-04-TOP-05",
    stem: "Post-viral sudden SNHL patient treated with high-dose corticosteroids shows 30% VA improvement by 2 weeks. Contralateral ear normal. Audiometry shows perilymphatic fistula-like bone-air gap at 2000 Hz post-treatment with air-bone gap closure. Likely mechanism of steroid benefit:",
    options: [
      { id: "a", text: "Anti-inflammatory effect reducing inner ear edema/cochlear swelling", isCorrect: true, explanation: "Steroid mechanism in viral labyrinthitis/cochleitis: reduce inflammation, perilymphatic edema, blood-labyrinth barrier disruption. Early steroid treatment within 2-3 weeks post-viral → partial recovery possible if inflammation not yet fibrotic. Bone-air gap closure suggests ossicular fluid resolution" },
      { id: "b", text: "Regeneration of damaged hair cells", isCorrect: false, explanation: "Hair cell regeneration not steroid-mediated (mammalian cochlea lacks regenerative capacity)" },
      { id: "c", text: "Reestablishment of endolymphatic homeostasis from sodium-potassium pump restoration", isCorrect: false, explanation: "Steroid effect too rapid for ion pump recovery; inflammation reduction more primary" },
      { id: "d", text: "Prevention of further viral replication in inner ear", isCorrect: false, explanation: "Steroids not antiviral; benefit if given early suggests inflammation more than viral damage" },
    ],
    explanation: "Post-viral sudden SNHL: steroid-responsive in first 2-3 weeks (inflammation phase). Mechanism: reduce edema, blood-labyrinth barrier disruption, inflammatory cytokines. Delayed (>3 weeks) = fibrosis established; steroid benefit limited. Bone-air gap closure suggests ossicular chain mobility restoration.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "4", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-05-TOP-04",
    stem: "Patient with dysphagia for solids, 10-pound weight loss over 2 months, normal esophagogastroscopy, but esophageal manometry shows uncoordinated peristalsis with elevated resting LES pressure. Barium swallow shows 'bird's beak' appearance at GE junction. Diagnosis mechanism of dysphagia:",
    options: [
      { id: "a", text: "Achalasia; loss of enteric neurons (Auerbach plexus) → absent relaxation of LES", isCorrect: true, explanation: "Achalasia: idiopathic neuronal loss → loss of inhibitory innervation (NO, VIP) → LES fails to relax. Bird's beak on barium (smooth tapering), elevated LES pressure, uncoordinated peristalsis diagnostic. Dysphagia solids + liquids (unlike Zenker)" },
      { id: "b", text: "GERD; chronic acid exposure → metaplastic tissue change", isCorrect: false, explanation: "GERD shows different manometry; doesn't cause bird's beak or complete obstruction" },
      { id: "c", text: "Esophageal carcinoma; malignant stricture", isCorrect: false, explanation: "Carcinoma would show irregular narrowing, not smooth bird's beak; EGD would visualize mass" },
      { id: "d", text: "Diffuse esophageal spasm; chaotic muscle contractions", isCorrect: false, explanation: "Spasm shows corkscrew appearance on barium; dysphagia intermittent; normal LES pressure" },
    ],
    explanation: "Achalasia: loss of ganglion cells in Auerbach plexus → LES innervation failure. LES cannot relax → functional obstruction. Bird's beak (smooth tapering narrowing) pathognomonic on barium. Treatment: calcium channel blockers, botulinum toxin, or pneumatic dilation.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "11", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-06-TOP-04",
    stem: "Laryngeal paralysis patient with breathy voice and weak cry suddenly develops stridor and dyspnea. Laryngoscopy shows one cord mobile, one fixed in paramedian position. Paradoxical development of airway obstruction with unilateral paralysis suggests:",
    options: [
      { id: "a", text: "Secondary vocal cord paralysis opposite side from tumor growth", isCorrect: true, explanation: "Paramedian-fixed cord (RLN palsy) + mobile cord paradoxically obstructing suggests: tumor growth from lateral (cricoid cartilage area) pushing medial cord inward = bilateral effective obstruction (one from nerve palsy, one from mass effect). Airway emergency" },
      { id: "b", text: "Laryngeal spasm from associated vocal cord dysfunction", isCorrect: false, explanation: "Spasm would show symmetric cord movement initially" },
      { id: "c", text: "Sudden vocal cord swelling from anaphylaxis", isCorrect: false, explanation: "Anaphylactic swelling would show bilateral involvement; history would suggest trigger" },
      { id: "d", text: "Arytenoid dislocation from trauma", isCorrect: false, explanation: "Dislocation would cause fixed cord position but not explain paradoxical obstruction development" },
    ],
    explanation: "Paradoxical bilateral obstruction: one cord fixed paramedian (RLN palsy), opposite cord medial from tumor/mass effect → airway emergency. Requires urgent assessment (imaging to identify mass) and possible airway intervention (tracheostomy) if stridor severe.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "5", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-01-TOP-06",
    stem: "Chronic ear discharge with fever, postauricular swelling, and positive 'fistula test' (pressure on mastoid produces discharge from meatus). CT shows extensive mastoid sclerosis with cortical erosion. Diagnosis and surgical urgency:",
    options: [
      { id: "a", text: "Acute mastoiditis; emergent mastoidectomy to prevent intracranial spread", isCorrect: true, explanation: "Positive fistula test = pathognomonic for mastoid cortical erosion with fistula track. Cortical erosion + fever + postauricular swelling = acute mastoiditis with osteomyelitis. Urgent CT/MRI to assess for intracranial complications (meningitis, abscess, venous sinus thrombosis), then emergent mastoidectomy" },
      { id: "b", text: "Chronic suppurative otitis media; conservative management with antibiotics", isCorrect: false, explanation: "CSOM doesn't typically present with positive fistula test or acute fever" },
      { id: "c", text: "Granulation tissue obstruction of meatal canal; office debridement", isCorrect: false, explanation: "Granulation doesn't explain cortical erosion or positive fistula test" },
      { id: "d", text: "Cholesteatoma with canal wall reconstruction; staged surgery planned", isCorrect: false, explanation: "Cholesteatoma possible but presentation more urgent (cortical erosion suggests aggressive osteomyelitis)" },
    ],
    explanation: "Positive fistula test = mastoid cortical erosion with fistula. Acute mastoiditis with osteomyelitis = surgical emergency to prevent meningitis/brain abscess. Imaging urgently; assess for intracranial complications before OR. Mastoidectomy essential.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "3", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-02-TOP-06",
    stem: "Children with mild recurrent otitis media and structural palatal abnormalities (submucous cleft, cleft palate repair) show persistent ETD after adenoidectomy. Pathophysiology explanation:",
    options: [
      { id: "a", text: "Tensor veli palatini muscle dysfunction from abnormal attachment/innervation → impaired ET opening", isCorrect: true, explanation: "ETD in cleft palate: tensor veli palatini abnormal (wrong attachment, innervation), can't effectively open ET during swallowing. Adenoidectomy doesn't fix muscle dysfunction. Surgical repair (levator veli palatini repositioning) sometimes needed" },
      { id: "b", text: "Residual adenoid tissue regrowth after adenoidectomy", isCorrect: false, explanation: "Regrowth possible but doesn't explain ETD in presence of structural abnormality" },
      { id: "c", text: "Eustachian tube hypoplasia (underdeveloped structure)", isCorrect: false, explanation: "While ET may be hypoplastic in cleft, muscle dysfunction is primary issue" },
      { id: "d", text: "Persistent middle ear effusion from low-frequency sound transmission", isCorrect: false, explanation: "Physiology backward; effusion causes HL, not caused by it" },
    ],
    explanation: "Palatal cleft: tensor veli palatini maldeveloped → cannot functionally open eustachian tube → ETD persists despite adenoidectomy. Treatment: levator veli palatini muscle repositioning surgery, tympanostomy tubes if recurrent otitis.",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "2", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-03-TOP-05",
    stem: "64-year-old with history of SSRX-positive nasal granulomata, upper respiratory symptoms, and pulmonary infiltrates now develops epistaxis from septal perforation. Laboratory: positive c-ANCA, negative p-ANCA. Most likely diagnosis and vascular pathophysiology:",
    options: [
      { id: "a", text: "Granulomatosis with polyangiitis (GPA, formerly Wegener); necrotizing vasculitis", isCorrect: true, explanation: "GPA: c-ANCA (PR3) positive, necrotizing vasculitis of small vessels → granulomatous inflammation in upper/lower respiratory tract. Nasal septum perforation from vasculitis-induced ischemic necrosis. Classic triad: upper (sinusitis, septal perforation), lower (pneumonitis), renal (GN)" },
      { id: "b", text: "Microscopic polyangiitis; necrotizing vasculitis without granulomas", isCorrect: false, explanation: "MPA: p-ANCA (MPO) typically; less upper respiratory involvement" },
      { id: "c", text: "Chronic granulomatous disease; neutrophil oxidase defect", isCorrect: false, explanation: "CGD: genetic immune defect; not ANCA-associated vasculitis" },
      { id: "d", text: "Eosinophilic granulomatosis with polyangiitis (EGPA); eosinophil-mediated", isCorrect: false, explanation: "EGPA: prominent eosinophilia, asthma; usually p-ANCA" },
    ],
    explanation: "GPA (Wegener granulomatosis): c-ANCA+ (PR3), necrotizing small-vessel vasculitis with granulomas. Nasal granulomata → ulceration → septal perforation from ischemic necrosis. Systemic: lung, kidney. Treatment: immunosuppression (corticosteroids + cyclophosphamide).",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "9", edition: "9th" }],
  },

  // ============ EXPERT (5 questions) ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-04-TOP-06",
    stem: "Familial otosclerosis patient with bilateral CHL, normal tympanogram (Type As), but audiometry shows disproportionate low-frequency HL (125-500 Hz much worse than 1000-4000 Hz). Bone conduction normal. Explain the atypical low-frequency pattern:",
    options: [
      { id: "a", text: "Stiffening of stapes footplate reducing compliance equally across frequencies", isCorrect: false, explanation: "Stapes stiffening alone should show relatively flat conductive pattern across frequencies" },
      { id: "b", text: "Combined ossicular ossification (incus long process) + stapes fixation", isCorrect: true, explanation: "Familial otosclerosis: can involve multiple ossicles. Incus long process ossification/stiffening adds mass-loading → worse low-frequency response (mass reactance dominant at low freq). Combined stapes fixation (stiffness) + incus mass = disproportionate low-freq CHL" },
      { id: "c", text: "Cochlear ossification from otosclerotic bone reaching cochlear lumen", isCorrect: false, explanation: "Cochlear involvement would show mixed HL (bone also affected)" },
      { id: "d", text: "Superior semicircular canal dehiscence secondary to otosclerosis", isCorrect: false, explanation: "SSCD would show bone-conduction improvement in low freq, not conductive pattern" },
    ],
    explanation: "Familial otosclerosis: multiple ossicular involvement. Stapes fixation (stiffness parameter) + incus ossification (mass parameter) → frequency-dependent conductive loss (mass worst at low freq, stiffness worst at high freq; combined creates valley at mid-freq, lower at low-freq).",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Booth", chapter: "4", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-05-TOP-05",
    stem: "Laryngeal papillomatosis (recurrent respiratory papillomatosis, RRP) patient with bilateral papillomas at anterior commissure now develops incomplete vocal cord paralysis with breathy voice despite normal innervation testing (EMG normal). Most likely explanation:",
    options: [
      { id: "a", text: "Malignant transformation of papilloma to squamous carcinoma with nerve invasion", isCorrect: false, explanation: "Malignancy would show complete paralysis or mass effect; EMG would be abnormal" },
      { id: "b", text: "Papilloma bulk mechanical mass effect + vocal cord stiffness from fibrin/exudate deposition", isCorrect: true, explanation: "RRP anterior commissure involvement: bulk mass + inflammatory exudate/fibrin coating vocal cords → stiffness → incomplete adduction. EMG normal (no denervation). Sounds like paralysis but is mechanical obstruction. Laser ablation to reduce bulk" },
      { id: "c", text: "Laryngeal spasm from chronic irritation", isCorrect: false, explanation: "Spasm would show symmetric movement dysfunction, not unilateral breathy voice" },
      { id: "d", text: "Vocal cord atrophy from prolonged immobilization during papilloma growth", isCorrect: false, explanation: "Atrophy would show thinning on laryngoscopy; EMG typically shows signs of denervation" },
    ],
    explanation: "RRP mechanical vocal cord dysfunction: bulk papillomas + fibrin coating → stiffness and reduced mobility despite normal innervation. Distinguishing true paralysis (EMG abnormal) from mechanical obstruction (EMG normal) is key. Laser therapy to reduce papilloma burden improves voice.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "7", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-06-TOP-05",
    stem: "Patient with paradoxical vocal cord movement (PVM, vocal cord dysfunction) during sleep shows normal awake laryngoscopy. Sleep-endoscopy shows bilateral vocal cord adduction during inspiration. Treatment challenge and mechanism explanation:",
    options: [
      { id: "a", text: "Neurological disorder requiring anti-seizure medication", isCorrect: false, explanation: "PVM not seizure disorder; not responsive to anti-seizure drugs" },
      { id: "b", text: "Laryngeal sensorimotor incoordination from afferent feedback dysregulation → inappropriate adduction during inspiration", isCorrect: true, explanation: "PVM (vocal cord dysfunction): abnormal laryngeal proprioception/sensorimotor control → cords adduct during inspiration instead of abduct. May be triggered by anxiety, asthma, GERD irritation. Sleep-endoscopy shows abnormality (awake may be masked by conscious control). Treatment: speech therapy, breathing techniques, identify triggers" },
      { id: "c", text: "Laryngeal dystonia (focal dystonia) requiring botulinum toxin", isCorrect: false, explanation: "While dystonia possible, PVM typically functional/behavioral, responsive to therapy" },
      { id: "d", text: "Sleep-related hypoventilation requiring CPAP support", isCorrect: false, explanation: "CPAP supports breathing; doesn't address laryngeal dysmotility" },
    ],
    explanation: "PVM (vocal cord dysfunction): functional laryngeal incoordination. Bilateral cord adduction during inspiration → partial airway obstruction, dyspnea, stridor. Awake often normal (conscious control). Sleep uncovers abnormality. Treatment: speech therapy (breathing training), address triggers (anxiety, acid reflux).",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "5", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-02-TOP-07",
    stem: "Congenital bilateral mixed hearing loss (high-frequency SNHL + low-frequency CHL) with blue sclerae, hearing aids providing excellent low-frequency amplification, but high-frequency HL not benefiting. Genetic diagnosis and explain frequency-specific pattern:",
    options: [
      { id: "a", text: "Osteogenesis imperfecta with concurrent cochlear dysplasia", isCorrect: true, explanation: "OI: ossicular dysgenesis (low-freq CHL from stiffness/mass) + cochlear dysplasia/hypoplasia (high-freq SNHL from under-developed cochlear structure). Two-mechanism HL: mechanical (ossicular) + sensorineural (cochlear). Frequency pattern from site of lesion: ossicle stiffness affects low-freq; cochlear dysplasia affects high-freq most" },
      { id: "b", text: "Pendred syndrome; thyroid abnormality + cochlear hypoplasia", isCorrect: false, explanation: "Pendred SNHL usually progressive; no CHL component" },
      { id: "c", text: "Branchio-oto-renal (BOR) syndrome; branchial/otologic/renal features", isCorrect: false, explanation: "BOR shows variable pattern; typically CHL dominant" },
      { id: "d", text: "Stickler syndrome; collagen defect affecting ossicles and cochlea", isCorrect: false, explanation: "Stickler: progressive myopia, retinal detachment; not blue sclerae" },
    ],
    explanation: "OI dual HL mechanism: ossicular dysgenesis (low-freq CHL → responsive to amplification) + cochlear dysplasia (high-freq SNHL → less responsive). Frequency-specific patterns help identify site of lesion. Hearing aids beneficial for conductive component; SNHL requires cochlear implant consideration.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "2", edition: "9th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "ENT-MOD-04-TOP-07",
    stem: "Temporal bone fracture with CSF otorrhea (beta-2 transferrin positive), conductive hearing loss, and normal facial nerve function. Imaging shows longitudinal fracture through external auditory canal with disruption of anterior malleus and intact facial canal. Surgical decision-making:",
    options: [
      { id: "a", text: "Immediate surgical repair of TM/malleus to prevent meningitis", isCorrect: false, explanation: "Immediate repair often not needed; observation first, surgery if CSF leak persists" },
      { id: "b", text: "Observation with head elevation, avoid straining; reassess in 2-4 weeks; surgery if CSF leak persists", isCorrect: true, explanation: "Longitudinal fracture with malleus disruption: majority CSF leaks seal spontaneously (70-90%) with conservative management. Facial nerve intact = no urgency for surgery. Observe with precautions; if leak persists >2-4 weeks → ossiculoplasty ± TM repair needed (meningitis risk increases with chronic leak)" },
      { id: "c", text: "MRI to assess for dural tear, then surgical repair if present", isCorrect: false, explanation: "MRI helpful for dural visualization, but presence doesn't mandate emergency repair if CSF leak minimal" },
      { id: "d", text: "Prophylactic antibiotics and ossiculoplasty regardless of CSF leak resolution", isCorrect: false, explanation: "Prophylactic antibiotics not standard; ossiculoplasty deferred until CSF leak persists" },
    ],
    explanation: "Longitudinal temporal bone fracture with CSF otorrhea: majority (70-90%) heal spontaneously with conservative management (head elevation, avoid straining, avoid nose blowing). Surgical intervention (TM repair ± ossiculoplasty) reserved for persistent leak (>2-4 weeks) due to meningitis risk. FN intact = no urgency.",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEET_PG"] as string[],
    textbookRefs: [{ book: "Logan Turner", chapter: "3", edition: "9th" }],
  },
];
