// Ophthalmology MCQs - NEXT pattern (40 questions)
// Distribution: 25% EASY (10), 40% MEDIUM (16), 25% HARD (10), 10% EXPERT (4)

export const ophthalmologyFullMcqs = [
  // ============ EASY (10 questions) ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-01-TOP-01",
    stem: "Which part of the eye is primarily responsible for refraction?",
    options: [
      { id: "a", text: "Cornea", isCorrect: true, explanation: "Cornea accounts for ~70% of total refractive power due to its curved surface" },
      { id: "b", text: "Lens", isCorrect: false, explanation: "Lens provides additional ~20%, but cornea is primary" },
      { id: "c", text: "Aqueous humor", isCorrect: false, explanation: "Transparent fluid; plays minimal refractive role" },
      { id: "d", text: "Retina", isCorrect: false, explanation: "Retina is photosensitive; doesn't refract light" },
    ],
    explanation: "The **cornea** is the primary refractive element of the eye (accounts for ~70% of refractive power). The **lens** adds accommodation and additional refraction (~20%).",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Refraction and Accommodation", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-02-TOP-01",
    stem: "In acute angle-closure glaucoma, which finding is characteristic on examination?",
    options: [
      { id: "a", text: "Mid-dilated pupil (fixed and dilated)", isCorrect: true, explanation: "Iris pushed forward by increased IOP; pupil becomes mid-dilated and fixed" },
      { id: "b", text: "Pinpoint pupil", isCorrect: false, explanation: "Occurs in acute iritis, not angle closure" },
      { id: "c", text: "Normal pupil reaction", isCorrect: false, explanation: "Affected in acute angle closure" },
      { id: "d", text: "Horner's syndrome", isCorrect: false, explanation: "Miotic pupil on affected side; not typical of angle closure" },
    ],
    explanation: "**Acute angle-closure glaucoma** presents with: Severe pain, blurred vision, redness, **mid-dilated fixed pupil** (from ischemic iris sphincter), corneal edema (hazy view), elevated IOP >40 mmHg.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Glaucoma", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-03-TOP-01",
    stem: "The leading preventable cause of blindness in India is:",
    options: [
      { id: "a", text: "Vitamin A deficiency", isCorrect: true, explanation: "Leading preventable cause in developing countries including India" },
      { id: "b", text: "Cataract", isCorrect: false, explanation: "Most common cause of blindness overall, but treatable (surgical)" },
      { id: "c", text: "Glaucoma", isCorrect: false, explanation: "Second most common; not preventable, only controllable" },
      { id: "d", text: "Retinitis pigmentosa", isCorrect: false, explanation: "Genetic; not preventable" },
    ],
    explanation: "**Vitamin A deficiency** is the **leading preventable cause of blindness** globally and in India (especially children). Progression: Night blindness → Xerosis → Corneal scarring → Blindness.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Vitamin A Deficiency", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-04-TOP-01",
    stem: "Which refractive error is characterized by the eyeball being too short?",
    options: [
      { id: "a", text: "Myopia", isCorrect: false, explanation: "Eyeball too long; light focuses in front of retina" },
      { id: "b", text: "Hyperopia (Hypermetropia)", isCorrect: true, explanation: "Eyeball too short; light focuses behind retina" },
      { id: "c", text: "Astigmatism", isCorrect: false, explanation: "Irregular corneal curvature; not related to axial length" },
      { id: "d", text: "Presbyopia", isCorrect: false, explanation: "Loss of accommodation with age; not refractive error" },
    ],
    explanation: "**Hyperopia**: Axial length SHORT (< 24mm normal); light focuses **behind retina** at infinity. Corrected with PLUS lens (convex). Opposite of myopia.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Refraction Errors", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-02-TOP-02",
    stem: "What is the normal intraocular pressure (IOP) range?",
    options: [
      { id: "a", text: "10-15 mmHg", isCorrect: false, explanation: "Too low; normal is higher" },
      { id: "b", text: "16-21 mmHg", isCorrect: true, explanation: "Normal IOP range; varies throughout day and with posture" },
      { id: "c", text: "25-30 mmHg", isCorrect: false, explanation: "Elevated; at risk for glaucoma" },
      { id: "d", text: ">35 mmHg", isCorrect: false, explanation: "Definitely abnormal; urgent treatment needed" },
    ],
    explanation: "**Normal IOP**: **16-21 mmHg** (average ~15 mmHg). IOP varies: Higher in morning, with posture change, physical exertion. Above 21 mmHg increases glaucoma risk.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Intraocular Pressure", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-05-TOP-01",
    stem: "The most common type of cataract is:",
    options: [
      { id: "a", text: "Congenital cataract", isCorrect: false, explanation: "Present at birth; less common than age-related" },
      { id: "b", text: "Age-related (nuclear sclerotic) cataract", isCorrect: true, explanation: "Most common type globally; increases with age" },
      { id: "c", text: "Secondary cataract (from trauma, inflammation)", isCorrect: false, explanation: "Important but less common than age-related" },
      { id: "d", text: "Drug-induced cataract", isCorrect: false, explanation: "Rare; only certain drugs (steroids)" },
    ],
    explanation: "**Age-related cataract** (nuclear sclerotic type) is most common cause of blindness worldwide. Caused by protein aggregation and cross-linking in lens over time.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Cataract", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-06-TOP-01",
    stem: "Which nerve is responsible for pupil constriction?",
    options: [
      { id: "a", text: "Optic nerve (CN II)", isCorrect: false, explanation: "Sensory pathway; carries light information to brain" },
      { id: "b", text: "Oculomotor nerve (CN III)", isCorrect: true, explanation: "Parasympathetic fibers control iris sphincter (constriction)" },
      { id: "c", text: "Trigeminal nerve (CN V)", isCorrect: false, explanation: "Sensory to cornea and eyelid; not pupil control" },
      { id: "d", text: "Sympathetic nerve", isCorrect: false, explanation: "Controls iris dilator; causes pupil dilation" },
    ],
    explanation: "**Pupil constriction (miosis)**: Parasympathetic via **oculomotor nerve (CN III)** → stimulates iris sphincter muscle. **Pupil dilation (mydriasis)**: Sympathetic → stimulates dilator muscle.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Anatomy of Eye Movements and Innervation", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-07-TOP-01",
    stem: "The optic disc cup-to-disc ratio in early glaucoma typically increases to:",
    options: [
      { id: "a", text: "0.3-0.4", isCorrect: false, explanation: "Still normal range" },
      { id: "b", text: "0.5-0.7", isCorrect: true, explanation: "Early glaucomatous changes; progressive cupping" },
      { id: "c", text: "0.1-0.2", isCorrect: false, explanation: "Very small cup; too small for early glaucoma" },
      { id: "d", text: ">0.9", isCorrect: false, explanation: "Advanced glaucoma with severe optic nerve damage" },
    ],
    explanation: "**Cup-to-disc (C:D) ratio** in glaucoma: Normal <0.3-0.4; Early glaucoma 0.5-0.7; Advanced >0.9. Increased cup size indicates optic nerve excavation.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Glaucoma Diagnosis", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-01-TOP-02",
    stem: "Which layer of the cornea provides the main barrier function?",
    options: [
      { id: "a", text: "Epithelium", isCorrect: true, explanation: "Tight junctions between epithelial cells form blood-aqueous barrier" },
      { id: "b", text: "Stroma", isCorrect: false, explanation: "Middle layer; provides structural support, not barrier" },
      { id: "c", text: "Endothelium", isCorrect: false, explanation: "Forms part of barrier but epithelium is primary" },
      { id: "d", text: "Descemet's membrane", isCorrect: false, explanation: "Basement membrane; structural not barrier" },
    ],
    explanation: "**Corneal epithelium** (5-6 cell layers) provides main barrier function through **tight junctions** between cells. Prevents entry of large molecules/pathogens.",
    difficulty: "EASY" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Corneal Anatomy and Physiology", edition: "8th" }],
  },

  // ============ MEDIUM (16 questions) ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-02-TOP-03",
    stem: "A patient with open-angle glaucoma shows 30% optic nerve head loss but maintains visual field. Which explains this discrepancy?",
    options: [
      { id: "a", text: "Early glaucoma can have structural damage before functional loss", isCorrect: true, findings: "Correct. Structural changes (optic disc cupping) precede visual field defects by months-years" },
      { id: "b", text: "Patient is malingering; doesn't have real disease", isCorrect: false, explanation: "No evidence; optic nerve changes are objective" },
      { id: "c", text: "Visual field testing is unreliable", isCorrect: false, explanation: "VF reliable when properly performed" },
      { id: "d", text: "Optic disc changes are due to other causes", isCorrect: false, explanation: "Cannot ignore optic disc findings" },
    ],
    explanation: "In glaucoma, **structural damage precedes functional loss**: Optic nerve cupping visible before VF defects appear. This lag allows window for early detection and intervention before vision loss.",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Glaucoma Pathophysiology", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-03-TOP-02",
    stem: "A 6-year-old child with sudden vision loss in one eye. Fundus shows retinal whitening at macula, cherry-red spot at fovea. Diagnosis?",
    options: [
      { id: "a", text: "Branch retinal artery occlusion", isCorrect: false, explanation: "Would show sectoral whitening, not cherry-red spot" },
      { id: "b", text: "Central retinal artery occlusion (CRAO)", isCorrect: true, explanation: "Retinal whitening + cherry-red spot at fovea (preserved choroidal perfusion) = classic CRAO" },
      { id: "c", text: "Retinal detachment", isCorrect: false, explanation: "Would show fold/elevation, not cherry-red spot" },
      { id: "d", text: "Acute macular neuroretinitis", isCorrect: false, explanation: "Would show optic disc swelling" },
    ],
    explanation: "**Central retinal artery occlusion (CRAO)**:\n- Sudden painless vision loss\n- Retina whitening (edema)\n- Cherry-red spot at macula (preserved choroidal perfusion)\n- Narrow arterioles\n- Emergency: Treatment within hours improves outcomes",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Retinal Vascular Occlusions", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-04-TOP-02",
    stem: "A 75-year-old with presbyopia experiences difficulty reading small print despite normal distance vision. What is the physiologic cause?",
    options: [
      { id: "a", text: "Corneal sclerosis", isCorrect: false, explanation: "Doesn't significantly affect accommodation" },
      { id: "b", text: "Loss of lens elasticity and weakened ciliary muscles", isCorrect: true, explanation: "Lens nucleus hardens; ciliary muscles weaken; accommodation reduces" },
      { id: "c", text: "Pupillary narrowing", isCorrect: false, explanation: "Contributes but not primary cause" },
      { id: "d", text: "Retinal degeneration", isCorrect: false, explanation: "Would affect all distances" },
    ],
    explanation: "**Presbyopia** (age-related accommodation loss):\n- Lens nucleus hardens (sclerosis)\n- Loss of lens elasticity\n- Ciliary muscle weakens\n- **Near point of accommodation recedes**: ~25 cm at age 8 → 50 cm at age 40 → arm's length at 50+\n- Corrected with reading glasses or bifocals",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Presbyopia and Accommodation", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-05-TOP-02",
    stem: "Which cataract type is associated with chronic corticosteroid use?",
    options: [
      { id: "a", text: "Posterior subcapsular cataract", isCorrect: true, explanation: "Characteristic of long-term systemic or topical steroid use" },
      { id: "b", text: "Nuclear sclerotic cataract", isCorrect: false, explanation: "Age-related, not steroid-induced" },
      { id: "c", text: "Anterior subcapsular cataract", isCorrect: false, explanation: "Less common with steroids" },
      { id: "d", text: "Polar cataract", isCorrect: false, explanation: "Congenital; not steroid-related" },
    ],
    explanation: "**Drug-induced cataracts**:\n- **Posterior subcapsular**: Steroids (most common drug-induced), myotonic dystrophy\n- **Nuclear sclerotic**: Phenothiazines, amiodarone\n- **Other drugs**: Chlorpromazine, tamoxifen, finasteride",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Recall",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Drug-Induced Ocular Effects", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-06-TOP-02",
    stem: "A patient with Horner's syndrome has ptosis, miosis, and anhidrosis on the affected side. This indicates a lesion where?",
    options: [
      { id: "a", text: "First-order neuron (central): Brain to neck", isCorrect: true, explanation: "Anhidrosis and other signs present; suggests central/preganglionic" },
      { id: "b", text: "Second-order neuron (preganglionic): Neck to superior cervical ganglion", isCorrect: false, explanation: "Would not have anhidrosis" },
      { id: "c", text: "Third-order neuron (postganglionic): Ganglion to orbit", isCorrect: false, explanation: "Most common; miosis + ptosis but NO anhidrosis" },
      { id: "d", text: "Sympathetic root in spinal cord", isCorrect: false, explanation: "Would affect different distribution" },
    ],
    explanation: "**Horner's syndrome localization**:\n- **Central/Preganglionic**: Anhidrosis + ptosis + miosis (facial and neck sweating loss)\n- **Postganglionic**: Ptosis + miosis only (NO anhidrosis; sudomotor fibers already branched)\n- Anhidrosis on forehead = central/preganglionic\n- Anhidrosis on arm = preganglionic (T1-T2 involvement)",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Neuro-ophthalmology - Horner's Syndrome", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-07-TOP-02",
    stem: "In primary angle-closure glaucoma pathophysiology, what is the PRIMARY mechanism of angle closure?",
    options: [
      { id: "a", text: "Ciliary body mass effect", isCorrect: false, explanation: "Occurs in secondary angle closure" },
      { id: "b", text: "Iris bombe from posterior synechiae", isCorrect: false, explanation: "Secondary angle closure mechanism" },
      { id: "c", text: "Pupillary block: iris pushed forward by lens", isCorrect: true, explanation: "Primary mechanism: thick lens + short eye pushes iris forward → angle closure" },
      { id: "d", text: "Trabecular meshwork sclerosis", isCorrect: false, explanation: "Open-angle mechanism, not primary closure" },
    ],
    explanation: "**Primary angle closure**: **Pupillary block** mechanism:\n1. Short axial length + thick lens (anatomically prone)\n2. Pupillary block: Lens-iris contact prevents aqueous flow\n3. Iris bows forward → angles close\n4. Sudden IOP rise (acute) or slow progression (chronic)\n\n**Risk factors**: Hyperopia, short eye, thick lens, narrow angles on gonioscopy",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Angle-Closure Glaucoma", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-01-TOP-03",
    stem: "A patient with corneal scarring from chemical burn has reduced vision despite clear media. Which is the MOST likely reason?",
    options: [
      { id: "a", text: "Irregular astigmatism from scar", isCorrect: true, explanation: "Chemical burns cause scarring → irregular corneal surface → optical aberrations" },
      { id: "b", text: "Retinal damage from chemical exposure", isCorrect: false, explanation: "Chemical doesn't typically reach retina" },
      { id: "c", text: "Optic nerve atrophy", isCorrect: false, explanation: "Not directly affected by surface chemical burn" },
      { id: "d", text: "Posterior segment inflammation", isCorrect: false, explanation: "Surface burns don't typically involve posterior" },
    ],
    explanation: "**Chemical burn complications**:\n- **Acute**: Corneal epithelial damage, edema\n- **Chronic**: Corneal scarring → irregular astigmatism → reduced vision despite clear media\n- **Severe**: Symblepharon formation, entropion, ocular surface disease\n- **Treatment**: Early copious irrigation, lubrication, potential transplantation",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Chemical Burns to Eye", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-02-TOP-04",
    stem: "A patient on timolol (beta-blocker) drops for glaucoma develops exercise intolerance and bradycardia. What is the mechanism?",
    options: [
      { id: "a", text: "Topical timolol absorbed systemically → reduces heart rate", isCorrect: true, explanation: "Topical ophthalmic drugs absorbed through nasolacrimal drainage → systemic effects" },
      { id: "b", text: "Direct effect on cornea reducing oxygen", isCorrect: false, explanation: "Doesn't explain systemic symptoms" },
      { id: "c", text: "Allergy to timolol", isCorrect: false, explanation: "Would cause local symptoms first" },
      { id: "d", text: "IOP reduction causing systemic hypotension", isCorrect: false, explanation: "Mechanism unrelated" },
    ],
    explanation: "**Systemic absorption of topical eye drops**:\n- **Route**: Nasolacrimal duct drainage → nasal mucosa absorption\n- **Risks**: Bradycardia (beta-blockers), hypotension (alpha-blockers), wheezing (beta-blockers in asthma)\n- **Prevention**: Nasolacrimal occlusion (1 minute after drop), use lowest concentration\n- **Contraindication**: Beta-blockers in asthma/COPD, heart block",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Glaucoma Management", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-03-TOP-03",
    stem: "A diabetic patient develops nonproliferative diabetic retinopathy (NPDR) with microaneurysms and retinal hemorrhages. What is the next progression if uncontrolled?",
    options: [
      { id: "a", text: "Proliferative diabetic retinopathy (PDR)", isCorrect: true, explanation: "Progressive ischemia → neovascularization of optic disc/periphery" },
      { id: "b", text: "Immediate retinal detachment", isCorrect: false, explanation: "Occurs in advanced PDR, not NPDR" },
      { id: "c", text: "Immediate vision loss", isCorrect: false, explanation: "NPDR may not affect vision initially" },
      { id: "d", text: "Cataract formation", isCorrect: false, explanation: "Unrelated progression of retinopathy" },
    ],
    explanation: "**Diabetic Retinopathy Progression**:\n1. **NPDR**: Microaneurysms, hemorrhages, exudates; no neovascularization\n2. **PDR**: Neovascularization of disc (NVD) or elsewhere (NVE) from ischemia\n3. **Complications**: Vitreous hemorrhage, tractional retinal detachment, rubeotic glaucoma\n4. **Prevention**: Tight glucose + BP control, regular eye exams, laser/anti-VEGF when needed",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Diabetic Retinopathy", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-04-TOP-03",
    stem: "A neonate with congenital cataracts and intellectual disability is found to have maternal rubella infection during first trimester. Which other ocular finding is expected?",
    options: [
      { id: "a", text: "Retinopathy of prematurity", isCorrect: false, explanation: "Related to oxygen, not intrauterine infection" },
      { id: "b", text: "Retinitis with salt-and-pepper appearance", isCorrect: true, explanation: "Congenital rubella causes diffuse retinal involvement" },
      { id: "c", text: "Optic nerve hypoplasia", isCorrect: false, explanation: "More common in other intrauterine infections" },
      { id: "d", text: "Posterior lenticonus", isCorrect: false, explanation: "Associated with Alport syndrome, not rubella" },
    ],
    explanation: "**Congenital Rubella Syndrome (CRS)**:\n- **Ocular manifestations**: Cataract (most common), **retinitis** (\"salt-and-pepper\" retinopathy), glaucoma, corneal opacities\n- **Systemic**: Deafness, cardiac defects, intellectual disability, growth retardation\n- **Prevention**: MMR vaccination before pregnancy (teratogenic live vaccine in pregnancy)",
    difficulty: "MEDIUM" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Congenital Infections", edition: "8th" }],
  },

  // ============ HARD (10 questions) ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-02-TOP-05",
    stem: "A patient with ocular hypertension (IOP 24 mmHg) has normal optic disc and visual field. No treatment started. After 5 years, develops glaucomatous optic neuropathy. What explains the delayed onset?",
    options: [
      { id: "a", text: "Ocular hypertension only occasionally progresses to glaucoma", isCorrect: true, explanation: "Ocular HTN has ~20-30% risk of converting to open-angle glaucoma over 5-15 years" },
      { id: "b", text: "Patient didn't follow treatment recommendations", isCorrect: false, explanation: "No treatment was started initially" },
      { id: "c", text: "IOP spontaneously increased after years", isCorrect: false, explanation: "May have, but HTN was already present" },
      { id: "d", text: "Diagnosis of glaucoma is incorrect", isCorrect: false, explanation: "Objective evidence of optic nerve damage" },
    ],
    explanation: "**Ocular hypertension (OHT)**:\n- **Definition**: IOP >21 mmHg without optic nerve damage or visual field loss\n- **Risk of conversion**: 20-30% develop glaucoma over 5-15 years (variable)\n- **Risk factors**: Higher IOP, older age, thin cornea, high cup-to-disc ratio\n- **OHTS study**: IOP-lowering delays or prevents conversion to glaucoma\n- **Management**: Monitor closely vs. treat based on risk factors",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Ocular Hypertension and Glaucoma Risk", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-03-TOP-04",
    stem: "A 45-year-old with myopic refraction develops sudden flashes of light, floaters, and shadow in superior temporal field. What is the diagnosis and emergency management?",
    options: [
      { id: "a", text: "Posterior vitreous detachment with flashes; observation if asymptomatic", isCorrect: false, explanation: "May be present but shadow suggests retinal detachment" },
      { id: "b", text: "Retinal tear with superior temporal retinal detachment; urgent laser/cryo", isCorrect: true, explanation: "Flashes (traction) + floaters (hemorrhage) + shadow = RD until proven otherwise" },
      { id: "c", text: "Vitreous hemorrhage; wait 3 months for blood absorption", isCorrect: false, explanation: "May accompany RD but RD needs urgent treatment" },
      { id: "d", text: "Migraine with aura; reassurance", isCorrect: false, explanation: "Wouldn't explain objective shadow/field loss" },
    ],
    explanation: "**Retinal detachment (RD) emergency**:\n- **Symptoms**: Flashes (retinal traction), floaters, shadow/curtain\n- **Higher risk**: High myopia, prior RD, family history, lattice degeneration\n- **Urgency**: Same-day to emergency ophthalmology referral\n- **Treatment**: Laser (tears) or cryotherapy (prevention) or scleral buckle/vitrectomy\n- **Prognosis**: Better if macula not detached (early intervention)",
    difficulty: "HARD" as const,
    bloomsLevel: "ProblemSolving",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Retinal Detachment", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-05-TOP-03",
    stem: "Following cataract surgery, patient develops corneal edema, pain, and reduced vision despite clear lens. What complication is likely?",
    options: [
      { id: "a", text: "Endothelial cell loss causing corneal decompensation", isCorrect: true, explanation: "Surgical trauma causes endothelial cell loss → inability to pump water → corneal edema" },
      { id: "b", text: "Anterior chamber inflammation only", isCorrect: false, explanation: "Would improve with steroids; endothelial damage persists" },
      { id: "c", text: "Epithelial erosion from contact lens use", isCorrect: false, explanation: "Can occur post-op but doesn't explain persistent edema" },
      { id: "d", text: "Posterior capsular opacification", isCorrect: false, explanation: "Doesn't cause corneal edema" },
    ],
    explanation: "**Corneal edema post-cataract surgery**:\n- **Cause**: Endothelial cell loss from surgical trauma (phaco burns, instrument trauma)\n- **Mechanism**: Endothelial pump failure → fluid accumulation → stromal edema\n- **Clinical**: Hazy cornea, reduced vision, pain (corneal sensitivity)\n- **Risk**: Longer phaco time, harder nucleus, anterior chamber IOL\n- **Treatment**: Hypertonic saline drops, topical steroids (early), corneal transplant if permanent",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Cataract Surgery Complications", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-01-TOP-04",
    stem: "A patient develops Stevens-Johnson syndrome (SJS) with ocular involvement. What is the long-term corneal consequence if untreated?",
    options: [
      { id: "a", text: "Anterior uveitis", isCorrect: false, explanation: "Not typical long-term consequence" },
      { id: "b", text: "Cicatricial changes leading to symblepharon and surface keratopathy", isCorrect: true, explanation: "SJS causes conjunctival scarring → symblepharon → corneal opacification" },
      { id: "c", text: "Posterior synechiae", isCorrect: false, explanation: "Occurs with iritis, not SJS" },
      { id: "d", text: "Cataract formation", isCorrect: false, explanation: "Not typical of SJS" },
    ],
    explanation: "**Ocular SJS/TEN**:\n- **Acute**: Severe conjunctivitis, keratitis, anterior uveitis\n- **Chronic**: **Cicatricial changes**: Symblepharon (conjunctival-eyelid adhesions), trichiasis, entropion, ocular surface disease\n- **Corneal**: Progressive keratopathy, neovascularization, scarring → vision loss\n- **Prevention**: Aggressive management during acute phase (lubricants, steroids, ocular surface care)",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Stevens-Johnson Syndrome", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-06-TOP-03",
    stem: "A patient develops binasal hemianopia. Which anatomic location of the lesion explains this field defect?",
    options: [
      { id: "a", text: "Optic chiasm: Compression from lateral structures", isCorrect: true, explanation: "Lateral compression of chiasm affects crossing nasal fibers → binasal hemianopia" },
      { id: "b", text: "Optic nerve: Unilateral demyelination", isCorrect: false, explanation: "Would cause monocular visual loss" },
      { id: "c", text: "Optic tract: Homonymous hemianopia", isCorrect: false, explanation: "Different field pattern" },
      { id: "d", text: "Optic radiation: Superior or inferior quadrantanopia", isCorrect: false, explanation: "Different pattern" },
    ],
    explanation: "**Visual field patterns by lesion location**:\n- **Optic nerve**: Monocular vision loss (scotoma)\n- **Chiasm (central compression)**: Bitemporal hemianopia (pressure from pituitary)\n- **Chiasm (lateral compression)**: **Binasal hemianopia** (affects nasal fibers bilaterally)\n- **Optic tract**: Homonymous hemianopia\n- **Optic radiation/cortex**: Homonymous hemianopia (superior or inferior quadrants)",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Neuro-ophthalmology - Visual Fields", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-04-TOP-04",
    stem: "A patient with high myopia (-12 diopters) develops lattice degeneration in peripheral retina. What is the increased risk?",
    options: [
      { id: "a", text: "Myopic macular degeneration only", isCorrect: false, explanation: "Occurs but not related to lattice" },
      { id: "b", text: "Retinal holes and detachment from tractional forces", isCorrect: true, explanation: "Lattice areas are weak zones prone to holes and subsequent detachment" },
      { id: "c", text: "Proliferative diabetic retinopathy", isCorrect: false, explanation: "Unrelated; requires diabetes" },
      { id: "d", text: "Retinal pigmentary dystrophy", isCorrect: false, explanation: "Separate condition" },
    ],
    explanation: "**Myopic maculopathy complications**:\n- **Lattice degeneration**: Atrophic area of peripheral retina\n- **Risk**: Retinal holes (higher risk with posterior vitreous detachment) → retinal detachment\n- **Myopic macular degeneration**: Central vision loss from choroidal neovascularization\n- **Prevention/Management**: Regular eye exams, laser prophylaxis if symptomatic tears, patient education on warning signs",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "High Myopia Complications", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-07-TOP-03",
    stem: "A patient treated with prostaglandin analog (latanoprost) for glaucoma develops increased iris pigmentation and eyelash growth. What is the mechanism?",
    options: [
      { id: "a", text: "Allergic reaction to the medication", isCorrect: false, explanation: "Would cause other allergic symptoms" },
      { id: "b", text: "Stimulation of melanogenesis in iris and hair follicles", isCorrect: true, explanation: "Prostaglandin analogs increase melanin production and eyelash proliferation" },
      { id: "c", text: "Increased intraocular pressure effect", isCorrect: false, explanation: "IOP lowering doesn't cause pigmentation" },
      { id: "d", text: "Bacterial contamination of drops", isCorrect: false, explanation: "Would cause inflammation, not pigmentation" },
    ],
    explanation: "**Prostaglandin analog side effects**:\n- **Iris darkening**: Increased melanogenesis in iris; irreversible (permanent change)\n- **Eyelash growth**: Anagen (growth) phase lengthening\n- **Periocular pigmentation**: Darkening of skin around eye\n- **Other**: Conjunctival injection, cystoid macular edema (in post-transplant eyes)\n- **Note**: Darkening may not occur in all patients (depends on baseline pigmentation)",
    difficulty: "HARD" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Glaucoma Medical Management", edition: "8th" }],
  },

  // ============ EXPERT (4 questions) ============
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-02-TOP-06",
    stem: "Using Goldmann applanation tonometry in a patient with corneal astigmatism (+3.00D cylinder), the measured IOP may be artificially altered. What is the correction principle?",
    options: [
      { id: "a", text: "Add 1 mmHg per diopter of cylinder; no correction needed usually", isCorrect: true, explanation: "With-the-rule astigmatism: IOP falsely high; Against-the-rule: falsely low; correction ≈0.7-1 mmHg per diopter" },
      { id: "b", text: "Always subtract 3 mmHg from measured IOP", isCorrect: false, explanation: "Correction depends on axis and magnitude" },
      { id: "c", text: "Use rebound tonometry instead", isCorrect: false, explanation: "Gadget but not standard practice; still affected" },
      { id: "d", text: "No correction needed; tonometry accurate regardless", isCorrect: false, explanation: "Astigmatism significantly affects measurement" },
    ],
    explanation: "**Corneal astigmatism effect on IOP measurement**:\n- **With-the-rule** (vertical cylinder, common): Steeper vertical axis → contact more rigid → IOP falsely HIGH\n- **Against-the-rule**: IOP falsely LOW\n- **Correction**: Approximately 0.7-1 mmHg per diopter of cylinder\n- **Practical**: For significant astigmatism (>2-3D), note discrepancy but don't always need correction\n- **Alternative**: Use rebound tonometry if concerned; less affected by corneal factors",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Tonometry and IOP Measurement", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-03-TOP-05",
    stem: "A diabetic patient develops proliferative diabetic retinopathy with extensive neovascularization of disc (NVD). Why is the risk of sudden vision loss high?",
    options: [
      { id: "a", text: "Neovessels are friable and prone to bleeding into vitreous", isCorrect: true, explanation: "NV are immature, lack supporting tissue → vitreous hemorrhage → sudden complete vision loss" },
      { id: "b", text: "New vessels directly compress optic nerve", isCorrect: false, explanation: "Mechanical compression less likely than bleeding" },
      { id: "c", text: "Associated retinal edema obscures vision permanently", isCorrect: false, explanation: "Edema can improve; hemorrhage is more critical" },
      { id: "d", text: "Rubeotic glaucoma develops immediately", isCorrect: false, explanation: "Can develop but not immediate; hemorrhage more acute threat" },
    ],
    explanation: "**PDR complications leading to vision loss**:\n1. **Vitreous hemorrhage** (most common cause of sudden blindness in PDR): Friable new vessels bleed\n2. **Tractional retinal detachment**: Fibrosis and contraction pull retina\n3. **Rubeotic glaucoma**: Angle closure from ectopic iris vascularization (late)\n4. **Management**: Anti-VEGF (bevacizumab, ranibizumab, aflibercept) + scatter laser or vitrectomy",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1", "NEET_PG"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Proliferative Diabetic Retinopathy Management", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-05-TOP-04",
    stem: "A patient develops posterior capsular opacification (PCO) 6 months after cataract surgery. Which cellular mechanism explains this complication?",
    options: [
      { id: "a", text: "Inflammation from surgical trauma", isCorrect: false, explanation: "Would improve; PCO is cellular issue" },
      { id: "b", text: "Epithelial cell migration onto posterior capsule with transdifferentiation to fibroblast-like cells", isCorrect: true, explanation: "Epithelial cells proliferate, migrate, transform → fibrosis of capsule" },
      { id: "c", text: "Calcification of lens proteins", isCorrect: false, explanation: "Not mechanism of PCO" },
      { id: "d", text: "Bacterial colonization on IOL surface", isCorrect: false, explanation: "Would cause endophthalmitis" },
    ],
    explanation: "**Posterior Capsular Opacification (PCO/\"after-cataract\") mechanism**:\n- **Cellular**: Equatorial lens epithelial cells → proliferation and migration onto posterior capsule\n- **Transformation**: Epithelial-mesenchymal transition (EMT) → myofibroblast-like cells\n- **Fibrosis**: Collagen deposition → capsular opacity\n- **Risk factors**: Young age, pre-op inflammation, rough posterior capsule\n- **Treatment**: YAG laser capsulotomy (creates opening in opacified capsule, restores light path)",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Posterior Capsular Opacification", edition: "8th" }],
  },
  {
    type: "MCQ_SINGLE" as const,
    topicCode: "OP-MOD-06-TOP-04",
    stem: "A patient with Marcus Gunn pupil (afferent pupillary defect, APD) demonstrates asymmetry in the pupillary light reflex. Which nerve segment is primarily affected?",
    options: [
      { id: "a", text: "Optic nerve (CN II) - afferent pathway", isCorrect: true, explanation: "Afferent pupillary defect indicates optic nerve damage; efferent (CN III) intact" },
      { id: "b", text: "Oculomotor nerve (CN III) - efferent pathway", isCorrect: false, explanation: "Would affect other CN III functions (eye movement, lid)" },
      { id: "c", text: "Ciliary body innervation", isCorrect: false, explanation: "Not directly involved" },
      { id: "d", text: "Iris sphincter muscle", isCorrect: false, explanation: "Would be secondary to CN III damage" },
    ],
    explanation: "**Afferent Pupillary Defect (Marcus Gunn Pupil)**:\n- **Definition**: Asymmetric pupillary response to light indicating optic nerve (CN II) damage\n- **Mechanism**: Reduced light information → reduced parasympathetic output → smaller pupil on affected side\n- **Causes**: Optic neuritis, optic nerve compression, retinal disease (if extensive)\n- **Test**: Swinging flashlight test - affected pupil dilates when light swung to it (relative afferent defect)\n- **CN III (efferent) defect**: Pupil doesn't respond to light on either side + eye movement abnormality",
    difficulty: "EXPERT" as const,
    bloomsLevel: "Analysis",
    examTags: ["NEXT_STEP1"] as string[],
    textbookRefs: [{ book: "Ophthalmology by Khurana", chapter: "Pupillary Abnormalities", edition: "8th" }],
  },
];